var _____resources___i_create_subtask_with_resolution_action_mode_8cs =
[
    [ "EleWise.ELMA.Documents.Models.__Resources_ICreateSubtaskWithResolutionActionModel", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_____resources___i_create_subtask_with_resolution_action_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_____resources___i_create_subtask_with_resolution_action_model" ]
];