var _abstract_db_metadata_provider_8cs =
[
    [ "EleWise.ELMA.Runtime.Db.Migrator.Providers.AbstractDbMetadataProvider", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_db_1_1_migrator_1_1_providers_1_1_abstract_db_metadata_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_db_1_1_migrator_1_1_providers_1_1_abstract_db_metadata_provider" ]
];