var _active_sessions_model_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.Models.ActiveSessionsModel", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_active_sessions_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_active_sessions_model" ],
    [ "EleWise.ELMA.BPM.Web.Security.Models.ActiveSessionsModel.UserSessionsModel", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_active_sessions_model_1_1_user_sessions_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_active_sessions_model_1_1_user_sessions_model" ]
];