var _action_toolbar_serialized_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Content.Models.Toolbar.ActionToolbarSerialized", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_models_1_1_toolbar_1_1_action_toolbar_serialized.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_models_1_1_toolbar_1_1_action_toolbar_serialized" ]
];