var _add_process_popup_view_model_8cs =
[
    [ "EleWise.ELMA.CRM.Workflow.Processes.Web.Models.AddProcessPopupViewModel", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_web_1_1_models_1_1_add_process_popup_view_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_web_1_1_models_1_1_add_process_popup_view_model" ]
];