var _add_project_plan_work_log_popup_view_model_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Models.AddProjectPlanWorkLogPopupViewModel", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_add_project_plan_work_log_popup_view_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_add_project_plan_work_log_popup_view_model" ]
];