var _add_template_periodicity_filter_provider_8cs =
[
    [ "EleWise.ELMA.KPI.Web.Components.PerformanceMatrix.AddTemplatePeriodicityFilterProvider", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_components_1_1_performance_matrix_1_1_add_template_periodicity_filter_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_components_1_1_performance_matrix_1_1_add_template_periodicity_filter_provider" ]
];