var _all_project_tasks_portlet_personalization_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.AllProjectTasksPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_all_project_tasks_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_all_project_tasks_portlet_personalization" ]
];