var _approval_task_quick_mode_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Integration.Portlets.ApprovalTaskQuickMode", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_integration_1_1_portlets_1_1_approval_task_quick_mode.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_integration_1_1_portlets_1_1_approval_task_quick_mode" ]
];