var _approvement_task_docflow_listener_8cs =
[
    [ "EleWise.ELMA.Documents.Listeners.ApprovementTaskDocflowListener", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_listeners_1_1_approvement_task_docflow_listener.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_listeners_1_1_approvement_task_docflow_listener" ]
];