var _approvement_is_active_exception_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Exceptions.ApprovementIsActiveException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_exceptions_1_1_approvement_is_active_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_exceptions_1_1_approvement_is_active_exception" ]
];