var _approvement_list_export_info_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Models.ApprovementListExportInfo", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_models_1_1_approvement_list_export_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_models_1_1_approvement_list_export_info" ]
];