var _artifact_data_base_decorator_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Shapes.Decorators.ArtifactDataBaseDecorator", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_decorators_1_1_artifact_data_base_decorator.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_decorators_1_1_artifact_data_base_decorator" ]
];