var _assigment_selectable_grid_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.AssigmentSelectableGridProvider", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_assigment_selectable_grid_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_assigment_selectable_grid_provider" ]
];