var _assembly_reference_type_descriptor_8cs =
[
    [ "EleWise.ELMA.Model.Scripts.Types.AssemblyReferenceTypeDescriptor", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_scripts_1_1_types_1_1_assembly_reference_type_descriptor.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_scripts_1_1_types_1_1_assembly_reference_type_descriptor" ]
];