var _automatic_currency_import_controller_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Controllers.ExchangeRates.AutomaticCurrencyImportController", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_controllers_1_1_exchange_rates_1_1_automatic_currency_import_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_controllers_1_1_exchange_rates_1_1_automatic_currency_import_controller" ]
];