var _b_p_m_n_root_activity_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Activities.BPMNRootActivity", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_b_p_m_n_root_activity.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_b_p_m_n_root_activity" ],
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Activities.BPMNRootActivity.Info", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_b_p_m_n_root_activity_1_1_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_b_p_m_n_root_activity_1_1_info" ]
];