var _back_to_project_button_extension_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.BackToProjectButtonExtension", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_back_to_project_button_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_back_to_project_button_extension" ]
];