var _bank_details_in_russia_controller_8cs =
[
    [ "EleWise.ELMA.CRM.RU.Web.Controllers.BankDetailsInRussiaController", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_r_u_1_1_web_1_1_controllers_1_1_bank_details_in_russia_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_r_u_1_1_web_1_1_controllers_1_1_bank_details_in_russia_controller" ]
];