var _basic_shape_template_harvester_8cs =
[
    [ "Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.BasicShapeTemplateHarvester", "class_orchard_1_1_display_management_1_1_descriptors_1_1_shape_template_strategy_1_1_basic_shape_template_harvester.html", "class_orchard_1_1_display_management_1_1_descriptors_1_1_shape_template_strategy_1_1_basic_shape_template_harvester" ]
];