var _base_entity_action_history_collector_related_8cs =
[
    [ "EleWise.ELMA.Events.Audit.BaseEntityActionHistoryCollectorRelated", "class_ele_wise_1_1_e_l_m_a_1_1_events_1_1_audit_1_1_base_entity_action_history_collector_related.html", "class_ele_wise_1_1_e_l_m_a_1_1_events_1_1_audit_1_1_base_entity_action_history_collector_related" ]
];