var _base_skip_entity_import_resolver_8cs =
[
    [ "EleWise.ELMA.Deploy.Import.ExtensionPoints.BaseSkipEntityImportResolver", "class_ele_wise_1_1_e_l_m_a_1_1_deploy_1_1_import_1_1_extension_points_1_1_base_skip_entity_import_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_deploy_1_1_import_1_1_extension_points_1_1_base_skip_entity_import_resolver" ]
];