var _book_external_data_metadata_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Metadata.BookExternalDataMetadata", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_metadata_1_1_book_external_data_metadata.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_metadata_1_1_book_external_data_metadata" ]
];