var _book_external_data_input_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Web.Inputs.BookExternalDataInput", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_web_1_1_inputs_1_1_book_external_data_input.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_web_1_1_inputs_1_1_book_external_data_input" ]
];