var _book_external_data_descriptor_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Types.BookExternalDataDescriptor", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_types_1_1_book_external_data_descriptor.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_types_1_1_book_external_data_descriptor" ]
];