var _bulk_data_import_exception_8cs =
[
    [ "EleWise.ELMA.Common.BulkDataImport.Exceptions.BulkDataImportException", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_bulk_data_import_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_bulk_data_import_exception" ]
];