var _business_rule_access_view_item_8cs =
[
    [ "EleWise.ELMA.BusinessRules.ViewItems.BusinessRules.BusinessRuleAccessViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_business_rules_1_1_business_rule_access_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_business_rules_1_1_business_rule_access_view_item" ]
];