var _business_rule_version_approval_task_actions_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Models.BusinessRuleVersionApprovalTaskActions", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_models_1_1_business_rule_version_approval_task_actions.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_models_1_1_business_rule_version_approval_task_actions" ]
];