var _business_rule_version_controller_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Web.Controllers.BusinessRuleVersionController", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_controllers_1_1_business_rule_version_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_controllers_1_1_business_rule_version_controller" ]
];