var _business_rule_element_8cs =
[
    [ "EleWise.ELMA.BusinessRules.BPMN.Diagrams.Elements.BusinessRuleElement", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_business_rule_element.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_business_rule_element" ],
    [ "EleWise.ELMA.BusinessRules.BPMN.Diagrams.Elements.BusinessRuleElement.ToolboxItem", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_business_rule_element_1_1_toolbox_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_business_rule_element_1_1_toolbox_item" ]
];