var _cache_query_call_metric_aggregator_8cs =
[
    [ "EleWise.ELMA.Diagnostics.Metrics.Impl.Aggregators.CacheQueryCallMetricAggregator", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_metrics_1_1_impl_1_1_aggregators_1_1_cache_query_call_metric_aggregator.html", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_metrics_1_1_impl_1_1_aggregators_1_1_cache_query_call_metric_aggregator" ]
];