var _calendar_event_profile_action_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Calendar.Extensions.CalendarEventProfileAction", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_calendar_1_1_extensions_1_1_calendar_event_profile_action.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_calendar_1_1_extensions_1_1_calendar_event_profile_action" ]
];