var _capi_com_auth_content_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.Components.CapiComAuthContentProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_components_1_1_capi_com_auth_content_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_components_1_1_capi_com_auth_content_provider" ]
];