var _change_status_document_history_model_8cs =
[
    [ "EleWise.ELMA.Documents.Models.ChangeStatusDocumentHistoryModel", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_change_status_document_history_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_change_status_document_history_model" ]
];