var _channel_instance_default_permission_8cs =
[
    [ "EleWise.ELMA.Messages.Security.ChannelInstanceDefaultPermission", "class_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_security_1_1_channel_instance_default_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_security_1_1_channel_instance_default_permission" ]
];