var _change_author_property_handler_ignore_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Components.ChangeAuthorPropertyHandlerIgnoreProvider", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_change_author_property_handler_ignore_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_change_author_property_handler_ignore_provider" ]
];