var _change_date_calendar_event_history_model_8cs =
[
    [ "EleWise.ELMA.Calendar.Models.ChangeDateCalendarEventHistoryModel", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_models_1_1_change_date_calendar_event_history_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_models_1_1_change_date_calendar_event_history_model" ]
];