var _change_permissions_on_document_swimlane_changed_handler_8cs =
[
    [ "EleWise.ELMA.Documents.Components.ChangePermissionsOnDocumentSwimlaneChangedHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_change_permissions_on_document_swimlane_changed_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_change_permissions_on_document_swimlane_changed_handler" ]
];