var _change_process_version_history_model_8cs =
[
    [ "EleWise.ELMA.Workflow.Audit.HistoryModels.ChangeProcessVersionHistoryModel", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_audit_1_1_history_models_1_1_change_process_version_history_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_audit_1_1_history_models_1_1_change_process_version_history_model" ]
];