var _change_process_version_no_action_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.ChangeProcessVersion.ChangeProcessVersionNoAction", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_change_process_version_1_1_change_process_version_no_action.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_change_process_version_1_1_change_process_version_no_action" ]
];