var _change_status_matrix_history_model_8cs =
[
    [ "EleWise.ELMA.KPI.Models.Performance.ChangeStatusMatrixHistoryModel", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_performance_1_1_change_status_matrix_history_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_performance_1_1_change_status_matrix_history_model" ]
];