var _collection_history_property_row_display_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.Components.CollectionHistoryPropertyRowDisplay", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_components_1_1_collection_history_property_row_display.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_components_1_1_collection_history_property_row_display" ]
];