var _column_header_model_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Models.BusinessRulesTable.ColumnHeaderModel", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_models_1_1_business_rules_table_1_1_column_header_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_models_1_1_business_rules_table_1_1_column_header_model" ]
];