var _column_visibility_handler_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Integration.Tasks.ColumnVisibilityHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_tasks_1_1_column_visibility_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_tasks_1_1_column_visibility_handler" ]
];