var _composite_exception_for_processes_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.CompositeExceptionForProcesses", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_composite_exception_for_processes.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_composite_exception_for_processes" ]
];