var _completed_associated_process_handler_8cs =
[
    [ "EleWise.ELMA.Projects.Notifications.CompletedAssociatedProcessHandler", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_notifications_1_1_completed_associated_process_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_notifications_1_1_completed_associated_process_handler" ]
];