var _comment_documents_action_web_handler_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.CommentDocumentsActionWebHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_comment_documents_action_web_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_comment_documents_action_web_handler" ]
];