var _content_part_field_definition_record_8cs =
[
    [ "Orchard.Core.Settings.Metadata.Records.ContentPartFieldDefinitionRecord", "class_orchard_1_1_core_1_1_settings_1_1_metadata_1_1_records_1_1_content_part_field_definition_record.html", "class_orchard_1_1_core_1_1_settings_1_1_metadata_1_1_records_1_1_content_part_field_definition_record" ]
];