var _contractor_legal_scoring_settings_8cs =
[
    [ "EleWise.ELMA.CRM.Components.Scoring.ContractorLegalScoringSettings", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_components_1_1_scoring_1_1_contractor_legal_scoring_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_components_1_1_scoring_1_1_contractor_legal_scoring_settings" ]
];