var _convert_document_process_references_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.Components.ConvertDocumentProcessReferencesExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_convert_document_process_references_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_convert_document_process_references_extension" ]
];