var _confirm_participation_recipient_handler_8cs =
[
    [ "EleWise.ELMA.Calendar.Notifications.ConfirmParticipationRecipientHandler", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_confirm_participation_recipient_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_confirm_participation_recipient_handler" ]
];