var _context_variable_code_item_tool_box_item_8cs =
[
    [ "EleWise.ELMA.ScriptDesigner.ToolBoxItems.ContextVariableCodeItemToolBoxItem", "class_ele_wise_1_1_e_l_m_a_1_1_script_designer_1_1_tool_box_items_1_1_context_variable_code_item_tool_box_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_script_designer_1_1_tool_box_items_1_1_context_variable_code_item_tool_box_item" ]
];