var _contracts_change_permissions_8cs =
[
    [ "EleWise.ELMA.Documents.Contracts.Components.ContractsChangePermissions", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_components_1_1_contracts_change_permissions.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_components_1_1_contracts_change_permissions" ]
];