var _contractor_dublicates_property_view_item_adjustment_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.ContractorDublicatesPropertyViewItemAdjustment", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_contractor_dublicates_property_view_item_adjustment.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_contractor_dublicates_property_view_item_adjustment" ],
    [ "EleWise.ELMA.CRM.Web.Components.ContactContractorPropertyViewItemAdjustment", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_contact_contractor_property_view_item_adjustment.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_contact_contractor_property_view_item_adjustment" ]
];