var _create_subtask_documents_action_handler_8cs =
[
    [ "EleWise.ELMA.Documents.Components.CreateSubtaskDocumentsActionHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_create_subtask_documents_action_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_create_subtask_documents_action_handler" ]
];