var _create_document_sub_task_base_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Components.CreateDocumentSubTaskBase", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_create_document_sub_task_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_create_document_sub_task_base" ]
];