var _create_document_task_feed_object_group_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Components.Feed.CreateDocumentTaskFeedObjectGroupExtension", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_feed_1_1_create_document_task_feed_object_group_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_feed_1_1_create_document_task_feed_object_group_extension" ]
];