var _create_document_action_provider_8cs =
[
    [ "EleWise.ELMA.Documents.Web.ContentLinkTypeProviders.CreateDocumentActionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_content_link_type_providers_1_1_create_document_action_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_content_link_type_providers_1_1_create_document_action_provider" ]
];