var _create_event_action_parameters_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Calendar.Models.CreateEventActionParameters", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_calendar_1_1_models_1_1_create_event_action_parameters.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_calendar_1_1_models_1_1_create_event_action_parameters" ]
];