var _create_document_element_8cs =
[
    [ "EleWise.ELMA.Documents.BPMN.Diagrams.Elements.CreateDocumentElement", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_create_document_element.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_create_document_element" ],
    [ "EleWise.ELMA.Documents.BPMN.Diagrams.Elements.CreateDocumentElement.ToolboxItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_create_document_element_1_1_toolbox_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_create_document_element_1_1_toolbox_item" ]
];