var _crm_module_settings_currency_item_provider_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.CrmModuleSettingsCurrencyItemProvider", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_crm_module_settings_currency_item_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_crm_module_settings_currency_item_provider" ]
];