var _currency_dynamics_settings_model_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Models.ExchangeRates.CurrencyDynamicsSettingsModel", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_models_1_1_exchange_rates_1_1_currency_dynamics_settings_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_models_1_1_exchange_rates_1_1_currency_dynamics_settings_model" ]
];