var _custom_markup_portlet_personalization_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Content.Portlets.CustomMarkupPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_portlets_1_1_custom_markup_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_portlets_1_1_custom_markup_portlet_personalization" ]
];