var _default_feed_comment_action_name_extension_8cs =
[
    [ "EleWise.ELMA.Messages.Components.Feed.DefaultFeedCommentActionNameExtension", "class_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_components_1_1_feed_1_1_default_feed_comment_action_name_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_components_1_1_feed_1_1_default_feed_comment_action_name_extension" ]
];