var _default_complete_type_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Components.ApprovementCompleteType.DefaultCompleteType", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_components_1_1_approvement_complete_type_1_1_default_complete_type.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_components_1_1_approvement_complete_type_1_1_default_complete_type" ]
];