var _deny_reassign_executor_user_task_element_extentions_8cs =
[
    [ "EleWise.ELMA.Workflow.ExtensionPoints.DenyReassignExecutorUserTaskElementExtentions", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extension_points_1_1_deny_reassign_executor_user_task_element_extentions.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extension_points_1_1_deny_reassign_executor_user_task_element_extentions" ]
];