var _designer_inform_elements_context_provider_8cs =
[
    [ "EleWise.ELMA.KPI.Analysis.DesignerInformElementsContextProvider", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_analysis_1_1_designer_inform_elements_context_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_analysis_1_1_designer_inform_elements_context_provider" ]
];