var _diagnostics_settings_module_controller_8cs =
[
    [ "EleWise.ELMA.Web.Mvc.Services.DiagnosticsSettingsModuleController", "class_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_services_1_1_diagnostics_settings_module_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_services_1_1_diagnostics_settings_module_controller" ]
];