var _disagreement_filter_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Contracts.Extensions.DisagreementFilterExtension", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_extensions_1_1_disagreement_filter_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_extensions_1_1_disagreement_filter_extension" ]
];