var _dms_object_default_permissions_skip_resolver_8cs =
[
    [ "EleWise.ELMA.Documents.Deploy.Import.DmsObjectDefaultPermissionsSkipResolver", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_deploy_1_1_import_1_1_dms_object_default_permissions_skip_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_deploy_1_1_import_1_1_dms_object_default_permissions_skip_resolver" ]
];