var _document_storage_settings_block_controller_base_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Extensions.DocumentStorageSettingsBlockControllerBase< TSettings, TSettingsModule >", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_extensions_1_1_document_storage_settings_block_controller_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_extensions_1_1_document_storage_settings_block_controller_base" ]
];