var _document_task_controller_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Controllers.DocumentTaskController", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_controllers_1_1_document_task_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_controllers_1_1_document_task_controller" ]
];