var _document_acquaintance_task_feed_object_group_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Components.Feed.DocumentAcquaintanceTaskFeedObjectGroupExtension", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_feed_1_1_document_acquaintance_task_feed_object_group_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_feed_1_1_document_acquaintance_task_feed_object_group_extension" ]
];