var _document_approvement_task_package_8cs =
[
    [ "EleWise.ELMA.Documents.API.Models.DocumentApprovementTaskPackage", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_a_p_i_1_1_models_1_1_document_approvement_task_package.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_a_p_i_1_1_models_1_1_document_approvement_task_package" ]
];