var _document_version_download_action_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.DocumentVersionDownloadAction", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_version_download_action.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_version_download_action" ]
];