var _document_versions_grid_view_item_builder_0l1_8cs =
[
    [ "EleWise.ELMA.Documents.Extensions.DocumentVersionsGridViewItemBuilder< TM >", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_document_versions_grid_view_item_builder.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_document_versions_grid_view_item_builder" ]
];