var _documents_view_item_toolbox_group_8cs =
[
    [ "EleWise.ELMA.Documents.ViewItems.DocumentsViewItemToolboxGroup", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_documents_view_item_toolbox_group.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_documents_view_item_toolbox_group" ]
];