var _document_acquaintance_task_actions_8cs =
[
    [ "EleWise.ELMA.Documents.Models.Tasks.DocumentAcquaintanceTaskActions", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_tasks_1_1_document_acquaintance_task_actions.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_tasks_1_1_document_acquaintance_task_actions" ]
];