var _document_filter_properties_zone_panel_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.Filter.DocumentFilterPropertiesZoneTab", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_filter_1_1_document_filter_properties_zone_tab.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_filter_1_1_document_filter_properties_zone_tab" ],
    [ "EleWise.ELMA.Documents.Web.Components.Filter.DocumentFilterPropertiesZonePanel", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_filter_1_1_document_filter_properties_zone_panel.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_filter_1_1_document_filter_properties_zone_panel" ]
];