var _documents_system_role_permissions_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.DocumentsSystemRolePermissions", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_documents_system_role_permissions.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_documents_system_role_permissions" ]
];