var _document_object_view_item_provider_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.DocumentObjectViewItemProvider", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_object_view_item_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_object_view_item_provider" ]
];