var _document_resolution_status_view_item_8cs =
[
    [ "EleWise.ELMA.Documents.ViewItems.DocumentResolutionStatusViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_document_resolution_status_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_document_resolution_status_view_item" ]
];