var _document_task_notification_flow_objects_8cs =
[
    [ "EleWise.ELMA.Documents.Components.DocumentTaskNotificationFlowObjects", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_document_task_notification_flow_objects.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_document_task_notification_flow_objects" ]
];