var _document_versions_tab_view_item_renderer_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.DocumentVersionsTabViewItemRenderer", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_versions_tab_view_item_renderer.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_versions_tab_view_item_renderer" ]
];