var _document_task_property_resolver_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Components.DocumentTaskPropertyResolver", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_document_task_property_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_document_task_property_resolver" ]
];