var _document_send_status_cache_manager_8cs =
[
    [ "EleWise.ELMA.Documents.Managers.DocumentSendStatusCacheManager", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_managers_1_1_document_send_status_cache_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_managers_1_1_document_send_status_cache_manager" ]
];