var _document_template_import_save_actions_8cs =
[
    [ "EleWise.ELMA.Documents.Deploy.Import.DocumentTemplateImportSaveActions", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_deploy_1_1_import_1_1_document_template_import_save_actions.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_deploy_1_1_import_1_1_document_template_import_save_actions" ]
];