var _document_task_solve_task_view_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Integration.Portlets.DocumentTaskSolveTaskView", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_portlets_1_1_document_task_solve_task_view.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_portlets_1_1_document_task_solve_task_view" ]
];