var _document_templates_list_type_settings_8cs =
[
    [ "EleWise.ELMA.Documents.Types.DocumentTemplatesListTypeSettings", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_document_templates_list_type_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_document_templates_list_type_settings" ]
];