var _document_task_group_base_actions_8cs =
[
    [ "EleWise.ELMA.Documents.Models.BPMN.DocumentTaskGroupBaseActions", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_b_p_m_n_1_1_document_task_group_base_actions.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_b_p_m_n_1_1_document_task_group_base_actions" ]
];