var _document_permission_settings_view_item_8cs =
[
    [ "EleWise.ELMA.Documents.ViewItems.DocumentPermissionSettingsViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_document_permission_settings_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_document_permission_settings_view_item" ]
];