var _document_channel_message_discussion_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Components.DocumentChannelMessageDiscussionExtension", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_document_channel_message_discussion_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_document_channel_message_discussion_extension" ]
];