var _document_storage_preview_settings_resolver_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.DocumentStoragePreviewSettingsResolver", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_storage_preview_settings_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_storage_preview_settings_resolver" ]
];