var _document_default_selected_columns_provider_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Components.DocumentDefaultSelectedColumnsProvider", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_default_selected_columns_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_components_1_1_document_default_selected_columns_provider" ]
];