var _documents_full_text_search_settings_8cs =
[
    [ "EleWise.ELMA.Documents.FullTextSearch.DocumentsFullTextSearchSettings", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_full_text_search_1_1_documents_full_text_search_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_full_text_search_1_1_documents_full_text_search_settings" ]
];