var _dynamic_module_virtual_path_provider_8cs =
[
    [ "Orchard.FileSystems.Dependencies.DynamicModuleVirtualPathProvider", "class_orchard_1_1_file_systems_1_1_dependencies_1_1_dynamic_module_virtual_path_provider.html", "class_orchard_1_1_file_systems_1_1_dependencies_1_1_dynamic_module_virtual_path_provider" ]
];