var _edit_project_task_action_default_form_8cs =
[
    [ "EleWise.ELMA.Projects.Components.EditProjectTaskActionDefaultForm", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_edit_project_task_action_default_form.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_edit_project_task_action_default_form" ]
];