var _edit_global_settings_event_args_8cs =
[
    [ "EleWise.ELMA.Runtime.Settings.Events.EditGlobalSettingsEventArgs", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_settings_1_1_events_1_1_edit_global_settings_event_args.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_settings_1_1_events_1_1_edit_global_settings_event_args" ]
];