var _ele_wise_8_e_l_m_a_8_integration1_c_8_web_2_components_2_catalogs_view_settings_8cs =
[
    [ "EleWise.ELMA.Integration1C.Web.Components.CatalogsViewSettings", "class_ele_wise_1_1_e_l_m_a_1_1_integration1_c_1_1_web_1_1_components_1_1_catalogs_view_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration1_c_1_1_web_1_1_components_1_1_catalogs_view_settings" ]
];