var _ele_wise_8_e_l_m_a_8i_pad_2_ele_wise_2_e_l_m_a_2i_pad_2_security_2i_pad_licensed_module_access_group_8cs =
[
    [ "EleWise.ELMA.iPad.Security.iPadLicensedModuleAccessGroup", "class_ele_wise_1_1_e_l_m_a_1_1i_pad_1_1_security_1_1i_pad_licensed_module_access_group.html", "class_ele_wise_1_1_e_l_m_a_1_1i_pad_1_1_security_1_1i_pad_licensed_module_access_group" ]
];