var _ele_wise_8_e_l_m_a_8_packaging_2_logging_2_i_logger_enabled_component_8cs =
[
    [ "EleWise.ELMA.Packaging.Logging.ILoggerEnabledComponent", "interface_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_logging_1_1_i_logger_enabled_component.html", "interface_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_logging_1_1_i_logger_enabled_component" ]
];