var _ele_wise_8_e_l_m_a_8_b_p_m_8_web_8_tasks_2_components_2_security_extension_zone_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Components.SecurityExtensionZone", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_security_extension_zone.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_security_extension_zone" ]
];