var _ele_wise_8_e_l_m_a_8_integration_oktell_2_components_2_telephony_settings_event_handler_8cs =
[
    [ "EleWise.ELMA.IntegrationOktell.Components.TelephonySettingsEventHandler", "class_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_components_1_1_telephony_settings_event_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_components_1_1_telephony_settings_event_handler" ]
];