var _ele_wise_8_e_l_m_a_8_b_p_m_8_web_8_common_2_extensions_2_filter_menu_provider_extension_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.Extensions.FilterMenuProviderExtension", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extensions_1_1_filter_menu_provider_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extensions_1_1_filter_menu_provider_extension" ]
];