var _ele_wise_8_e_l_m_a_8_projects_8_web_2_controllers_2_admin_controller_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Controllers.AdminController", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_controllers_1_1_admin_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_controllers_1_1_admin_controller" ]
];