var _ele_wise_8_e_l_m_a_8_documents_8_contracts_8_web_2_controllers_2_settings_controller_8cs =
[
    [ "EleWise.ELMA.Documents.Contracts.Web.Controllers.SettingsController", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_web_1_1_controllers_1_1_settings_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_web_1_1_controllers_1_1_settings_controller" ]
];