var _ele_wise_8_e_l_m_a_8_b_p_m_8_web_8_security_2_controllers_2_user_controller_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.Controllers.UserController", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_controllers_1_1_user_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_controllers_1_1_user_controller" ]
];