var _ele_wise_8_e_l_m_a_8_c_r_m_8_workflow_8_processes_8_db_8_postgre_s_q_l_2_crm_expert_db_structure_8cs =
[
    [ "EleWise.ELMA.CRM.Workflow.Processes.Db.PostgreSQL.CrmExpertDbStructure", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_db_1_1_postgre_s_q_l_1_1_crm_expert_db_structure.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_db_1_1_postgre_s_q_l_1_1_crm_expert_db_structure" ]
];