var _ele_wise_8_e_l_m_a_8_k_p_i_2_ele_wise_2_e_l_m_a_2_k_p_i_2_a_p_i_2_models_2_deleted_ids_package_8cs =
[
    [ "EleWise.ELMA.KPI.API.Models.DeletedIdsPackage", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_a_p_i_1_1_models_1_1_deleted_ids_package.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_a_p_i_1_1_models_1_1_deleted_ids_package" ]
];