var _ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_notifications_2_impl_2_notification_manager_8cs =
[
    [ "EleWise.ELMA.Notifications.Impl.NotificationManager", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_notification_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_notification_manager" ]
];