var _ele_wise_8_e_l_m_a_8i_pad_8_k_p_i_2_ele_wise_2_e_l_m_a_2i_pad_2_k_p_i_2_security_2_permissions_provider_8cs =
[
    [ "EleWise.ELMA.iPad.KPI.Security.PermissionsProvider", "class_ele_wise_1_1_e_l_m_a_1_1i_pad_1_1_k_p_i_1_1_security_1_1_permissions_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1i_pad_1_1_k_p_i_1_1_security_1_1_permissions_provider" ]
];