var _ele_wise_8_e_l_m_a_8_documents_2_documents_2_models_2_dms_object_permissions_2_custom_code_template_8cs =
[
    [ "EleWise.ELMA.Documents.Models.DmsObjectPermission", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_dms_object_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_dms_object_permission" ]
];