var _ele_wise_8_e_l_m_a_8_content_2_models_2_portal_object_permissions_2_custom_code_template_8cs =
[
    [ "EleWise.ELMA.Content.Models.PortalObjectPermission", "class_ele_wise_1_1_e_l_m_a_1_1_content_1_1_models_1_1_portal_object_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_content_1_1_models_1_1_portal_object_permission" ]
];