var _ele_wise_8_e_l_m_a_8_k_p_i_8_workflow_2_listeners_2_associated_process_listener_8cs =
[
    [ "EleWise.ELMA.KPI.Workflow.Listeners.AssociatedProcessListener", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_listeners_1_1_associated_process_listener.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_listeners_1_1_associated_process_listener" ]
];