var _ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_authorization_service_event_handler_8cs =
[
    [ "Orchard.Security.IAuthorizationServiceEventHandler", "interface_orchard_1_1_security_1_1_i_authorization_service_event_handler.html", "interface_orchard_1_1_security_1_1_i_authorization_service_event_handler" ]
];