var _ele_wise_8_e_l_m_a_8_c_r_m_2_c_r_m_2_components_2_metadata_forms_transformations_8cs =
[
    [ "EleWise.ELMA.CRM.Components.MetadataFormsTransformations", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_components_1_1_metadata_forms_transformations.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_components_1_1_metadata_forms_transformations" ]
];