var _ele_wise_8_e_l_m_a_8_documents_2_documents_2_models_2_folders_2_filter_document_folder_2_custom_code_template_8cs =
[
    [ "EleWise.ELMA.Documents.Models.Folders.FilterDocumentFolder", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_folders_1_1_filter_document_folder.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_folders_1_1_filter_document_folder" ]
];