var _ele_wise_8_e_l_m_a_8_workflow_2_ele_wise_2_e_l_m_a_2_workflow_2_db_2_db_process_update_handler_8cs =
[
    [ "EleWise.ELMA.Workflow.Db.DbProcessUpdateHandler", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_db_1_1_db_process_update_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_db_1_1_db_process_update_handler" ]
];