var _ele_wise_8_e_l_m_a_8_c_r_m_2_c_r_m_2_models_2_sale_person_permission_2_custom_code_template_8cs =
[
    [ "EleWise.ELMA.CRM.Models.SalePersonPermission", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_models_1_1_sale_person_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_models_1_1_sale_person_permission" ]
];