var _ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_mvc_2_view_engines_2_theme_awareness_2_theme_aware_view_engine_8cs =
[
    [ "Orchard.Mvc.ViewEngines.ThemeAwareness.ThemeAwareViewEngine", "class_orchard_1_1_mvc_1_1_view_engines_1_1_theme_awareness_1_1_theme_aware_view_engine.html", "class_orchard_1_1_mvc_1_1_view_engines_1_1_theme_awareness_1_1_theme_aware_view_engine" ]
];