var _ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_services_2_i_permission_provider_8cs =
[
    [ "EleWise.ELMA.Security.Services.IPermissionProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_services_1_1_i_permission_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_services_1_1_i_permission_provider" ]
];