var _ele_wise_8_e_l_m_a_8_documents_2_documents_2_d_t_o_2_models_2_life_cycle_transition_d_t_o_8cs =
[
    [ "EleWise.ELMA.Documents.DTO.Models.LifeCycleTransitionDTO", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_d_t_o_1_1_models_1_1_life_cycle_transition_d_t_o.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_d_t_o_1_1_models_1_1_life_cycle_transition_d_t_o" ]
];