var _ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_model_2_services_2_i_metadata_service_8cs =
[
    [ "EleWise.ELMA.Model.Services.IMetadataService", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_services_1_1_i_metadata_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_services_1_1_i_metadata_service" ]
];