var _ele_wise_8_e_l_m_a_8_s_d_k_8_u_i_builder_2_s_d_k_2_u_i_builder_2_default_namespaces_8cs =
[
    [ "EleWise.ELMA.SDK.UIBuilder.DefaultNamespaces.Core", "class_ele_wise_1_1_e_l_m_a_1_1_s_d_k_1_1_u_i_builder_1_1_default_namespaces_1_1_core.html", "class_ele_wise_1_1_e_l_m_a_1_1_s_d_k_1_1_u_i_builder_1_1_default_namespaces_1_1_core" ],
    [ "EleWise.ELMA.SDK.UIBuilder.DefaultNamespaces.Scripts", "class_ele_wise_1_1_e_l_m_a_1_1_s_d_k_1_1_u_i_builder_1_1_default_namespaces_1_1_scripts.html", "class_ele_wise_1_1_e_l_m_a_1_1_s_d_k_1_1_u_i_builder_1_1_default_namespaces_1_1_scripts" ]
];