var _ele_wise_8_e_l_m_a_8_integration_asterisk_2_integration_asterisk_2_components_2_telephony_settings_event_handler_8cs =
[
    [ "EleWise.ELMA.IntegrationAsterisk.Components.TelephonySettingsEventHandler", "class_ele_wise_1_1_e_l_m_a_1_1_integration_asterisk_1_1_components_1_1_telephony_settings_event_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_asterisk_1_1_components_1_1_telephony_settings_event_handler" ]
];