var _ele_wise_8_e_l_m_a_8_b_p_m_8_web_8_reports_8_documents_2_report_document_area_registration_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Reports.Documents.ReportDocumentAreaRegistration", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_documents_1_1_report_document_area_registration.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_documents_1_1_report_document_area_registration" ]
];