var _ele_wise_8_e_l_m_a_8_c_r_m_2_c_r_m_2_full_text_search_2_components_2_full_text_search_create_file_preview_item_index_8cs =
[
    [ "EleWise.ELMA.CRM.FullTextSearch.Components.FullTextSearchCreateFilePreviewItemIndex", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_full_text_search_1_1_components_1_1_full_text_search_create_file_preview_item_index.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_full_text_search_1_1_components_1_1_full_text_search_create_file_preview_item_index" ]
];