var _ele_wise_8_e_l_m_a_8_common_2_common_2_extensions_2_filter_portlet_check_permission_extensions_8cs =
[
    [ "EleWise.ELMA.Common.Extensions.FilterPortletCheckPermissionExtensions", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_extensions_1_1_filter_portlet_check_permission_extensions.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_extensions_1_1_filter_portlet_check_permission_extensions" ]
];