var _ele_wise_8_e_l_m_a_8_b_p_m_8_web_8_reports_2_security_2_module_permissions_page_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Reports.Security.ModulePermissionsPageProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_security_1_1_module_permissions_page_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_security_1_1_module_permissions_page_provider" ]
];