var _ele_wise_8_e_l_m_a_8_tasks_2_tasks_2_components_2_create_subtask_action_handler_8cs =
[
    [ "EleWise.ELMA.Tasks.Components.CreateSubtaskActionHandler", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_create_subtask_action_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_create_subtask_action_handler" ]
];