var _elma_store_component_build_settings_8cs =
[
    [ "EleWise.ELMA.Packaging.ElmaStoreManifest.ElmaStoreComponentBuildSettings", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_elma_store_manifest_1_1_elma_store_component_build_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_elma_store_manifest_1_1_elma_store_component_build_settings" ]
];