var _encrypt_document_version_exception_8cs =
[
    [ "EleWise.ELMA.Documents.Exceptions.EncryptDocumentVersionException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_encrypt_document_version_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_encrypt_document_version_exception" ]
];