var _end_work_set_complete_percent_project_task_history_model_8cs =
[
    [ "EleWise.ELMA.Projects.Models.History.EndWorkSetCompletePercentProjectTaskHistoryModel", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_history_1_1_end_work_set_complete_percent_project_task_history_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_history_1_1_end_work_set_complete_percent_project_task_history_model" ]
];