var _entity_model_history_events_filter_base_8cs =
[
    [ "EleWise.ELMA.Events.Audit.EntityModelHistoryEventsFilterBase", "class_ele_wise_1_1_e_l_m_a_1_1_events_1_1_audit_1_1_entity_model_history_events_filter_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_events_1_1_audit_1_1_entity_model_history_events_filter_base" ]
];