var _entity_update_by_workflow_task_event_renderer_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Components.EntityUpdateByWorkflowTaskEventRenderer", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_components_1_1_entity_update_by_workflow_task_event_renderer.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_components_1_1_entity_update_by_workflow_task_event_renderer" ]
];