var _entity_type_descriptor_operations_base_0l1_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.ConditionTable.EntityTypeDescriptorOperationsBase< TEntity >", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_condition_table_1_1_entity_type_descriptor_operations_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_condition_table_1_1_entity_type_descriptor_operations_base" ]
];