var _entity_without_marketing_filter_provider_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.EntityWithoutMarketingFilterProvider", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_entity_without_marketing_filter_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_entity_without_marketing_filter_provider" ]
];