var _entity_sub_type_descriptor_serializer_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Extensions.EntitySubTypeDescriptorSerializer", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_extensions_1_1_entity_sub_type_descriptor_serializer.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_extensions_1_1_entity_sub_type_descriptor_serializer" ]
];