var _entity_base_controller_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.Controllers.EntityBaseController", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_controllers_1_1_entity_base_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_controllers_1_1_entity_base_controller" ],
    [ "EleWise.ELMA.BPM.Web.Common.Controllers.EntityBaseController.GridResult", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_controllers_1_1_entity_base_controller_1_1_grid_result.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_controllers_1_1_entity_base_controller_1_1_grid_result" ]
];