var _entity_action_history_event_service_8cs =
[
    [ "EleWise.ELMA.Events.Audit.Impl.EntityActionHistoryEventService", "class_ele_wise_1_1_e_l_m_a_1_1_events_1_1_audit_1_1_impl_1_1_entity_action_history_event_service.html", "class_ele_wise_1_1_e_l_m_a_1_1_events_1_1_audit_1_1_impl_1_1_entity_action_history_event_service" ]
];