var _entity_type_filter_property_editor_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.EntityTypeFilterPropertyEditor", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_entity_type_filter_property_editor.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_entity_type_filter_property_editor" ]
];