var _exception_flow_background_task_info_8cs =
[
    [ "EleWise.ELMA.Workflow.Diagrams.Activities.Helpers.ExceptionFlowBackgroundTaskInfo", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_helpers_1_1_exception_flow_background_task_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_helpers_1_1_exception_flow_background_task_info" ]
];