var _export_2_workflow_process_export_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.Deploy.Export.WorkflowProcessExportExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_deploy_1_1_export_1_1_workflow_process_export_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_deploy_1_1_export_1_1_workflow_process_export_extension" ]
];