var _external_data_execute_exception_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Db.Exceptions.ExternalDataExecuteException", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_db_1_1_exceptions_1_1_external_data_execute_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_db_1_1_exceptions_1_1_external_data_execute_exception" ]
];