var _external_structure_reader_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Providers.ExternalStructureReader", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_providers_1_1_external_structure_reader.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_providers_1_1_external_structure_reader" ]
];