var _external_calendar_permission_provider_8cs =
[
    [ "EleWise.ELMA.Calendar.Export.Security.ExternalCalendarPermissionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_security_1_1_external_calendar_permission_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_security_1_1_external_calendar_permission_provider" ]
];