var _extension_points_2_i_projects_start_page_portlets_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Web.ExtensionPoints.IProjectsStartPagePortletsProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extension_points_1_1_i_projects_start_page_portlets_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extension_points_1_1_i_projects_start_page_portlets_provider" ]
];