var _filter_properties_zone_view_model_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.Models.FilterPropertiesZoneViewModel", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_models_1_1_filter_properties_zone_view_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_models_1_1_filter_properties_zone_view_model" ]
];