var _filter_project_menu_provider_extension_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Extensions.FilterProjectMenuProviderExtension", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extensions_1_1_filter_project_menu_provider_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extensions_1_1_filter_project_menu_provider_extension" ]
];