var _filter_portlet_task_color_extension_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.FilterPortletTaskColorExtension", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_filter_portlet_task_color_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_filter_portlet_task_color_extension" ]
];