var _file_preview_service_provider_manager_8cs =
[
    [ "EleWise.ELMA.Files.Previews.FilePreviewServiceProviderManager", "class_ele_wise_1_1_e_l_m_a_1_1_files_1_1_previews_1_1_file_preview_service_provider_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_files_1_1_previews_1_1_file_preview_service_provider_manager" ]
];