var _from_me_tasks_portlet_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Portlets.FromMeTasksPortlet", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_portlets_1_1_from_me_tasks_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_portlets_1_1_from_me_tasks_portlet" ],
    [ "EleWise.ELMA.BPM.Web.Tasks.Portlets.FromMeTasksPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_portlets_1_1_from_me_tasks_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_portlets_1_1_from_me_tasks_portlet_personalization" ]
];