var _general_information_channel_group_8cs =
[
    [ "EleWise.ELMA.Messages.Web.Extensions.GeneralInformationChannelGroup", "class_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_web_1_1_extensions_1_1_general_information_channel_group.html", "class_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_web_1_1_extensions_1_1_general_information_channel_group" ]
];