var _get_start_information_localized_completed_event_args_8cs =
[
    [ "EleWise.ELMA.ServerInfoReference.GetStartInformationLocalizedCompletedEventArgs", "class_ele_wise_1_1_e_l_m_a_1_1_server_info_reference_1_1_get_start_information_localized_completed_event_args.html", "class_ele_wise_1_1_e_l_m_a_1_1_server_info_reference_1_1_get_start_information_localized_completed_event_args" ]
];