var _header_buttons_watch_is_available_service_8cs =
[
    [ "EleWise.ELMA.Common.Components.HeaderButtonsServices.HeaderButtonsWatchIsAvailableService", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_components_1_1_header_buttons_services_1_1_header_buttons_watch_is_available_service.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_components_1_1_header_buttons_services_1_1_header_buttons_watch_is_available_service" ]
];