var _http_media_type_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.BackgroundOperations.HttpRequest.HttpMediaType", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_http_request_1_1_http_media_type.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_http_request_1_1_http_media_type" ]
];