var _i_authentication_service_event_handler2_8cs =
[
    [ "EleWise.ELMA.Security.Services.IAuthenticationServiceEventHandler2", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_services_1_1_i_authentication_service_event_handler2.html", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_services_1_1_i_authentication_service_event_handler2" ]
];