var _i_audit_event_permission_checker_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.ExtensionPoints.IAuditEventPermissionChecker", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extension_points_1_1_i_audit_event_permission_checker.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extension_points_1_1_i_audit_event_permission_checker" ]
];