var _i_approvement_list_settings_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Models.Interfaces.IApprovementListSettings", "interface_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_models_1_1_interfaces_1_1_i_approvement_list_settings.html", "interface_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_models_1_1_interfaces_1_1_i_approvement_list_settings" ]
];