var _i_bank_details_in_russia_8cs =
[
    [ "EleWise.ELMA.CRM.Models.BillingInformation.IBankDetailsInRussia", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_models_1_1_billing_information_1_1_i_bank_details_in_russia.html", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_models_1_1_billing_information_1_1_i_bank_details_in_russia" ]
];