var _i_bulk_data_import_command_service_8cs =
[
    [ "EleWise.ELMA.Common.BulkDataImport.Services.IBulkDataImportCommandService", "interface_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_services_1_1_i_bulk_data_import_command_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_services_1_1_i_bulk_data_import_command_service" ]
];