var _i_block_user_action_extension_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.ExtensionPoints.IBlockUserActionExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_i_block_user_action_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_i_block_user_action_extension" ]
];