var _i_budget_version_expense_item_8cs =
[
    [ "EleWise.ELMA.Projects.Models.Budgets.IBudgetVersionExpenseItem", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_budgets_1_1_i_budget_version_expense_item.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_budgets_1_1_i_budget_version_expense_item" ]
];