var _i_business_rule_execution_service_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Services.IBusinessRuleExecutionService", "interface_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_services_1_1_i_business_rule_execution_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_services_1_1_i_business_rule_execution_service" ]
];