var _i_create_subtask_with_project_action_model_8cs =
[
    [ "EleWise.ELMA.Projects.Models.ICreateSubtaskWithProjectActionModel", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_i_create_subtask_with_project_action_model.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_i_create_subtask_with_project_action_model" ]
];