var _i_create_task_group_action_handler_8cs =
[
    [ "EleWise.ELMA.Documents.Extensions.ICreateTaskGroupActionHandler", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_i_create_task_group_action_handler.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_i_create_task_group_action_handler" ]
];