var _i_channel_message_objects_extension_8cs =
[
    [ "EleWise.ELMA.Messages.ExtensionPoints.IChannelMessageObjectsExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_extension_points_1_1_i_channel_message_objects_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_messages_1_1_extension_points_1_1_i_channel_message_objects_extension" ]
];