var _i_channel_message_documents_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Models.Messages.IChannelMessageDocumentsExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_messages_1_1_i_channel_message_documents_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_messages_1_1_i_channel_message_documents_extension" ]
];