var _i_configuration_external_data_service_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Services.IConfigurationExternalDataService", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_services_1_1_i_configuration_external_data_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_services_1_1_i_configuration_external_data_service" ]
];