var _i_calendar_item_excluded_types_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.ICalendarItemExcludedTypes", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_calendar_item_excluded_types.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_calendar_item_excluded_types" ]
];