var _i_create_subtask_action_handler_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.ICreateSubtaskActionHandler", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_create_subtask_action_handler.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_create_subtask_action_handler" ]
];