var _i_common_settings_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.Runtime.Settings.DTO.ICommonSettingsDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_settings_1_1_d_t_o_1_1_i_common_settings_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_settings_1_1_d_t_o_1_1_i_common_settings_d_t_o_manager" ]
];