var _i_create_popup_document_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Extensions.ICreatePopupDocumentExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_extensions_1_1_i_create_popup_document_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_extensions_1_1_i_create_popup_document_extension" ]
];