var _i_create_task_with_projects_extended_model_8cs =
[
    [ "EleWise.ELMA.Projects.Models.ICreateTaskWithProjectsExtendedModel", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_i_create_task_with_projects_extended_model.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_i_create_task_with_projects_extended_model" ]
];