var _i_current_user_panel_action_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.ExtensionPoints.ICurrentUserPanelAction", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_i_current_user_panel_action.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_i_current_user_panel_action" ]
];