var _i_docflow_system_folders_service_8cs =
[
    [ "EleWise.ELMA.Documents.Services.IDocflowSystemFoldersService", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_services_1_1_i_docflow_system_folders_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_services_1_1_i_docflow_system_folders_service" ]
];