var _i_documents_property_resolver_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Extensions.IDocumentsPropertyResolver", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_extensions_1_1_i_documents_property_resolver.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_extensions_1_1_i_documents_property_resolver" ]
];