var _i_document_metadata_profile_updater_service_8cs =
[
    [ "EleWise.ELMA.Documents.Services.IDocumentMetadataProfileUpdaterService", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_services_1_1_i_document_metadata_profile_updater_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_services_1_1_i_document_metadata_profile_updater_service" ]
];