var _i_disagreements_protocol_filter_8cs =
[
    [ "EleWise.ELMA.Documents.Contracts.Models.IDisagreementsProtocolFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_models_1_1_i_disagreements_protocol_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_contracts_1_1_models_1_1_i_disagreements_protocol_filter" ]
];