var _i_document_work_log_object_search_filter_8cs =
[
    [ "EleWise.ELMA.Documents.Extensions.IDocumentWorkLogObjectSearchFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_i_document_work_log_object_search_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_i_document_work_log_object_search_filter" ]
];