var _i_document_action_default_visibility_8cs =
[
    [ "EleWise.ELMA.Documents.Extensions.IDocumentActionDefaultVisibility", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_i_document_action_default_visibility.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extensions_1_1_i_document_action_default_visibility" ]
];