var _i_data_class_metadata_item_header_manager_8cs =
[
    [ "EleWise.ELMA.Model.Metadata.Managers.IDataClassMetadataItemHeaderManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_i_data_class_metadata_item_header_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_i_data_class_metadata_item_header_manager" ]
];