var _i_external_book_configuration_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Configuration.IExternalBookConfiguration", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_configuration_1_1_i_external_book_configuration.html", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_configuration_1_1_i_external_book_configuration" ]
];