var _i_extended_validate_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.IExtendedValidateProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_i_extended_validate_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_i_extended_validate_provider" ]
];