var _i_external_less_source_provider_8cs =
[
    [ "EleWise.ELMA.Web.Mvc.ExtensionPoints.IExternalLessSourceProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_extension_points_1_1_i_external_less_source_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_extension_points_1_1_i_external_less_source_provider" ]
];