var _i_elma_parser_global_value_8cs =
[
    [ "EleWise.ELMA.Templates.GlobalValueTemplateGenerator.IElmaParserGlobalValue", "interface_ele_wise_1_1_e_l_m_a_1_1_templates_1_1_global_value_template_generator_1_1_i_elma_parser_global_value.html", "interface_ele_wise_1_1_e_l_m_a_1_1_templates_1_1_global_value_template_generator_1_1_i_elma_parser_global_value" ]
];