var _i_entity_history_restriction_service_8cs =
[
    [ "EleWise.ELMA.Common.Services.IEntityHistoryRestrictionService", "interface_ele_wise_1_1_e_l_m_a_1_1_common_1_1_services_1_1_i_entity_history_restriction_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_common_1_1_services_1_1_i_entity_history_restriction_service" ]
];