var _i_element_with_notification_8cs =
[
    [ "EleWise.ELMA.Workflow.Diagrams.Elements.IElementWithNotification", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_elements_1_1_i_element_with_notification.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_elements_1_1_i_element_with_notification" ]
];