var _i_entity_permission_configuration_manager_8cs =
[
    [ "EleWise.ELMA.Model.Managers.IEntityPermissionConfigurationManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_permission_configuration_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_permission_configuration_manager" ]
];