var _i_element_with_form_constructor_view_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Elements.IElementWithFormConstructorView", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_i_element_with_form_constructor_view.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_i_element_with_form_constructor_view" ]
];