var _i_executable_aggregation_function_provider_8cs =
[
    [ "EleWise.ELMA.KPI.Managers.Formula.IExecutableAggregationFunctionProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_managers_1_1_formula_1_1_i_executable_aggregation_function_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_managers_1_1_formula_1_1_i_executable_aggregation_function_provider" ]
];