var _i_excel_export_permission_handler_8cs =
[
    [ "EleWise.ELMA.SDK.Web.ExtensionPoints.IExcelExportPermissionHandler", "interface_ele_wise_1_1_e_l_m_a_1_1_s_d_k_1_1_web_1_1_extension_points_1_1_i_excel_export_permission_handler.html", "interface_ele_wise_1_1_e_l_m_a_1_1_s_d_k_1_1_web_1_1_extension_points_1_1_i_excel_export_permission_handler" ]
];