var _i_entity_action_event_mapping_8cs =
[
    [ "EleWise.ELMA.History.ExtensionPoints.IEntityActionEventMapping", "interface_ele_wise_1_1_e_l_m_a_1_1_history_1_1_extension_points_1_1_i_entity_action_event_mapping.html", "interface_ele_wise_1_1_e_l_m_a_1_1_history_1_1_extension_points_1_1_i_entity_action_event_mapping" ]
];