var _i_external_provider_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Providers.IExternalProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_providers_1_1_i_external_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_providers_1_1_i_external_provider" ]
];