var _i_element_with_view_transformation_8cs =
[
    [ "EleWise.ELMA.Workflow.ExtensionPoints.IElementWithViewTransformation", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extension_points_1_1_i_element_with_view_transformation.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extension_points_1_1_i_element_with_view_transformation" ]
];