var _i_full_text_search_provider_settings_8cs =
[
    [ "EleWise.ELMA.FullTextSearch.Model.IFullTextSearchProviderSettings", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_model_1_1_i_full_text_search_provider_settings.html", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_model_1_1_i_full_text_search_provider_settings" ]
];