var _i_full_text_search_fields_mappings_extension_8cs =
[
    [ "EleWise.ELMA.FullTextSearch.ExtensionPoints.IFullTextSearchFieldsMappingsExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_extension_points_1_1_i_full_text_search_fields_mappings_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_extension_points_1_1_i_full_text_search_fields_mappings_extension" ]
];