var _i_filter_portlet_filter_modifier_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.ExtensionPoints.IFilterPortletFilterModifier", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extension_points_1_1_i_filter_portlet_filter_modifier.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extension_points_1_1_i_filter_portlet_filter_modifier" ]
];