var _i_form_metadata_item_header_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.UI.DTO.Managers.IFormMetadataItemHeaderDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_u_i_1_1_d_t_o_1_1_managers_1_1_i_form_metadata_item_header_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_u_i_1_1_d_t_o_1_1_managers_1_1_i_form_metadata_item_header_d_t_o_manager" ]
];