var _i_function_metadata_service_8cs =
[
    [ "EleWise.ELMA.UIBuilder.MetadataEdit.Services.Abstraction.IFunctionMetadataService", "interface_ele_wise_1_1_e_l_m_a_1_1_u_i_builder_1_1_metadata_edit_1_1_services_1_1_abstraction_1_1_i_function_metadata_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_u_i_builder_1_1_metadata_edit_1_1_services_1_1_abstraction_1_1_i_function_metadata_service" ]
];