var _i_filter_workflow_instance_criteria_builder_8cs =
[
    [ "EleWise.ELMA.Workflow.Extensions.IFilterWorkflowInstanceCriteriaBuilder", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_filter_workflow_instance_criteria_builder.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_filter_workflow_instance_criteria_builder" ]
];