var _i_function_metadata_item_header_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.Model.Metadata.DTO.Managers.IFunctionMetadataItemHeaderDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_d_t_o_1_1_managers_1_1_i_function_metadata_item_header_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_d_t_o_1_1_managers_1_1_i_function_metadata_item_header_d_t_o_manager" ]
];