var _i_full_text_property_mapping_descriptor_8cs =
[
    [ "EleWise.ELMA.FullTextSearch.Descriptors.IFullTextPropertyMappingDescriptor", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_descriptors_1_1_i_full_text_property_mapping_descriptor.html", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_descriptors_1_1_i_full_text_property_mapping_descriptor" ]
];