var _i_filter_favorite_menu_extension_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Content.ExtensionPoints.IFilterFavoriteMenuExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_extension_points_1_1_i_filter_favorite_menu_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_extension_points_1_1_i_filter_favorite_menu_extension" ]
];