var _i_field_storage_provider_selector_8cs =
[
    [ "Orchard.ContentManagement.FieldStorage.IFieldStorageProviderSelector", "interface_orchard_1_1_content_management_1_1_field_storage_1_1_i_field_storage_provider_selector.html", "interface_orchard_1_1_content_management_1_1_field_storage_1_1_i_field_storage_provider_selector" ]
];