var _i_full_text_property_descriptor_8cs =
[
    [ "EleWise.ELMA.FullTextSearch.Descriptors.IFullTextPropertyDescriptor", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_descriptors_1_1_i_full_text_property_descriptor.html", "interface_ele_wise_1_1_e_l_m_a_1_1_full_text_search_1_1_descriptors_1_1_i_full_text_property_descriptor" ]
];