var _i_filter_menu_provider_extension_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Common.Extensions.IFilterMenuProviderExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extensions_1_1_i_filter_menu_provider_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_extensions_1_1_i_filter_menu_provider_extension" ]
];