var _i_gate_integration_provider_8cs =
[
    [ "EleWise.ELMA.Messaging.SMS.Extensions.IGateIntegrationProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_extensions_1_1_i_gate_integration_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_extensions_1_1_i_gate_integration_provider" ]
];