var _i_history_identifier_extension_point_8cs =
[
    [ "EleWise.ELMA.Common.Services.IHistoryIdentifierExtensionPoint", "interface_ele_wise_1_1_e_l_m_a_1_1_common_1_1_services_1_1_i_history_identifier_extension_point.html", "interface_ele_wise_1_1_e_l_m_a_1_1_common_1_1_services_1_1_i_history_identifier_extension_point" ]
];