var _i_instance_permission_type_role_service_8cs =
[
    [ "EleWise.ELMA.Security.IInstancePermissionTypeRoleService", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_i_instance_permission_type_role_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_i_instance_permission_type_role_service" ]
];