var _i_login_digital_signature_event_handler_8cs =
[
    [ "EleWise.ELMA.Security.Events.ILoginDigitalSignatureEventHandler", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_events_1_1_i_login_digital_signature_event_handler.html", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_events_1_1_i_login_digital_signature_event_handler" ]
];