var _i_life_cycle_stage_d_t_o_manager_ext_8cs =
[
    [ "EleWise.ELMA.Projects.DTO.Managers.ILifeCycleStageDTOManagerExt", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_d_t_o_1_1_managers_1_1_i_life_cycle_stage_d_t_o_manager_ext.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_d_t_o_1_1_managers_1_1_i_life_cycle_stage_d_t_o_manager_ext" ]
];