var _i_life_cycle_status_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.Documents.DTO.Managers.ILifeCycleStatusDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_d_t_o_1_1_managers_1_1_i_life_cycle_status_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_d_t_o_1_1_managers_1_1_i_life_cycle_status_d_t_o_manager" ]
];