var _i_message_related_element_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Elements.Tasks.IMessageRelatedElement", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_i_message_related_element.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_i_message_related_element" ]
];