var _i_module_access_permission_provider_8cs =
[
    [ "EleWise.ELMA.Security.Services.IModuleAccessPermissionProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_services_1_1_i_module_access_permission_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_security_1_1_services_1_1_i_module_access_permission_provider" ]
];