var _i_module_settings_reports_page_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Reports.Extensions.IModuleSettingsReportsPageProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_extensions_1_1_i_module_settings_reports_page_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_extensions_1_1_i_module_settings_reports_page_provider" ]
];