var _i_overdue_task_extension_point_8cs =
[
    [ "EleWise.ELMA.Projects.ExtensionPoints.IOverdueTaskExtensionPoint", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_extension_points_1_1_i_overdue_task_extension_point.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_extension_points_1_1_i_overdue_task_extension_point" ]
];