var _i_oktell_user_settings_model_8cs =
[
    [ "EleWise.ELMA.IntegrationOktell.Model.IOktellUserSettingsModel", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_model_1_1_i_oktell_user_settings_model.html", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_model_1_1_i_oktell_user_settings_model" ]
];