var _i_overtime_work_log_with_drafts_extension_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.IOvertimeWorkLogWithDraftsExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_overtime_work_log_with_drafts_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_overtime_work_log_with_drafts_extension" ]
];