var _i_process_monitor_web_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.ExtensionPoints.IProcessMonitorWebExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_extension_points_1_1_i_process_monitor_web_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_extension_points_1_1_i_process_monitor_web_extension" ]
];