var _i_placement_file_parser_8cs =
[
    [ "Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.IPlacementFileParser", "interface_orchard_1_1_display_management_1_1_descriptors_1_1_shape_placement_strategy_1_1_i_placement_file_parser.html", "interface_orchard_1_1_display_management_1_1_descriptors_1_1_shape_placement_strategy_1_1_i_placement_file_parser" ]
];