var _i_project_task_state_re_calculate_extension_8cs =
[
    [ "EleWise.ELMA.Projects.ExtensionPoints.IProjectTaskStateReCalculateExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_extension_points_1_1_i_project_task_state_re_calculate_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_extension_points_1_1_i_project_task_state_re_calculate_extension" ]
];