var _i_performance_approval_task_ext_8cs =
[
    [ "EleWise.ELMA.KPI.Workflow.Models.IPerformanceApprovalTaskExt", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_models_1_1_i_performance_approval_task_ext.html", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_models_1_1_i_performance_approval_task_ext" ]
];