var _i_project_plan_simple_resolve_conflict_8cs =
[
    [ "EleWise.ELMA.Projects.Web.ExtensionPoints.IProjectPlanSimpleResolveConflict", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extension_points_1_1_i_project_plan_simple_resolve_conflict.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extension_points_1_1_i_project_plan_simple_resolve_conflict" ]
];