var _i_process_regulation_settings_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.Workflow.DTO.Managers.IProcessRegulationSettingsDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_d_t_o_1_1_managers_1_1_i_process_regulation_settings_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_d_t_o_1_1_managers_1_1_i_process_regulation_settings_d_t_o_manager" ]
];