var _i_property_view_item_adjustment_8cs =
[
    [ "EleWise.ELMA.Web.Mvc.ExtensionPoints.IPropertyViewItemAdjustment", "interface_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_extension_points_1_1_i_property_view_item_adjustment.html", "interface_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_extension_points_1_1_i_property_view_item_adjustment" ]
];