var _i_project_workflow_instance_start_filter_8cs =
[
    [ "EleWise.ELMA.Projects.Models.IProjectWorkflowInstanceStartFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_i_project_workflow_instance_start_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_i_project_workflow_instance_start_filter" ]
];