var _i_project_plan_adapter_extension_8cs =
[
    [ "EleWise.ELMA.Projects.ExtensionPoints.IProjectPlanAdapterExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_extension_points_1_1_i_project_plan_adapter_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_extension_points_1_1_i_project_plan_adapter_extension" ]
];