var _i_project_portlet_page_update_service_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Services.IProjectPortletPageUpdateService", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_services_1_1_i_project_portlet_page_update_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_services_1_1_i_project_portlet_page_update_service" ]
];