var _i_process_metric_context_menu_8cs =
[
    [ "EleWise.ELMA.Workflow.ProcessMetricExtensions.IProcessMetricContextMenu", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_context_menu.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_context_menu" ]
];