var _i_qualified_type_resolver_extension_8cs =
[
    [ "EleWise.ELMA.Model.Metadata.ExtensionPoints.IQualifiedTypeResolverExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_extension_points_1_1_i_qualified_type_resolver_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_extension_points_1_1_i_qualified_type_resolver_extension" ]
];