var _i_registration_document_history_service_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Services.IRegistrationDocumentHistoryService", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_services_1_1_i_registration_document_history_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_services_1_1_i_registration_document_history_service" ]
];