var _i_report_external_data_source_processor_creator_8cs =
[
    [ "EleWise.ELMA.Reports.Extensions.IReportExternalDataSourceProcessorCreator", "interface_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_extensions_1_1_i_report_external_data_source_processor_creator.html", "interface_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_extensions_1_1_i_report_external_data_source_processor_creator" ]
];