var _i_render_in_workflow_instance_history_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.History.IRenderInWorkflowInstanceHistory", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_history_1_1_i_render_in_workflow_instance_history.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_history_1_1_i_render_in_workflow_instance_history" ]
];