var _i_registration_place_filter_8cs =
[
    [ "EleWise.ELMA.Documents.Models.Nomenclature.IRegistrationPlaceFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_nomenclature_1_1_i_registration_place_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_models_1_1_nomenclature_1_1_i_registration_place_filter" ]
];