var _i_solve_task_under_control_management_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.ISolveTaskUnderControlManagement", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_solve_task_under_control_management.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_solve_task_under_control_management" ]
];