var _i_status_workflow_process_terminate_action_8cs =
[
    [ "EleWise.ELMA.Workflow.Extensions.IStatusWorkflowProcessTerminateAction", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_status_workflow_process_terminate_action.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_status_workflow_process_terminate_action" ]
];