var _i_shell_descriptor_manager_event_handler_8cs =
[
    [ "Orchard.Environment.Descriptor.IShellDescriptorManagerEventHandler", "interface_orchard_1_1_environment_1_1_descriptor_1_1_i_shell_descriptor_manager_event_handler.html", "interface_orchard_1_1_environment_1_1_descriptor_1_1_i_shell_descriptor_manager_event_handler" ]
];