var _i_shape_template_view_engine_8cs =
[
    [ "Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.IShapeTemplateViewEngine", "interface_orchard_1_1_display_management_1_1_descriptors_1_1_shape_template_strategy_1_1_i_shape_template_view_engine.html", "interface_orchard_1_1_display_management_1_1_descriptors_1_1_shape_template_strategy_1_1_i_shape_template_view_engine" ]
];