var _i_telephony_settings_event_handler_8cs =
[
    [ "EleWise.ELMA.CRM.Telephony.Extensions.ITelephonySettingsEventHandler", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_extensions_1_1_i_telephony_settings_event_handler.html", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_extensions_1_1_i_telephony_settings_event_handler" ]
];