var _i_type_descriptor_operations_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.ConditionTable.ITypeDescriptorOperations", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_condition_table_1_1_i_type_descriptor_operations.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_condition_table_1_1_i_type_descriptor_operations" ]
];