var _i_type_descriptor_provider_8cs =
[
    [ "EleWise.ELMA.DevServer.TypeDescriptors.ITypeDescriptorProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_dev_server_1_1_type_descriptors_1_1_i_type_descriptor_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_dev_server_1_1_type_descriptors_1_1_i_type_descriptor_provider" ]
];