var _i_toolbox_element_group_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Toolbox.IToolboxElementGroup", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_toolbox_1_1_i_toolbox_element_group.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_toolbox_1_1_i_toolbox_element_group" ]
];