var _i_telephony_user_settings_model_8cs =
[
    [ "EleWise.ELMA.CRM.Telephony.Models.ITelephonyUserSettingsModel", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_models_1_1_i_telephony_user_settings_model.html", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_models_1_1_i_telephony_user_settings_model" ]
];