var _i_transformation_provider_base_8cs =
[
    [ "EleWise.ELMA.Runtime.Db.Migrator.Framework.ITransformationProviderBase", "interface_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_db_1_1_migrator_1_1_framework_1_1_i_transformation_provider_base.html", "interface_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_db_1_1_migrator_1_1_framework_1_1_i_transformation_provider_base" ]
];