var _i_workflow_instance_terminate_action_8cs =
[
    [ "EleWise.ELMA.Workflow.Extensions.IWorkflowInstanceTerminateAction", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_workflow_instance_terminate_action.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_workflow_instance_terminate_action" ]
];