var _i_work_log_history_object_extension_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.IWorkLogHistoryObjectExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_work_log_history_object_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_i_work_log_history_object_extension" ]
];