var _i_workflow_task_work_log_object_search_filter_8cs =
[
    [ "EleWise.ELMA.Workflow.Extensions.IWorkflowTaskWorkLogObjectSearchFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_workflow_task_work_log_object_search_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_workflow_task_work_log_object_search_filter" ]
];