var _i_worflow_instance_setup_filter_8cs =
[
    [ "EleWise.ELMA.Workflow.Extensions.IWorflowInstanceSetupFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_worflow_instance_setup_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_i_worflow_instance_setup_filter" ]
];