var _i_workflow_public_service_task_form_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.ExtensionPoints.IWorkflowPublicServiceTaskFormExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extension_points_1_1_i_workflow_public_service_task_form_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extension_points_1_1_i_workflow_public_service_task_form_extension" ]
];