var _i_workflow_instance_migration_item_filter_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.IWorkflowInstanceMigrationItemFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_i_workflow_instance_migration_item_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_i_workflow_instance_migration_item_filter" ]
];