var _i_web_diagrammer_element_shape_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Shapes.IWebDiagrammerElementShape", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_i_web_diagrammer_element_shape.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_i_web_diagrammer_element_shape" ]
];