var _i_workflow_integration_bookmark_filter_8cs =
[
    [ "EleWise.ELMA.IntegrationModules.Workflow.Models.IWorkflowIntegrationBookmarkFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_workflow_1_1_models_1_1_i_workflow_integration_bookmark_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_workflow_1_1_models_1_1_i_workflow_integration_bookmark_filter" ]
];