var _improvement_process_settings_manager_8cs =
[
    [ "EleWise.ELMA.Workflow.Managers.ImprovementProcessSettingsManager", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_managers_1_1_improvement_process_settings_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_managers_1_1_improvement_process_settings_manager" ]
];