var _improvement_filter_property_visibility_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Components.ImprovementFilterPropertyVisibility", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_improvement_filter_property_visibility.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_improvement_filter_property_visibility" ]
];