var _import_info_8cs =
[
    [ "EleWise.ELMA.CRM.Import.Web.Components.ContractorLegalImportInfo", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_import_1_1_web_1_1_components_1_1_contractor_legal_import_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_import_1_1_web_1_1_components_1_1_contractor_legal_import_info" ],
    [ "EleWise.ELMA.CRM.Import.Web.Components.ContractorIndividualImportInfo", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_import_1_1_web_1_1_components_1_1_contractor_individual_import_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_import_1_1_web_1_1_components_1_1_contractor_individual_import_info" ],
    [ "EleWise.ELMA.CRM.Import.Web.Components.LeadImportInfo", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_import_1_1_web_1_1_components_1_1_lead_import_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_import_1_1_web_1_1_components_1_1_lead_import_info" ]
];