var _indicator_global_permissions_delegate_8cs =
[
    [ "EleWise.ELMA.KPI.Security.IndicatorGlobalPermissionsDelegate", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_security_1_1_indicator_global_permissions_delegate.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_security_1_1_indicator_global_permissions_delegate" ]
];