var _indicator_o_l_a_p_settings_type_descriptor_8cs =
[
    [ "EleWise.ELMA.KPI.Models.IndicatorOlapSettings.IndicatorOLAPSettingsTypeDescriptor", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_indicator_olap_settings_1_1_indicator_o_l_a_p_settings_type_descriptor.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_indicator_olap_settings_1_1_indicator_o_l_a_p_settings_type_descriptor" ]
];