var _info_channel_role_type_selector_project_role_items_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.InfoChannelRoleTypeSelectorProjectRoleItems", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_info_channel_role_type_selector_project_role_items.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_info_channel_role_type_selector_project_role_items" ]
];