var _instance_settings_permission_manager_behavior_8cs =
[
    [ "EleWise.ELMA.Security.InstanceSettingsPermissionManagerBehavior", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_instance_settings_permission_manager_behavior.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_instance_settings_permission_manager_behavior" ]
];