var _instance_settings_registration_place_permission_8cs =
[
    [ "EleWise.ELMA.Documents.Security.InstanceSettingsRegistrationPlacePermission", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_instance_settings_registration_place_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_instance_settings_registration_place_permission" ]
];