var _integration_activity_view_model_8cs =
[
    [ "EleWise.ELMA.IntegrationModules.Web.Models.IntegrationActivityViewModel", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models_1_1_integration_activity_view_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models_1_1_integration_activity_view_model" ]
];