var _json_serialization_ignore_attribute_8cs =
[
    [ "EleWise.ELMA.Model.Types.Settings.JsonSerializationIgnoreAttribute", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_types_1_1_settings_1_1_json_serialization_ignore_attribute.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_types_1_1_settings_1_1_json_serialization_ignore_attribute" ]
];