var _kpi_performance_matrix_status_package_8cs =
[
    [ "EleWise.ELMA.KPI.API.Models.KpiPerformanceMatrixStatusPackage", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_a_p_i_1_1_models_1_1_kpi_performance_matrix_status_package.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_a_p_i_1_1_models_1_1_kpi_performance_matrix_status_package" ]
];