var _kpi_s_s_a_s_data_source_d_t_o_8cs =
[
    [ "EleWise.ELMA.KPI.DTO.Models.DataSources.KpiSSASDataSourceDTO", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_d_t_o_1_1_models_1_1_data_sources_1_1_kpi_s_s_a_s_data_source_d_t_o.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_d_t_o_1_1_models_1_1_data_sources_1_1_kpi_s_s_a_s_data_source_d_t_o" ]
];