var _kpi_value_question_history_part_provider_8cs =
[
    [ "EleWise.ELMA.KPI.Web.Components.KpiValueQuestionHistoryPartProvider", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_components_1_1_kpi_value_question_history_part_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_components_1_1_kpi_value_question_history_part_provider" ]
];