var _lead_default_selected_columns_provider_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.LeadDefaultSelectedColumnsProvider", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_lead_default_selected_columns_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_lead_default_selected_columns_provider" ]
];