var _life_cycle_status_changer_form_model_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Models.LifeCycleStatusChangerFormModel", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_models_1_1_life_cycle_status_changer_form_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_models_1_1_life_cycle_status_changer_form_model" ],
    [ "EleWise.ELMA.Documents.Web.Models.LifeCycleStatusItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_models_1_1_life_cycle_status_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_models_1_1_life_cycle_status_item" ]
];