var _localization_file_statistic_model_8cs =
[
    [ "EleWise.ELMA.Web.Mvc.Models.Translate.LocalizationFileStatisticModel", "class_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_models_1_1_translate_1_1_localization_file_statistic_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_models_1_1_translate_1_1_localization_file_statistic_model" ]
];