var _make_call_toolbar_button_8cs =
[
    [ "EleWise.ELMA.CRM.Telephony.Web.Components.MakeCallToolbarButton", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_web_1_1_components_1_1_make_call_toolbar_button.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_web_1_1_components_1_1_make_call_toolbar_button" ],
    [ "EleWise.ELMA.CRM.Telephony.Web.Components.MakeCallToobarButtonItem", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_web_1_1_components_1_1_make_call_toobar_button_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_web_1_1_components_1_1_make_call_toobar_button_item" ]
];