var _marketing_activity_work_log_extension_8cs =
[
    [ "EleWise.ELMA.CRM.Components.WorkLog.MarketingActivityWorkLogExtension", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_components_1_1_work_log_1_1_marketing_activity_work_log_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_components_1_1_work_log_1_1_marketing_activity_work_log_extension" ]
];