var _marketing_statistic_menu_provider_extension_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.FilterMarketingStatisticMenuProviderExtension", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_filter_marketing_statistic_menu_provider_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_filter_marketing_statistic_menu_provider_extension" ]
];