var _marker_multi_instance_shape_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Shapes.Tasks.MarkerMultiInstanceShape", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_tasks_1_1_marker_multi_instance_shape.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_tasks_1_1_marker_multi_instance_shape" ]
];