var _message_send_activity_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Activities.Tasks.MessageSendActivity", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_tasks_1_1_message_send_activity.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_tasks_1_1_message_send_activity" ]
];