var _milestone_task_solve_quick_mode_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Extensions.MilestoneTaskSolveQuickMode", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extensions_1_1_milestone_task_solve_quick_mode.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extensions_1_1_milestone_task_solve_quick_mode" ]
];