var _milestone_filter_portlet_available_property_uids_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Extensions.MilestoneFilterPortletAvailablePropertyUids", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extensions_1_1_milestone_filter_portlet_available_property_uids.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_extensions_1_1_milestone_filter_portlet_available_property_uids" ]
];