var _modules_2_ele_wise_8_e_l_m_a_8_messaging_8_s_m_s_8_web_2_models_2_chart_settings_8cs =
[
    [ "EleWise.ELMA.Messaging.SMS.Web.Models.ChartSettings", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_web_1_1_models_1_1_chart_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_web_1_1_models_1_1_chart_settings" ]
];