var _modules_2_ele_wise_8_e_l_m_a_8_business_rules_8_web_2_models_2_permission_model_8cs =
[
    [ "EleWise.ELMA.BusinessRules.Web.Models.PermissionModel", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_models_1_1_permission_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_models_1_1_permission_model" ]
];