var _monitor_processes_all_info_listener_8cs =
[
    [ "EleWise.ELMA.Workflow.Listeners.MonitorProcessesAllInfoListener", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_listeners_1_1_monitor_processes_all_info_listener.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_listeners_1_1_monitor_processes_all_info_listener" ]
];