var _monthly_periodical_entity_settings_8cs =
[
    [ "EleWise.ELMA.Common.Models.PeriodicalEntitySettings.MonthlyPeriodicalEntitySettings", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_models_1_1_periodical_entity_settings_1_1_monthly_periodical_entity_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_models_1_1_periodical_entity_settings_1_1_monthly_periodical_entity_settings" ]
];