var _my_processes_controller_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Controllers.MyProcessesController", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_controllers_1_1_my_processes_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_controllers_1_1_my_processes_controller" ]
];