var _n_h_provider_dependent_user_type_registrar_0l2_8cs =
[
    [ "EleWise.ELMA.Runtime.Managers.NHProviderDependentUserTypeRegistrar< TUserTypeImpl, TUserTypeBase >", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_managers_1_1_n_h_provider_dependent_user_type_registrar.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_managers_1_1_n_h_provider_dependent_user_type_registrar" ]
];