var _namespace_import_declaration_syntax_8cs =
[
    [ "EleWise.ELMA.CodeGeneration.CSharp.Nodes.NamespaceImportDeclarationSyntax", "class_ele_wise_1_1_e_l_m_a_1_1_code_generation_1_1_c_sharp_1_1_nodes_1_1_namespace_import_declaration_syntax.html", "class_ele_wise_1_1_e_l_m_a_1_1_code_generation_1_1_c_sharp_1_1_nodes_1_1_namespace_import_declaration_syntax" ]
];