var _notification_template_embedded_data_source_8cs =
[
    [ "EleWise.ELMA.Notifications.Impl.NotificationTemplateEmbeddedDataSource", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_notification_template_embedded_data_source.html", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_notification_template_embedded_data_source" ]
];