var _notification_workflow_task_functions_8cs =
[
    [ "EleWise.ELMA.Workflow.Components.NotificationWorkflowTaskFunctions", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_notification_workflow_task_functions.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_notification_workflow_task_functions" ]
];