var _notification_partial_extension_template_8cs =
[
    [ "EleWise.ELMA.Notifications.Impl.NotificationPartialExtensionTemplate", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_notification_partial_extension_template.html", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_notification_partial_extension_template" ]
];