var _notification_generator_provider_8cs =
[
    [ "EleWise.ELMA.Notifications.Impl.TemplateGenerator.NotificationGeneratorProvider", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_template_generator_1_1_notification_generator_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_notifications_1_1_impl_1_1_template_generator_1_1_notification_generator_provider" ]
];