var _o_data_connection_exception_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Exceptions.ODataConnectionException", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_exceptions_1_1_o_data_connection_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_exceptions_1_1_o_data_connection_exception" ]
];