var _object_map_provider_base_8cs =
[
    [ "EleWise.ELMA.Common.BulkDataImport.Mapping.Providers.ObjectMapProviderBase", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_mapping_1_1_providers_1_1_object_map_provider_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_mapping_1_1_providers_1_1_object_map_provider_base" ]
];