var _oktell_settings_controller_8cs =
[
    [ "EleWise.ELMA.IntegrationOktell.Web.Controllers.OktellSettingsController", "class_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_web_1_1_controllers_1_1_oktell_settings_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_web_1_1_controllers_1_1_oktell_settings_controller" ]
];