var _oktell_user_settings_model_handler_8cs =
[
    [ "EleWise.ELMA.IntegrationOktell.Web.Components.OktellUserSettingsModelHandler", "class_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_web_1_1_components_1_1_oktell_user_settings_model_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_oktell_1_1_web_1_1_components_1_1_oktell_user_settings_model_handler" ]
];