var _on_entity_property_changed_script_type_8cs =
[
    [ "EleWise.ELMA.Model.Scripts.Types.OnEntityPropertyChangedScriptType", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_scripts_1_1_types_1_1_on_entity_property_changed_script_type.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_scripts_1_1_types_1_1_on_entity_property_changed_script_type" ]
];