var _organization_model_import_entity_save_action_8cs =
[
    [ "EleWise.ELMA.Security.Deploy.Import.OrganizationModelImportEntitySaveAction", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_deploy_1_1_import_1_1_organization_model_import_entity_save_action.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_deploy_1_1_import_1_1_organization_model_import_entity_save_action" ]
];