var _organization_annotation_connector_shape_8cs =
[
    [ "EleWise.ELMA.Security.Diagrams.Shapes.OrganizationAnnotationConnectorShape", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_diagrams_1_1_shapes_1_1_organization_annotation_connector_shape.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_diagrams_1_1_shapes_1_1_organization_annotation_connector_shape" ]
];