var _package_dependency_manifest_8cs =
[
    [ "EleWise.ELMA.Packaging.ElmaStoreManifest.PackageDependencyManifest", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_elma_store_manifest_1_1_package_dependency_manifest.html", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_elma_store_manifest_1_1_package_dependency_manifest" ]
];