var _package_manager_project_system_8cs =
[
    [ "EleWise.ELMA.Packaging.Components.PackageManager.PackageManagerProjectSystem", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_components_1_1_package_manager_1_1_package_manager_project_system.html", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_components_1_1_package_manager_1_1_package_manager_project_system" ]
];