var _performance_approval_task_ext_actions_8cs =
[
    [ "EleWise.ELMA.KPI.Workflow.Models.PerformanceApprovalTaskExtActions", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_models_1_1_performance_approval_task_ext_actions.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_models_1_1_performance_approval_task_ext_actions" ]
];