var _performance_item_filter_settings_8cs =
[
    [ "EleWise.ELMA.KPI.Web.Models.Settings.PerformanceItemFilterSettings", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_models_1_1_settings_1_1_performance_item_filter_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_models_1_1_settings_1_1_performance_item_filter_settings" ]
];