var _percent_at_zero_plan_settings_extension_8cs =
[
    [ "EleWise.ELMA.KPI.Common.Extensions.PercentAtZeroPlanSettingsExtension", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_common_1_1_extensions_1_1_percent_at_zero_plan_settings_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_common_1_1_extensions_1_1_percent_at_zero_plan_settings_extension" ]
];