var _performance_approval_task_controller_8cs =
[
    [ "EleWise.ELMA.KPI.Web.Controllers.PerformanceApprovalTaskController", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_controllers_1_1_performance_approval_task_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_controllers_1_1_performance_approval_task_controller" ]
];