var _performance_approval_task_ext_manager_8cs =
[
    [ "EleWise.ELMA.KPI.Workflow.Managers.PerformanceApprovalTaskExtManager", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_managers_1_1_performance_approval_task_ext_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_managers_1_1_performance_approval_task_ext_manager" ]
];