var _permission_add_request_model_8cs =
[
    [ "EleWise.ELMA.Security.Mobile.API.Models.PermissionAddRequestModel", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_mobile_1_1_a_p_i_1_1_models_1_1_permission_add_request_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_mobile_1_1_a_p_i_1_1_models_1_1_permission_add_request_model" ]
];