var _permission_public_service_methods_provider_8cs =
[
    [ "EleWise.ELMA.Security.Mobile.API.Services.PermissionPublicServiceMethodsProvider", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_mobile_1_1_a_p_i_1_1_services_1_1_permission_public_service_methods_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_mobile_1_1_a_p_i_1_1_services_1_1_permission_public_service_methods_provider" ]
];