var _periodical_entity_creating_job_repository_8cs =
[
    [ "EleWise.ELMA.Common.Components.PeriodicalEntityCreatingJobRepository", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_components_1_1_periodical_entity_creating_job_repository.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_components_1_1_periodical_entity_creating_job_repository" ]
];