var _performance_value_view_average_8cs =
[
    [ "EleWise.ELMA.KPI.Web.Components.PerformanceValueViewTypes.PerformanceValueViewAverage", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_components_1_1_performance_value_view_types_1_1_performance_value_view_average.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_web_1_1_components_1_1_performance_value_view_types_1_1_performance_value_view_average" ]
];