var _placement_file_parser_8cs =
[
    [ "Orchard.DisplayManagement.Descriptors.ShapePlacementStrategy.PlacementFileParser", "class_orchard_1_1_display_management_1_1_descriptors_1_1_shape_placement_strategy_1_1_placement_file_parser.html", "class_orchard_1_1_display_management_1_1_descriptors_1_1_shape_placement_strategy_1_1_placement_file_parser" ]
];