var _portlet_personalization_generator_8cs =
[
    [ "EleWise.ELMA.UI.CodeGeneration.PortletPersonalizationGenerator", "class_ele_wise_1_1_e_l_m_a_1_1_u_i_1_1_code_generation_1_1_portlet_personalization_generator.html", "class_ele_wise_1_1_e_l_m_a_1_1_u_i_1_1_code_generation_1_1_portlet_personalization_generator" ]
];