var _portlets_restriction_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Content.Security.PortletsRestrictionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_security_1_1_portlets_restriction_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_security_1_1_portlets_restriction_provider" ]
];