var _postgre_s_q_l_external_data_source_executor_8cs =
[
    [ "EleWise.ELMA.Extensions.PostgreSQL.PostgreSQLExternalDataSourceExecutor", "class_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_postgre_s_q_l_1_1_postgre_s_q_l_external_data_source_executor.html", "class_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_postgre_s_q_l_1_1_postgre_s_q_l_external_data_source_executor" ]
];