var _prepare_log_on_certificate_model_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.Models.PrepareLogOnCertificateModel", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_prepare_log_on_certificate_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_prepare_log_on_certificate_model" ],
    [ "EleWise.ELMA.BPM.Web.Security.Models.PrepareLogOnCertificateModelExt", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_prepare_log_on_certificate_model_ext.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_prepare_log_on_certificate_model_ext" ]
];