var _pre_start_test_import_parameters_8cs =
[
    [ "EleWise.ELMA.Deploy.Import.ExtensionPoints.PreStartTestImportParameters", "class_ele_wise_1_1_e_l_m_a_1_1_deploy_1_1_import_1_1_extension_points_1_1_pre_start_test_import_parameters.html", "class_ele_wise_1_1_e_l_m_a_1_1_deploy_1_1_import_1_1_extension_points_1_1_pre_start_test_import_parameters" ]
];