var _profile_action_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.ExtensionPoints.ProfileActionAttribute", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_profile_action_attribute.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_profile_action_attribute" ],
    [ "EleWise.ELMA.BPM.Web.Security.ExtensionPoints.ProfileActionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_profile_action_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_profile_action_provider" ]
];