var _property_marketing_effect_is_empty_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.PropertyMarketingEffectIsEmpty", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_property_marketing_effect_is_empty.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_property_marketing_effect_is_empty" ]
];