var _property_action_info_base_8cs =
[
    [ "EleWise.ELMA.Common.BulkDataImport.Mapping.Models.PropertyActionInfoBase", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_mapping_1_1_models_1_1_property_action_info_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_mapping_1_1_models_1_1_property_action_info_base" ]
];