var _project_budget_approval_task_model_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Models.Budget.ProjectBudgetApprovalTaskModel", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_budget_1_1_project_budget_approval_task_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_budget_1_1_project_budget_approval_task_model" ]
];