var _project_from_me_tasks_portlet_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectFromMeTasksPortlet", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_from_me_tasks_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_from_me_tasks_portlet" ],
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectFromMeTasksPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_from_me_tasks_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_from_me_tasks_portlet_personalization" ]
];