var _project_portlets_restriction_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectPortletsRestrictionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_portlets_restriction_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_portlets_restriction_provider" ]
];