var _process_header_select_group_resolver_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Extensions.ProcessHeaderSelectGroupResolver", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_extensions_1_1_process_header_select_group_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_extensions_1_1_process_header_select_group_resolver" ]
];