var _project_tasks_public_service_methods_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Mobile.API.ProjectTasksPublicServiceMethodsProvider", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_mobile_1_1_a_p_i_1_1_project_tasks_public_service_methods_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_mobile_1_1_a_p_i_1_1_project_tasks_public_service_methods_provider" ]
];