var _project_budget_approve_task_shape_8cs =
[
    [ "EleWise.ELMA.Projects.BPMN.Diagrams.Shapes.Tasks.ProjectBudgetApproveTaskShape", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_tasks_1_1_project_budget_approve_task_shape.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_b_p_m_n_1_1_diagrams_1_1_shapes_1_1_tasks_1_1_project_budget_approve_task_shape" ]
];