var _project_roles_update_queue_item_8cs =
[
    [ "EleWise.ELMA.Projects.Models.ProjectRolesUpdate.ProjectRolesUpdateQueueItem", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_project_roles_update_1_1_project_roles_update_queue_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_models_1_1_project_roles_update_1_1_project_roles_update_queue_item" ]
];