var _project_metadata_head_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.Projects.DTO.Managers.ProjectMetadataHeadDTOManager", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_d_t_o_1_1_managers_1_1_project_metadata_head_d_t_o_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_d_t_o_1_1_managers_1_1_project_metadata_head_d_t_o_manager" ]
];