var _process_instance_metrics_container_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.ProcessInstanceMetricsContainer", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_process_instance_metrics_container.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_process_instance_metrics_container" ],
    [ "EleWise.ELMA.Workflow.Models.ProcessInstanceMetricsContainer.Info", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_process_instance_metrics_container_1_1_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_process_instance_metrics_container_1_1_info" ]
];