var _process_permissions_page_provider_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Components.ProcessPermissionsPageProvider", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_process_permissions_page_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_process_permissions_page_provider" ]
];