var _project_process_portlet_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectProcessPortlet", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_process_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_process_portlet" ],
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectProcessPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_process_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_process_portlet_personalization" ]
];