var _project_common_info_portlet_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectCommonInfoPortlet", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_common_info_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_common_info_portlet" ],
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectCommonInfoPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_common_info_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_common_info_portlet_personalization" ]
];