var _projects_current_list_portlet_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectsCurrentListPortlet", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_projects_current_list_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_projects_current_list_portlet" ],
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectsCurrentListPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_projects_current_list_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_projects_current_list_portlet_personalization" ]
];