var _project_plan_approval_task_expired_recipient_handler_8cs =
[
    [ "EleWise.ELMA.Projects.Notifications.ProjectPlanApprovalTaskExpiredRecipientHandler", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_notifications_1_1_project_plan_approval_task_expired_recipient_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_notifications_1_1_project_plan_approval_task_expired_recipient_handler" ]
];