var _project_workflow_element_base_8cs =
[
    [ "EleWise.ELMA.Projects.BPMN.Diagrams.Elements.Tasks.ProjectWorkflowElementBase", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_project_workflow_element_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_project_workflow_element_base" ]
];