var _project_filter_permission_resolver_8cs =
[
    [ "EleWise.ELMA.Projects.Components.ProjectFilterPermissionResolver", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_project_filter_permission_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_project_filter_permission_resolver" ]
];