var _project_object_view_item_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Components.ProjectObjectViewItemProvider", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_project_object_view_item_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_project_object_view_item_provider" ]
];