var _project_task_solve_task_view_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Integration.Portlets.ProjectTaskSolveTaskView", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_integration_1_1_portlets_1_1_project_task_solve_task_view.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_integration_1_1_portlets_1_1_project_task_solve_task_view" ]
];