var _project_comment_history_part_provider_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.EventRender.ProjectCommentHistoryPartProvider", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_event_render_1_1_project_comment_history_part_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_event_render_1_1_project_comment_history_part_provider" ]
];