var _processes_workflow_instance_manager_8cs =
[
    [ "EleWise.ELMA.Workflow.Managers.ProcessesWorkflowInstanceManager", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_managers_1_1_processes_workflow_instance_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_managers_1_1_processes_workflow_instance_manager" ]
];