var _property_metadata_additional_attribute_8cs =
[
    [ "EleWise.ELMA.Model.Metadata.PropertyMetadataAdditionalAttribute", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_property_metadata_additional_attribute.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_property_metadata_additional_attribute" ]
];