var _project_phase_task_in_control_portlet_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectPhaseTaskInControlPortlet", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_phase_task_in_control_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_phase_task_in_control_portlet" ],
    [ "EleWise.ELMA.Projects.Web.Portlets.ProjectPhaseTaskInControlPortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_phase_task_in_control_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_portlets_1_1_project_phase_task_in_control_portlet_personalization" ]
];