var _project_task_work_log_object_search_extension_8cs =
[
    [ "EleWise.ELMA.Projects.Components.WorkLog.ProjectTaskWorkLogObjectSearchExtension", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_work_log_1_1_project_task_work_log_object_search_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_work_log_1_1_project_task_work_log_object_search_extension" ]
];