var _project_settings_module_controller_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.ProjectSettingsModuleController", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_project_settings_module_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_project_settings_module_controller" ]
];