var _project_task_base_permissions_delegate_8cs =
[
    [ "EleWise.ELMA.Projects.Security.ProjectTaskBasePermissionsDelegate", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_task_base_permissions_delegate.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_task_base_permissions_delegate" ]
];