var _project_workflow_instance_start_manager_8cs =
[
    [ "EleWise.ELMA.Projects.Managers.ProjectWorkflowInstanceStartManager", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_managers_1_1_project_workflow_instance_start_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_managers_1_1_project_workflow_instance_start_manager" ]
];