var _project_approval_task_feed_comment_action_name_extension_8cs =
[
    [ "EleWise.ELMA.Projects.Components.Feed.ProjectApprovalTaskFeedCommentActionNameExtension", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_feed_1_1_project_approval_task_feed_comment_action_name_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_feed_1_1_project_approval_task_feed_comment_action_name_extension" ]
];