var _project_complex_task_activity_8cs =
[
    [ "EleWise.ELMA.Projects.BPMN.Diagrams.Activities.Tasks.ProjectComplexTaskActivity", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_tasks_1_1_project_complex_task_activity.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_tasks_1_1_project_complex_task_activity" ]
];