var _process_context_generation_params_8cs =
[
    [ "EleWise.ELMA.Workflow.CodeGeneration.ProcessContextGenerationParams", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_code_generation_1_1_process_context_generation_params.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_code_generation_1_1_process_context_generation_params" ]
];