var _published_process_filter_provider_8cs =
[
    [ "EleWise.ELMA.Workflow.Components.PublishedProcessFilterProvider", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_published_process_filter_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_published_process_filter_provider" ]
];