var _public_api_services_description_8cs =
[
    [ "EleWise.ELMA.Model.CodeGeneration.PublicApi.PublicApiServicesDescription", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_code_generation_1_1_public_api_1_1_public_api_services_description.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_code_generation_1_1_public_api_1_1_public_api_services_description" ]
];