var _question_history_collector_base_cachable_8cs =
[
    [ "EleWise.ELMA.Tasks.Audit.History.QuestionHistoryCollectorBaseCachable", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_audit_1_1_history_1_1_question_history_collector_base_cachable.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_audit_1_1_history_1_1_question_history_collector_base_cachable" ]
];