var _recipient_info_for_notification_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Elements.Tasks.RecipientInfoForNotification", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_recipient_info_for_notification.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_recipient_info_for_notification" ]
];