var _recipe_execution_step_configuration_context_8cs =
[
    [ "Orchard.Recipes.Models.RecipeExecutionStepConfigurationContext", "class_orchard_1_1_recipes_1_1_models_1_1_recipe_execution_step_configuration_context.html", "class_orchard_1_1_recipes_1_1_models_1_1_recipe_execution_step_configuration_context" ]
];