var _redirect_solve_task_action_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Integration.Portlets.RedirectSolveTaskAction", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_integration_1_1_portlets_1_1_redirect_solve_task_action.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_integration_1_1_portlets_1_1_redirect_solve_task_action" ]
];