var _reference_on_entity_type_convention_8cs =
[
    [ "EleWise.ELMA.Model.Entities.EntityReferences.ReferenceOnEntityTypeConvention", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_entities_1_1_entity_references_1_1_reference_on_entity_type_convention.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_entities_1_1_entity_references_1_1_reference_on_entity_type_convention" ]
];