var _reference_on_entity_type_8cs =
[
    [ "EleWise.ELMA.Model.Entities.EntityReferences.ReferenceOnEntityType", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_entities_1_1_entity_references_1_1_reference_on_entity_type.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_entities_1_1_entity_references_1_1_reference_on_entity_type" ]
];