var _registration_card_converted_action_event_args_8cs =
[
    [ "EleWise.ELMA.Documents.Audit.RegistrationCardConvertedActionEventArgs", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_audit_1_1_registration_card_converted_action_event_args.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_audit_1_1_registration_card_converted_action_event_args" ]
];