var _registration_card_simple_event_render_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Components.RegistrationCardSimpleEventRender", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_registration_card_simple_event_render.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_registration_card_simple_event_render" ]
];