var _registration_card_custom_sortable_8cs =
[
    [ "EleWise.ELMA.Documents.Components.RegistrationCardCustomSortable", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_registration_card_custom_sortable.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_components_1_1_registration_card_custom_sortable" ]
];