var _registration_card_property_input_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Inputs.RegistrationCardPropertyInput", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_inputs_1_1_registration_card_property_input.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_inputs_1_1_registration_card_property_input" ]
];