var _regulation_header_properties_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.Regulation.RegulationHeaderProperties", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_regulation_1_1_regulation_header_properties.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_regulation_1_1_regulation_header_properties" ]
];