var _registration_card_registration_info_view_item_8cs =
[
    [ "EleWise.ELMA.Documents.ViewItems.RegistrationCardRegistrationInfoViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_registration_card_registration_info_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_view_items_1_1_registration_card_registration_info_view_item" ]
];