var _registration_place_instance_default_permission_8cs =
[
    [ "EleWise.ELMA.Documents.Security.RegistrationPlaceInstanceDefaultPermission", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_registration_place_instance_default_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_registration_place_instance_default_permission" ]
];