var _relative_date_time_wrapper_descriptor_8cs =
[
    [ "EleWise.ELMA.Model.Types.Helpers.RelativeDateTimeWrapperDescriptor", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_types_1_1_helpers_1_1_relative_date_time_wrapper_descriptor.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_types_1_1_helpers_1_1_relative_date_time_wrapper_descriptor" ]
];