var _related_tasks_view_item_renderer_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.FormViews.RelatedTasksViewItemRenderer", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_form_views_1_1_related_tasks_view_item_renderer.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_form_views_1_1_related_tasks_view_item_renderer" ]
];