var _render_by_document_task_close_history_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.History.RenderByDocumentTaskCloseHistory", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_render_by_document_task_close_history.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_render_by_document_task_close_history" ]
];