var _report_footer_query_rec_8cs =
[
    [ "EleWise.ELMA.CRM.Workflow.Processes.Models.SaleDynamicReport.ReportFooterQueryRec", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_models_1_1_sale_dynamic_report_1_1_report_footer_query_rec.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_models_1_1_sale_dynamic_report_1_1_report_footer_query_rec" ]
];