var _replacement_task_active_tasks_tab_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Components.ReplacementTaskActiveTasksTab", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_replacement_task_active_tasks_tab.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_replacement_task_active_tasks_tab" ]
];