var _reports_instance_settings_permission_8cs =
[
    [ "EleWise.ELMA.Reports.Security.ReportsInstanceSettingsPermission", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_security_1_1_reports_instance_settings_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_security_1_1_reports_instance_settings_permission" ]
];