var _report_external_data_source_processor_connection_excepti_8cs =
[
    [ "EleWise.ELMA.Reports.Exceptions.ReportExternalDataSourceProcessorConnectionException", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_exceptions_1_1_report_external_data_source_processor_connection_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_exceptions_1_1_report_external_data_source_processor_connection_exception" ]
];