var _reports_common_home_page_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Reports.Components.ReportsCommonHomePageProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_components_1_1_reports_common_home_page_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_reports_1_1_components_1_1_reports_common_home_page_provider" ]
];