var _resource_calendar_simple_model_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Calendar.Models.ResourceCalendarSimpleModel", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_calendar_1_1_models_1_1_resource_calendar_simple_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_calendar_1_1_models_1_1_resource_calendar_simple_model" ]
];