var _review_task_tool_bar_button_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Integration.Buttons.ReviewTaskToolBarButton", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_buttons_1_1_review_task_tool_bar_button.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_buttons_1_1_review_task_tool_bar_button" ]
];