var _root_code_item_collection_type_descriptor_8cs =
[
    [ "EleWise.ELMA.ScriptDesigner.TranslateData.RootCodeItemCollectionTypeDescriptor", "class_ele_wise_1_1_e_l_m_a_1_1_script_designer_1_1_translate_data_1_1_root_code_item_collection_type_descriptor.html", "class_ele_wise_1_1_e_l_m_a_1_1_script_designer_1_1_translate_data_1_1_root_code_item_collection_type_descriptor" ]
];