var _sale_dynamic_filter_permission_resolver_8cs =
[
    [ "EleWise.ELMA.CRM.Extensions.SaleDynamicFilterPermissionResolver", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extensions_1_1_sale_dynamic_filter_permission_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extensions_1_1_sale_dynamic_filter_permission_resolver" ]
];