var _sale_form_view_item_transformate_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.SaleContractorReadOnlyFunnelFormViewItemTransformate", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_sale_contractor_read_only_funnel_form_view_item_transformate.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_sale_contractor_read_only_funnel_form_view_item_transformate" ]
];