var _sale_dynamic_report_manager_8cs =
[
    [ "EleWise.ELMA.CRM.Workflow.Processes.Managers.SaleDynamicReportManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_managers_1_1_sale_dynamic_report_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_managers_1_1_sale_dynamic_report_manager" ]
];