var _sale_products_grid_view_item_renderer_8cs =
[
    [ "EleWise.ELMA.CRM.Web.Components.SaleProductsGridViewItemRenderer", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_sale_products_grid_view_item_renderer.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_web_1_1_components_1_1_sale_products_grid_view_item_renderer" ]
];