var _search_uses_elements_organization_d_t_o_manager_8cs =
[
    [ "EleWise.ELMA.Documents.DTO.Managers.SearchUsesElementsOrganizationDTOManager", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_d_t_o_1_1_managers_1_1_search_uses_elements_organization_d_t_o_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_d_t_o_1_1_managers_1_1_search_uses_elements_organization_d_t_o_manager" ]
];