var _shape_template_binding_strategy_8cs =
[
    [ "Orchard.DisplayManagement.Descriptors.ShapeTemplateStrategy.ShapeTemplateBindingStrategy", "class_orchard_1_1_display_management_1_1_descriptors_1_1_shape_template_strategy_1_1_shape_template_binding_strategy.html", "class_orchard_1_1_display_management_1_1_descriptors_1_1_shape_template_strategy_1_1_shape_template_binding_strategy" ]
];