var _sign_security_actions_extension_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Components.SignSecurityActionsExtension", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_sign_security_actions_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_components_1_1_sign_security_actions_extension" ]
];