var _sql_query_call_metric_processor_8cs =
[
    [ "EleWise.ELMA.Diagnostics.Metrics.Impl.Processors.SqlQueryCallMetricProcessor", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_metrics_1_1_impl_1_1_processors_1_1_sql_query_call_metric_processor.html", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_metrics_1_1_impl_1_1_processors_1_1_sql_query_call_metric_processor" ]
];