var _start_approvement_activity_8cs =
[
    [ "EleWise.ELMA.Documents.BPMN.Diagrams.Activities.Approvement.StartApprovementActivity", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_approvement_1_1_start_approvement_activity.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_diagrams_1_1_activities_1_1_approvement_1_1_start_approvement_activity" ]
];