var _static_file_image_browser_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Content.Services.StaticMediaFileProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_services_1_1_static_media_file_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_services_1_1_static_media_file_provider" ],
    [ "EleWise.ELMA.BPM.Web.Content.Services.StaticMediaFileService", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_services_1_1_static_media_file_service.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_content_1_1_services_1_1_static_media_file_service" ]
];