var _stylesheet_binding_strategy_8cs =
[
    [ "Orchard.DisplayManagement.Descriptors.ResourceBindingStrategy.StylesheetBindingStrategy", "class_orchard_1_1_display_management_1_1_descriptors_1_1_resource_binding_strategy_1_1_stylesheet_binding_strategy.html", "class_orchard_1_1_display_management_1_1_descriptors_1_1_resource_binding_strategy_1_1_stylesheet_binding_strategy" ]
];