var _sub_project___project_task_state_re_calculate_extension_8cs =
[
    [ "EleWise.ELMA.Projects.Components.SubProject_ProjectTaskStateReCalculateExtension", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_sub_project___project_task_state_re_calculate_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_components_1_1_sub_project___project_task_state_re_calculate_extension" ]
];