var _subtask_approvement_list_item_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Models.SubtaskApprovementListItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_models_1_1_subtask_approvement_list_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_models_1_1_subtask_approvement_list_item" ]
];