var _sub_task_copy_settings_renderer_base_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.SubTaskCopySettingsRendererBase", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_sub_task_copy_settings_renderer_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_sub_task_copy_settings_renderer_base" ]
];