var _summary_table_work_log_portlet_model_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Models.SummaryTableWorkLogPortletModel", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_summary_table_work_log_portlet_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_summary_table_work_log_portlet_model" ]
];