var _table_part_external_data_dynamic_8cs =
[
    [ "EleWise.ELMA.IntegrationExternalData.Models.TablePartExternalDataDynamic", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_models_1_1_table_part_external_data_dynamic.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_external_data_1_1_models_1_1_table_part_external_data_dynamic" ]
];