var _task_feed_object_group_extension_8cs =
[
    [ "EleWise.ELMA.Tasks.Components.Feed.TaskFeedObjectGroupExtension", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_feed_1_1_task_feed_object_group_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_feed_1_1_task_feed_object_group_extension" ]
];