var _task_questions_history_part_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Components.TaskQuestionsHistoryPartProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_task_questions_history_part_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_task_questions_history_part_provider" ]
];