var _tasks_common_home_page_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Components.TasksCommonHomePageProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_tasks_common_home_page_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_components_1_1_tasks_common_home_page_provider" ]
];