var _task_filter_portlet_check_permission_extensions_8cs =
[
    [ "EleWise.ELMA.Tasks.Extensions.TaskFilterPortletCheckPermissionExtensions", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extensions_1_1_task_filter_portlet_check_permission_extensions.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extensions_1_1_task_filter_portlet_check_permission_extensions" ]
];