var _task_document_attachments_zone_8cs =
[
    [ "EleWise.ELMA.Documents.Web.Integration.Tasks.TaskDocumentAttachmentsZone", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_integration_1_1_tasks_1_1_task_document_attachments_zone.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_web_1_1_integration_1_1_tasks_1_1_task_document_attachments_zone" ]
];