var _task_base_work_log_object_search_extension_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.TaskBaseWorkLogObjectSearchExtension", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_task_base_work_log_object_search_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_task_base_work_log_object_search_extension" ]
];