var _tasks_filter_portlet_extensions_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.TasksFilterPortletExtensions", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_tasks_filter_portlet_extensions.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_tasks_filter_portlet_extensions" ]
];