var _task_extended_validator_extender_8cs =
[
    [ "EleWise.ELMA.Documents.Docflow.Web.Integration.Views.TaskExtendedValidatorExtender", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_views_1_1_task_extended_validator_extender.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_integration_1_1_views_1_1_task_extended_validator_extender" ]
];