var _tasks_grid_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Integration.Tasks.MyTasksPortletGridExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_my_tasks_portlet_grid_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_my_tasks_portlet_grid_extension" ],
    [ "EleWise.ELMA.Workflow.Web.Integration.Tasks.AllTasksGridExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_all_tasks_grid_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_all_tasks_grid_extension" ],
    [ "EleWise.ELMA.Workflow.Web.Integration.Tasks.TasksGridExtensionBase", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_tasks_grid_extension_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_tasks_grid_extension_base" ]
];