var _task_status_link_descriptions_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.ApprovalTaskStatusLinkDescription", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_approval_task_status_link_description.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_approval_task_status_link_description" ],
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.ReplacementTaskStatusLinkDescription", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_replacement_task_status_link_description.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_replacement_task_status_link_description" ],
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.TaskStatusLinkDescription", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_task_status_link_description.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_task_status_link_description" ]
];