var _technical_resource_index_model_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Models.Resources.TechnicalResourceIndexModel", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_resources_1_1_technical_resource_index_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_models_1_1_resources_1_1_technical_resource_index_model" ]
];