var _telephony_settings_module_controller_8cs =
[
    [ "EleWise.ELMA.CRM.Telephony.Web.Components.TelephonySettingsModuleController", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_web_1_1_components_1_1_telephony_settings_module_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_telephony_1_1_web_1_1_components_1_1_telephony_settings_module_controller" ]
];