var _transformation_provider_base_8cs =
[
    [ "EleWise.ELMA.Runtime.Db.Migrator.Providers.TransformationProviderBase", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_db_1_1_migrator_1_1_providers_1_1_transformation_provider_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_db_1_1_migrator_1_1_providers_1_1_transformation_provider_base" ]
];