var _type_settings_instance_data_n_h_type_8cs =
[
    [ "EleWise.ELMA.Runtime.NH.CustomTypes.TypeSettingsInstanceDataNHType", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_n_h_1_1_custom_types_1_1_type_settings_instance_data_n_h_type.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_n_h_1_1_custom_types_1_1_type_settings_instance_data_n_h_type" ],
    [ "EleWise.ELMA.Runtime.NH.CustomTypes.TypeSettingsInstanceDataNHType.Convention", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_n_h_1_1_custom_types_1_1_type_settings_instance_data_n_h_type_1_1_convention.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_n_h_1_1_custom_types_1_1_type_settings_instance_data_n_h_type_1_1_convention" ]
];