var _type_filter_property_resolver_attribute_8cs =
[
    [ "EleWise.ELMA.Model.Attributes.TypeFilterPropertyResolverAttribute", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_attributes_1_1_type_filter_property_resolver_attribute.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_attributes_1_1_type_filter_property_resolver_attribute" ]
];