var _update_public_application_token_model_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.Models.UpdatePublicApplicationTokenModel", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_update_public_application_token_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_models_1_1_update_public_application_token_model" ]
];