var _user_task_element_8cs =
[
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Elements.Tasks.UserTaskElement", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_user_task_element.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_user_task_element" ],
    [ "EleWise.ELMA.Workflow.BPMN.Diagrams.Elements.Tasks.UserTaskElement.ToolboxItem", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_user_task_element_1_1_toolbox_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_diagrams_1_1_elements_1_1_tasks_1_1_user_task_element_1_1_toolbox_item" ]
];