var _users_home_portlet_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.Portlets.UsersHomePortlet", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_portlets_1_1_users_home_portlet.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_portlets_1_1_users_home_portlet" ],
    [ "EleWise.ELMA.BPM.Web.Security.Portlets.UsersHomePortletPersonalization", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_portlets_1_1_users_home_portlet_personalization.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_portlets_1_1_users_home_portlet_personalization" ]
];