var _user_type_filter_provider_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Security.ExtensionPoints.UserTypeFilterProvider", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_user_type_filter_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extension_points_1_1_user_type_filter_provider" ]
];