var _user_template_generator_functions_8cs =
[
    [ "EleWise.ELMA.Security.Notifications.UserTemplateGeneratorFunctions", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_notifications_1_1_user_template_generator_functions.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_notifications_1_1_user_template_generator_functions" ]
];