var _web_reference_discovery_response_8cs =
[
    [ "EleWise.ELMA.Scripts.ServiceReference.Models.WebReferenceDiscoveryResponse", "class_ele_wise_1_1_e_l_m_a_1_1_scripts_1_1_service_reference_1_1_models_1_1_web_reference_discovery_response.html", "class_ele_wise_1_1_e_l_m_a_1_1_scripts_1_1_service_reference_1_1_models_1_1_web_reference_discovery_response" ]
];