var _web_service_discovery_client_protocol_8cs =
[
    [ "EleWise.ELMA.Scripts.ServiceReference.WebServiceDiscoveryClientProtocol", "class_ele_wise_1_1_e_l_m_a_1_1_scripts_1_1_service_reference_1_1_web_service_discovery_client_protocol.html", "class_ele_wise_1_1_e_l_m_a_1_1_scripts_1_1_service_reference_1_1_web_service_discovery_client_protocol" ]
];