var _workflow_task_form_view_transformate_8cs =
[
    [ "EleWise.ELMA.Workflow.Components.WorkflowTaskFormViewTransformate", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_workflow_task_form_view_transformate.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_components_1_1_workflow_task_form_view_transformate" ]
];