var _workflow_task_base_export_excel_value_provider_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Integration.Tasks.WorkflowTaskBaseExportExcelValueProvider", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_workflow_task_base_export_excel_value_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_tasks_1_1_workflow_task_base_export_excel_value_provider" ]
];