var _workflow_metrics_values_view_model_8cs =
[
    [ "EleWise.ELMA.Workflow.Indicators.Web.Models.WorkflowMetricsValuesViewModel", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_models_1_1_workflow_metrics_values_view_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_models_1_1_workflow_metrics_values_view_model" ]
];