var _workflow_instance_question_history_collector_8cs =
[
    [ "EleWise.ELMA.Workflow.Audit.WorkflowInstanceQuestionHistoryCollector", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_audit_1_1_workflow_instance_question_history_collector.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_audit_1_1_workflow_instance_question_history_collector" ]
];