var _workflow_start_event_object_view_item_provider_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Integration.WorkflowStartEventObjectViewItemProvider", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_workflow_start_event_object_view_item_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_integration_1_1_workflow_start_event_object_view_item_provider" ]
];