var _work_log_item_approve_report_fields_filter_extension_8cs =
[
    [ "EleWise.ELMA.BPM.Web.Tasks.Extensions.WorkLogItemApproveReportFieldsFilterExtension", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_work_log_item_approve_report_fields_filter_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_tasks_1_1_extensions_1_1_work_log_item_approve_report_fields_filter_extension" ]
];