var _workflow_tasks_user_settings_model_handler_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Components.WorkflowTasksUserSettingsModelHandler", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_components_1_1_workflow_tasks_user_settings_model_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_components_1_1_workflow_tasks_user_settings_model_handler" ]
];