var _workflow_project_task_simple_event_render_8cs =
[
    [ "EleWise.ELMA.Projects.Web.Components.EventRender.WorkflowProjectTaskSimpleEventRender", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_event_render_1_1_workflow_project_task_simple_event_render.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_web_1_1_components_1_1_event_render_1_1_workflow_project_task_simple_event_render" ]
];