var _workflow_integration_activity_bookmark_info_8cs =
[
    [ "EleWise.ELMA.IntegrationModules.Workflow.Models.WorkflowIntegrationActivityBookmarkInfo", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_workflow_1_1_models_1_1_workflow_integration_activity_bookmark_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_workflow_1_1_models_1_1_workflow_integration_activity_bookmark_info" ]
];