var _workflow_sale_simple_event_render_8cs =
[
    [ "EleWise.ELMA.CRM.Workflow.Processes.Web.Components.WorkflowSaleSimpleEventRender", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_workflow_sale_simple_event_render.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_workflow_sale_simple_event_render" ]
];