var _workflow_instance_base_filter_creator_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Components.WorkflowInstanceBaseFilterCreator", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_workflow_instance_base_filter_creator.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_workflow_instance_base_filter_creator" ]
];