var _workflow_send_to_approvement_terminate_data_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.WorkflowSendToApprovementTerminateData", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_workflow_send_to_approvement_terminate_data.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_workflow_send_to_approvement_terminate_data" ]
];