var _workflow_external_sub_process_terminate_data_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.WorkflowExternalSubProcessTerminateData", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_workflow_external_sub_process_terminate_data.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_workflow_external_sub_process_terminate_data" ]
];