var _workflow_task_simple_event_render_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Components.WorkflowTaskSimpleEventRender", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_components_1_1_workflow_task_simple_event_render.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_components_1_1_workflow_task_simple_event_render" ]
];