var _workflow_queue_switcher_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Components.WorkflowQueueSwitcher", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_workflow_queue_switcher.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_components_1_1_workflow_queue_switcher" ]
];