var _workflow_notifications_data_source_8cs =
[
    [ "EleWise.ELMA.Workflow.Notifications.WorkflowNotificationsDataSource", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_workflow_notifications_data_source.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_workflow_notifications_data_source" ]
];