var _workflow_message_receive_action_event_args_8cs =
[
    [ "EleWise.ELMA.Workflow.Audit.WorkflowMessageReceiveActionEventArgs", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_audit_1_1_workflow_message_receive_action_event_args.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_audit_1_1_workflow_message_receive_action_event_args" ]
];