var _workflow_instance_migration_item_model_8cs =
[
    [ "EleWise.ELMA.Workflow.Processes.Web.Models.WorkflowInstanceMigrationItemModel", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_models_1_1_workflow_instance_migration_item_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_processes_1_1_web_1_1_models_1_1_workflow_instance_migration_item_model" ]
];