var _workflow_instance_migration_item_manager_8cs =
[
    [ "EleWise.ELMA.Workflow.Managers.WorkflowInstanceMigrationItemManager", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_managers_1_1_workflow_instance_migration_item_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_managers_1_1_workflow_instance_migration_item_manager" ]
];