var _work_log_item_filter_permission_resolver_8cs =
[
    [ "EleWise.ELMA.Tasks.Extensions.WorkLogItemFilterPermissionResolver", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extensions_1_1_work_log_item_filter_permission_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extensions_1_1_work_log_item_filter_permission_resolver" ]
];