var _workflow_forms_container_type_settings_8cs =
[
    [ "EleWise.ELMA.Workflow.Types.Settings.WorkflowFormsContainerTypeSettings", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_types_1_1_settings_1_1_workflow_forms_container_type_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_types_1_1_settings_1_1_workflow_forms_container_type_settings" ]
];