var _workflow_task_work_log_entity_link_description_8cs =
[
    [ "EleWise.ELMA.Workflow.Web.Extensions.WorkflowTaskWorkLogEntityLinkDescription", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_extensions_1_1_workflow_task_work_log_entity_link_description.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_web_1_1_extensions_1_1_workflow_task_work_log_entity_link_description" ]
];