var _work_log_summary_table_view_item_8cs =
[
    [ "EleWise.ELMA.Tasks.ViewItems.WorkLogSummaryTableViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_view_items_1_1_work_log_summary_table_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_view_items_1_1_work_log_summary_table_view_item" ],
    [ "EleWise.ELMA.Tasks.ViewItems.WorkLogSummaryTableViewItem.DebugView", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_view_items_1_1_work_log_summary_table_view_item_1_1_debug_view.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_view_items_1_1_work_log_summary_table_view_item_1_1_debug_view" ]
];