var _workflow_instance_indicators_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.Indicators.Web.Components.WorkflowInstanceIndicatorsExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components_1_1_workflow_instance_indicators_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components_1_1_workflow_instance_indicators_extension" ]
];