var _workflow_task_work_log_object_search_extension_8cs =
[
    [ "EleWise.ELMA.Workflow.Extensions.WorkflowTaskWorkLogObjectSearchExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_workflow_task_work_log_object_search_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_extensions_1_1_workflow_task_work_log_object_search_extension" ]
];