var _workflow_context_property_observer_info_8cs =
[
    [ "EleWise.ELMA.Workflow.Models.WorkflowContextPropertyObserverInfo", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_workflow_context_property_observer_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_workflow_context_property_observer_info" ]
];