var _work_log_item_unique_filter_extension_8cs =
[
    [ "EleWise.ELMA.Tasks.ExtensionPoints.WorkLogItemUniqueFilterExtension", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_work_log_item_unique_filter_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_work_log_item_unique_filter_extension" ]
];