var _xml_serializable_object_type_descriptor_8cs =
[
    [ "EleWise.ELMA.Model.Types.XmlSerializableObjectTypeDescriptor", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_types_1_1_xml_serializable_object_type_descriptor.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_types_1_1_xml_serializable_object_type_descriptor" ]
];