var bin_2_ele_wise_8_e_l_m_a_8_messaging_8_s_m_s_2_extensions_2_permission_provider_8cs =
[
    [ "EleWise.ELMA.Messaging.SMS.Extensions.PermissionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_extensions_1_1_permission_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_extensions_1_1_permission_provider" ]
];