var bin_2_ele_wise_8_e_l_m_a_8_security_2_ele_wise_2_e_l_m_a_2_security_2_models_2_permission_model_8cs =
[
    [ "EleWise.ELMA.Security.Models.PermissionModel", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_models_1_1_permission_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_models_1_1_permission_model" ]
];