var bin_2_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_ele_wise_2_e_l_m_a_2_web_2_mvc_2_models_2_panels_2_client_info_panel_8cs =
[
    [ "EleWise.ELMA.Web.Mvc.Models.Panels.ClientInfoPanel", "class_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_models_1_1_panels_1_1_client_info_panel.html", "class_ele_wise_1_1_e_l_m_a_1_1_web_1_1_mvc_1_1_models_1_1_panels_1_1_client_info_panel" ]
];