var dir_05cabdac28bf36337a7c538a9199adcc =
[
    [ "Permissions", "dir_461fada4178e72e9d0d3bce74349ad8b.html", "dir_461fada4178e72e9d0d3bce74349ad8b" ],
    [ "Providers", "dir_94bebabc8029319080ba7b4a991e709e.html", "dir_94bebabc8029319080ba7b4a991e709e" ],
    [ "AlwaysAccessibleAttribute.cs", "_always_accessible_attribute_8cs.html", "_always_accessible_attribute_8cs" ],
    [ "Authorizer.cs", "_authorizer_8cs.html", "_authorizer_8cs" ],
    [ "CheckAccessContext.cs", "_check_access_context_8cs.html", "_check_access_context_8cs" ],
    [ "CreateUserParams.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_create_user_params_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_create_user_params_8cs" ],
    [ "CurrentUserWorkContext.cs", "_current_user_work_context_8cs.html", "_current_user_work_context_8cs" ],
    [ "DefaultMembershipValidationService.cs", "_default_membership_validation_service_8cs.html", "_default_membership_validation_service_8cs" ],
    [ "IAuthenticationService.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_authentication_service_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_authentication_service_8cs" ],
    [ "IAuthorizationService.cs", "_orchard_2_security_2_i_authorization_service_8cs.html", "_orchard_2_security_2_i_authorization_service_8cs" ],
    [ "IAuthorizationServiceEventHandler.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_authorization_service_event_handler_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_authorization_service_event_handler_8cs" ],
    [ "IAuthorizer.cs", "_i_authorizer_8cs.html", "_i_authorizer_8cs" ],
    [ "IEncryptionService.cs", "_i_encryption_service_8cs.html", "_i_encryption_service_8cs" ],
    [ "IMembershipService.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_membership_service_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_membership_service_8cs" ],
    [ "IMembershipSettings.cs", "_i_membership_settings_8cs.html", "_i_membership_settings_8cs" ],
    [ "IMembershipValidationService.cs", "_i_membership_validation_service_8cs.html", "_i_membership_validation_service_8cs" ],
    [ "ISslSettingsProvider.cs", "_i_ssl_settings_provider_8cs.html", "_i_ssl_settings_provider_8cs" ],
    [ "IUser.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_user_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_8_web_2_orchard_2_security_2_i_user_8cs" ],
    [ "NullMembershipService.cs", "_null_membership_service_8cs.html", "_null_membership_service_8cs" ],
    [ "OrchardSecurityException.cs", "_orchard_security_exception_8cs.html", "_orchard_security_exception_8cs" ],
    [ "SecurityFilter.cs", "_security_filter_8cs.html", "_security_filter_8cs" ],
    [ "StandardPermissions.cs", "_standard_permissions_8cs.html", "_standard_permissions_8cs" ]
];