var dir_6f6ae125b5d26de90d2d15232ff6e9f6 =
[
    [ "AuthenticationService.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_services_2_authentication_service_8cs.html", null ],
    [ "CommonPermissions.cs", "_common_permissions_8cs.html", "_common_permissions_8cs" ],
    [ "GroupDescriptor.cs", "_group_descriptor_8cs.html", "_group_descriptor_8cs" ],
    [ "IAuthenticatedSessionEventHandler.cs", "_i_authenticated_session_event_handler_8cs.html", "_i_authenticated_session_event_handler_8cs" ],
    [ "IAuthenticationKeyService.cs", "_i_authentication_key_service_8cs.html", "_i_authentication_key_service_8cs" ],
    [ "IAuthenticationService.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_services_2_i_authentication_service_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_services_2_i_authentication_service_8cs" ],
    [ "IAuthenticationServiceEventHandler.cs", "_i_authentication_service_event_handler_8cs.html", "_i_authentication_service_event_handler_8cs" ],
    [ "IAuthenticationServiceEventHandler2.cs", "_i_authentication_service_event_handler2_8cs.html", "_i_authentication_service_event_handler2_8cs" ],
    [ "IAuthenticationTokenService.cs", "_i_authentication_token_service_8cs.html", "_i_authentication_token_service_8cs" ],
    [ "ICommonHomePageProvider.cs", "_i_common_home_page_provider_8cs.html", "_i_common_home_page_provider_8cs" ],
    [ "IDynamicExpressionPermission.cs", "_i_dynamic_expression_permission_8cs.html", "_i_dynamic_expression_permission_8cs" ],
    [ "IInstanceExpressionPermission.cs", "_i_instance_expression_permission_8cs.html", "_i_instance_expression_permission_8cs" ],
    [ "IInstanceExpressionPermissionHolder.cs", "_i_instance_expression_permission_holder_8cs.html", "_i_instance_expression_permission_holder_8cs" ],
    [ "IInstanceSettingsPermission.cs", "_i_instance_settings_permission_8cs.html", "_i_instance_settings_permission_8cs" ],
    [ "IInstanceSettingsPermissionChild.cs", "_i_instance_settings_permission_child_8cs.html", "_i_instance_settings_permission_child_8cs" ],
    [ "IInstanceSettingsPermissionHolder.cs", "_i_instance_settings_permission_holder_8cs.html", "_i_instance_settings_permission_holder_8cs" ],
    [ "IJwtAuthTokenService.cs", "_i_jwt_auth_token_service_8cs.html", "_i_jwt_auth_token_service_8cs" ],
    [ "IMembershipServiceEventHandler.cs", "_i_membership_service_event_handler_8cs.html", "_i_membership_service_event_handler_8cs" ],
    [ "IMembershipServiceEventHandler2.cs", "_i_membership_service_event_handler2_8cs.html", "_i_membership_service_event_handler2_8cs" ],
    [ "IModuleAccessPermissionProvider.cs", "_i_module_access_permission_provider_8cs.html", "_i_module_access_permission_provider_8cs" ],
    [ "IModulePermissionsPageProvider.cs", "_i_module_permissions_page_provider_8cs.html", "_i_module_permissions_page_provider_8cs" ],
    [ "IModulePermissionsPortletProvider.cs", "_i_module_permissions_portlet_provider_8cs.html", "_i_module_permissions_portlet_provider_8cs" ],
    [ "IModuleSettingsPageProvider.cs", "_i_module_settings_page_provider_8cs.html", "_i_module_settings_page_provider_8cs" ],
    [ "InstanceSettingsPermissionHolder.cs", "_instance_settings_permission_holder_8cs.html", "_instance_settings_permission_holder_8cs" ],
    [ "IPermissionProvider.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_services_2_i_permission_provider_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_services_2_i_permission_provider_8cs" ],
    [ "IPropertyExpressionDescriptor.cs", "_i_property_expression_descriptor_8cs.html", "_i_property_expression_descriptor_8cs" ],
    [ "IPropertyExpressionDescriptorWithInstanceUid.cs", "_i_property_expression_descriptor_with_instance_uid_8cs.html", "_i_property_expression_descriptor_with_instance_uid_8cs" ],
    [ "ISecurityExpressionSetIdHolder.cs", "_i_security_expression_set_id_holder_8cs.html", "_i_security_expression_set_id_holder_8cs" ],
    [ "ISecuritySetIdHolder.cs", "_i_security_set_id_holder_8cs.html", "_i_security_set_id_holder_8cs" ],
    [ "ISspiService.cs", "_i_sspi_service_8cs.html", "_i_sspi_service_8cs" ],
    [ "ITrustedDeviceService.cs", "_i_trusted_device_service_8cs.html", "_i_trusted_device_service_8cs" ],
    [ "IUserInfoDTOService.cs", "_i_user_info_d_t_o_service_8cs.html", "_i_user_info_d_t_o_service_8cs" ],
    [ "UserValidationContext.cs", "_user_validation_context_8cs.html", "_user_validation_context_8cs" ]
];