var dir_f0719e2207449d03eda55160e4b585b2 =
[
    [ "__Resources_AcquaintanceListViewItem.cs", "_____resources___acquaintance_list_view_item_8cs.html", null ],
    [ "__Resources_ApprovementListViewItem.cs", "_____resources___approvement_list_view_item_8cs.html", null ],
    [ "__Resources_DocumentTaskContextViewItem.cs", "_____resources___document_task_context_view_item_8cs.html", null ],
    [ "__Resources_DocumentTaskParentTaskFormViewItem.cs", "_____resources___document_task_parent_task_form_view_item_8cs.html", null ],
    [ "__Resources_DocumentVersionApprovementStatusViewIt.cs", "_____resources___document_version_approvement_status_view_it_8cs.html", null ],
    [ "__Resources_DocumentVersionResolutionStatusViewIte.cs", "_____resources___document_version_resolution_status_view_ite_8cs.html", null ],
    [ "__Resources_DocumentVersionSignStatusViewItem.cs", "_____resources___document_version_sign_status_view_item_8cs.html", null ],
    [ "__Resources_RegistrationCardContextViewItem.cs", "_____resources___registration_card_context_view_item_8cs.html", null ],
    [ "__Resources_RegistrationCardDefaultContainerViewIt.cs", "_____resources___registration_card_default_container_view_it_8cs.html", null ],
    [ "__Resources_RegistrationCardPropertyCaptionViewIte.cs", "_____resources___registration_card_property_caption_view_ite_8cs.html", null ],
    [ "__Resources_RegistrationCardPropertyDescriptionVie.cs", "_____resources___registration_card_property_description_vie_8cs.html", null ],
    [ "__Resources_RegistrationCardPropertyValueViewItem.cs", "_____resources___registration_card_property_value_view_item_8cs.html", null ],
    [ "__Resources_RegistrationCardPropertyViewItem.cs", "_____resources___registration_card_property_view_item_8cs.html", null ],
    [ "__Resources_RegistrationCardRegistrationInfoViewIt.cs", "_____resources___registration_card_registration_info_view_it_8cs.html", null ],
    [ "__Resources_RegistrationCardRegNumberViewItem.cs", "_____resources___registration_card_reg_number_view_item_8cs.html", null ],
    [ "AcquaintanceListViewItem.cs", "_acquaintance_list_view_item_8cs.html", "_acquaintance_list_view_item_8cs" ],
    [ "ApprovementListViewItem.cs", "_approvement_list_view_item_8cs.html", "_approvement_list_view_item_8cs" ],
    [ "CreateRKKViewItem.cs", "_create_r_k_k_view_item_8cs.html", "_create_r_k_k_view_item_8cs" ],
    [ "DocumentAcquaintanceGridViewItem.cs", "_document_acquaintance_grid_view_item_8cs.html", "_document_acquaintance_grid_view_item_8cs" ],
    [ "DocumentApprovementGridViewItem.cs", "_document_approvement_grid_view_item_8cs.html", "_document_approvement_grid_view_item_8cs" ],
    [ "DocumentResolutionStatusViewItem.cs", "_document_resolution_status_view_item_8cs.html", "_document_resolution_status_view_item_8cs" ],
    [ "DocumentTaskContextViewItem.cs", "_document_task_context_view_item_8cs.html", "_document_task_context_view_item_8cs" ],
    [ "DocumentTaskParentTaskFormViewItem.cs", "_document_task_parent_task_form_view_item_8cs.html", "_document_task_parent_task_form_view_item_8cs" ],
    [ "DocumentVersionApprovementStatusViewItem.cs", "_document_version_approvement_status_view_item_8cs.html", "_document_version_approvement_status_view_item_8cs" ],
    [ "DocumentVersionSignStatusViewItem.cs", "_document_version_sign_status_view_item_8cs.html", "_document_version_sign_status_view_item_8cs" ],
    [ "EditRKKViewItem.cs", "_edit_r_k_k_view_item_8cs.html", "_edit_r_k_k_view_item_8cs" ],
    [ "IRegistrationCardPropertyViewItem.cs", "_i_registration_card_property_view_item_8cs.html", "_i_registration_card_property_view_item_8cs" ],
    [ "RegistrationCardContextViewItem.cs", "_registration_card_context_view_item_8cs.html", "_registration_card_context_view_item_8cs" ],
    [ "RegistrationCardDefaultContainerViewItem.cs", "_registration_card_default_container_view_item_8cs.html", "_registration_card_default_container_view_item_8cs" ],
    [ "RegistrationCardPropertyCaptionViewItem.cs", "_registration_card_property_caption_view_item_8cs.html", "_registration_card_property_caption_view_item_8cs" ],
    [ "RegistrationCardPropertyDescriptionViewItem.cs", "_registration_card_property_description_view_item_8cs.html", "_registration_card_property_description_view_item_8cs" ],
    [ "RegistrationCardPropertyValueViewItem.cs", "_registration_card_property_value_view_item_8cs.html", "_registration_card_property_value_view_item_8cs" ],
    [ "RegistrationCardPropertyViewItem.cs", "_registration_card_property_view_item_8cs.html", "_registration_card_property_view_item_8cs" ],
    [ "RegistrationCardRegistrationInfoViewItem.cs", "_registration_card_registration_info_view_item_8cs.html", "_registration_card_registration_info_view_item_8cs" ],
    [ "RegistrationCardRegNumberViewItem.cs", "_registration_card_reg_number_view_item_8cs.html", "_registration_card_reg_number_view_item_8cs" ]
];