var dir_9a4f368c004b2645485d962951b36f6a =
[
    [ "_NamespaceInfo.cs", "_ele_wise_8_e_l_m_a_8_integration_external_data_2_integration_external_data_2_models_2___namespace_info_8cs.html", null ],
    [ "BookExternalData`1.cs", "_book_external_data_0l1_8cs.html", "_book_external_data_0l1_8cs" ],
    [ "BookExternalDataDynamic`1.cs", "_book_external_data_dynamic_0l1_8cs.html", "_book_external_data_dynamic_0l1_8cs" ],
    [ "BookExternalDataFilter.cs", "_book_external_data_filter_8cs.html", "_book_external_data_filter_8cs" ],
    [ "DependencyNode.cs", "_dependency_node_8cs.html", "_dependency_node_8cs" ],
    [ "DynamicDebugView.cs", "_ele_wise_8_e_l_m_a_8_integration_external_data_2_integration_external_data_2_models_2_dynamic_debug_view_8cs.html", null ],
    [ "ExternalDescription.cs", "_external_description_8cs.html", "_external_description_8cs" ],
    [ "ExternalIdentifiedClass.cs", "_external_identified_class_8cs.html", "_external_identified_class_8cs" ],
    [ "ExternalNameClass.cs", "_external_name_class_8cs.html", "_external_name_class_8cs" ],
    [ "IBookExternalData.cs", "_i_book_external_data_8cs.html", "_i_book_external_data_8cs" ],
    [ "IBookExternalData`1.cs", "_i_book_external_data_0l1_8cs.html", "_i_book_external_data_0l1_8cs" ],
    [ "IBookExternalDataInternal.cs", "_i_book_external_data_internal_8cs.html", null ],
    [ "IBookExternalDataInternal`1.cs", "_i_book_external_data_internal_0l1_8cs.html", null ],
    [ "IExternalDescription.cs", "_i_external_description_8cs.html", "_i_external_description_8cs" ],
    [ "IExternalIdentifiedClass.cs", "_i_external_identified_class_8cs.html", "_i_external_identified_class_8cs" ],
    [ "IExternalNameClass.cs", "_i_external_name_class_8cs.html", "_i_external_name_class_8cs" ],
    [ "IPersistentGenericSet.cs", "_i_persistent_generic_set_8cs.html", null ],
    [ "ISetWrapper`1.cs", "_i_set_wrapper_0l1_8cs.html", null ],
    [ "ITablePartExternalData.cs", "_i_table_part_external_data_8cs.html", null ],
    [ "ITablePartIdentifierExternalData`1.cs", "_i_table_part_identifier_external_data_0l1_8cs.html", null ],
    [ "PersistentGenericSet`1.cs", "_persistent_generic_set_0l1_8cs.html", null ],
    [ "TablePartExternalData.cs", "_table_part_external_data_8cs.html", "_table_part_external_data_8cs" ],
    [ "TablePartExternalDataDynamic.cs", "_table_part_external_data_dynamic_8cs.html", "_table_part_external_data_dynamic_8cs" ],
    [ "TablePartIdentifierExternalData`1.cs", "_table_part_identifier_external_data_0l1_8cs.html", "_table_part_identifier_external_data_0l1_8cs" ],
    [ "TablePartIdentifierExternalDataDynamic`1.cs", "_table_part_identifier_external_data_dynamic_0l1_8cs.html", "_table_part_identifier_external_data_dynamic_0l1_8cs" ],
    [ "TableRefModel.cs", "_table_ref_model_8cs.html", "_table_ref_model_8cs" ]
];