var dir_7843a3650a6dccb9763fdef19c4d59b2 =
[
    [ "Components", "dir_5ee0481ecd868448a32b65a65d474e34.html", "dir_5ee0481ecd868448a32b65a65d474e34" ],
    [ "Cryptography", "dir_dcbcf041a28a20f034027556aaf18370.html", "dir_dcbcf041a28a20f034027556aaf18370" ],
    [ "ExtensionPoints", "dir_d112568a86c3546a43956e3fce2f53a3.html", "dir_d112568a86c3546a43956e3fce2f53a3" ],
    [ "Services", "dir_6f6ae125b5d26de90d2d15232ff6e9f6.html", "dir_6f6ae125b5d26de90d2d15232ff6e9f6" ],
    [ "Settings", "dir_5a421f206803a714231c44a2415d597d.html", "dir_5a421f206803a714231c44a2415d597d" ],
    [ "AuthenticatedSessionFilter.cs", "_authenticated_session_filter_8cs.html", "_authenticated_session_filter_8cs" ],
    [ "AuthenticatedSessionInfo.cs", "_authenticated_session_info_8cs.html", "_authenticated_session_info_8cs" ],
    [ "AuthenticatedSessionStatus.cs", "_authenticated_session_status_8cs.html", "_authenticated_session_status_8cs" ],
    [ "AuthInfoContainer.cs", "_auth_info_container_8cs.html", "_auth_info_container_8cs" ],
    [ "CreateUserParams.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_create_user_params_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_create_user_params_8cs" ],
    [ "IEntityInstanceDefaultPermission.cs", "_i_entity_instance_default_permission_8cs.html", "_i_entity_instance_default_permission_8cs" ],
    [ "IGlobalPermissionsDelegate.cs", "_i_global_permissions_delegate_8cs.html", "_i_global_permissions_delegate_8cs" ],
    [ "IInstancePermissionRoleTypeProvider.cs", "_i_instance_permission_role_type_provider_8cs.html", "_i_instance_permission_role_type_provider_8cs" ],
    [ "IInstancePermissionTypeRoleService.cs", "_i_instance_permission_type_role_service_8cs.html", "_i_instance_permission_type_role_service_8cs" ],
    [ "IMembershipService.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_i_membership_service_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_i_membership_service_8cs" ],
    [ "IPermissionManagmentService.cs", "_i_permission_managment_service_8cs.html", "_i_permission_managment_service_8cs" ],
    [ "IPermissionRoleTypeProvider.cs", "_i_permission_role_type_provider_8cs.html", "_i_permission_role_type_provider_8cs" ],
    [ "IPermissionsDelegate.cs", "_i_permissions_delegate_8cs.html", "_i_permissions_delegate_8cs" ],
    [ "IPermissionTarget.cs", "_i_permission_target_8cs.html", "_i_permission_target_8cs" ],
    [ "IPermissionTypeRoleService.cs", "_i_permission_type_role_service_8cs.html", "_i_permission_type_role_service_8cs" ],
    [ "IPropertyPermissionService.cs", "_i_property_permission_service_8cs.html", "_i_property_permission_service_8cs" ],
    [ "ISecurityService.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_i_security_service_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_i_security_service_8cs" ],
    [ "ISecurityServiceAsync.cs", "_i_security_service_async_8cs.html", "_i_security_service_async_8cs" ],
    [ "IUser.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_i_user_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_i_user_8cs" ],
    [ "IUserAuthenticationChecker.cs", "_i_user_authentication_checker_8cs.html", "_i_user_authentication_checker_8cs" ],
    [ "JwtTokenContainer.cs", "_jwt_token_container_8cs.html", "_jwt_token_container_8cs" ],
    [ "MembershipSettings.cs", "_membership_settings_8cs.html", "_membership_settings_8cs" ],
    [ "Permission.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_permission_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_permission_8cs" ],
    [ "PermissionBuilder.cs", "_permission_builder_8cs.html", "_permission_builder_8cs" ],
    [ "PermissionRoleType.cs", "_permission_role_type_8cs.html", "_permission_role_type_8cs" ],
    [ "PermissionRoleTypeStereotype.cs", "_permission_role_type_stereotype_8cs.html", "_permission_role_type_stereotype_8cs" ],
    [ "PermissionStereotype.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_permission_stereotype_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_security_2_permission_stereotype_8cs" ],
    [ "PermissionType.cs", "_permission_type_8cs.html", "_permission_type_8cs" ],
    [ "PropertyMetadataReference.cs", "_property_metadata_reference_8cs.html", "_property_metadata_reference_8cs" ],
    [ "PropertyPermissionType.cs", "_property_permission_type_8cs.html", "_property_permission_type_8cs" ]
];