var dir_5ae104617f51b32c0427288f44a90922 =
[
    [ "Links", "dir_bf5db9d13d5862925fa624816386db93.html", "dir_bf5db9d13d5862925fa624816386db93" ],
    [ "SignDocumentVersion", "dir_8b9301fc06b987c815cd3966721b2168.html", "dir_8b9301fc06b987c815cd3966721b2168" ],
    [ "ConvertRegistrationCardsInfoExtensions.cs", "_convert_registration_cards_info_extensions_8cs.html", null ],
    [ "CreateSubtaskDocumentFieldVisibility.cs", "_create_subtask_document_field_visibility_8cs.html", "_create_subtask_document_field_visibility_8cs" ],
    [ "DepositoryWebExtensions.cs", "_depository_web_extensions_8cs.html", null ],
    [ "DigitalSignatureTemplateSettings.cs", "_digital_signature_template_settings_8cs.html", "_digital_signature_template_settings_8cs" ],
    [ "DocflowScriptsSourceProvider.cs", "_docflow_scripts_source_provider_8cs.html", "_docflow_scripts_source_provider_8cs" ],
    [ "DocumentExtensions.cs", "_document_extensions_8cs.html", null ],
    [ "DocumentStartableByRoute.cs", "_document_startable_by_route_8cs.html", "_document_startable_by_route_8cs" ],
    [ "FilterModelExtension.cs", "_filter_model_extension_8cs.html", "_filter_model_extension_8cs" ],
    [ "HtmlExtensions.cs", "_ele_wise_8_e_l_m_a_8_documents_8_docflow_8_web_2_extensions_2_html_extensions_8cs.html", null ],
    [ "ICertificateSelectionOnMultipleSigningWeb.cs", "_i_certificate_selection_on_multiple_signing_web_8cs.html", "_i_certificate_selection_on_multiple_signing_web_8cs" ],
    [ "ICryptoProviderWeb.cs", "_i_crypto_provider_web_8cs.html", "_i_crypto_provider_web_8cs" ],
    [ "IDocumentActionAfterRegistration.cs", "_i_document_action_after_registration_8cs.html", "_i_document_action_after_registration_8cs" ],
    [ "ModuleSettingsNomenclature.cs", "_ele_wise_8_e_l_m_a_8_documents_8_docflow_8_web_2_extensions_2_module_settings_nomenclature_8cs.html", "_ele_wise_8_e_l_m_a_8_documents_8_docflow_8_web_2_extensions_2_module_settings_nomenclature_8cs" ],
    [ "NomenclatureExtensions.cs", "_nomenclature_extensions_8cs.html", null ],
    [ "OfficePermissionSettings.cs", "_office_permission_settings_8cs.html", "_office_permission_settings_8cs" ],
    [ "RegistrationPlacePermissionSettings.cs", "_registration_place_permission_settings_8cs.html", "_registration_place_permission_settings_8cs" ],
    [ "RegistrationVariantSettings.cs", "_registration_variant_settings_8cs.html", "_registration_variant_settings_8cs" ],
    [ "RouteExtensions.cs", "_route_extensions_8cs.html", null ],
    [ "SettingsQuickLinksRegistration.cs", "_settings_quick_links_registration_8cs.html", "_settings_quick_links_registration_8cs" ],
    [ "TaskExtension.cs", "_ele_wise_8_e_l_m_a_8_documents_8_docflow_8_web_2_extensions_2_task_extension_8cs.html", null ]
];