var dir_1aaf0e6f992bb0cf3306e1c6270ae0f4 =
[
    [ "AcquireContext`1.cs", "_acquire_context_0l1_8cs.html", "_acquire_context_0l1_8cs" ],
    [ "Cache`2.cs", "_cache_0l2_8cs.html", "_cache_0l2_8cs" ],
    [ "CacheManagerExtensions.cs", "_cache_manager_extensions_8cs.html", null ],
    [ "CacheModule.cs", "_cache_module_8cs.html", "_cache_module_8cs" ],
    [ "DefaultAsyncTokenProvider.cs", "_default_async_token_provider_8cs.html", "_default_async_token_provider_8cs" ],
    [ "DefaultCacheContextAccessor.cs", "_default_cache_context_accessor_8cs.html", "_default_cache_context_accessor_8cs" ],
    [ "DefaultCacheHolder.cs", "_default_cache_holder_8cs.html", "_default_cache_holder_8cs" ],
    [ "DefaultCacheManager.cs", "_default_cache_manager_8cs.html", "_default_cache_manager_8cs" ],
    [ "DefaultParallelCacheContext.cs", "_default_parallel_cache_context_8cs.html", "_default_parallel_cache_context_8cs" ],
    [ "IAcquireContext.cs", "_i_acquire_context_8cs.html", "_i_acquire_context_8cs" ],
    [ "IAsyncTokenProvider.cs", "_i_async_token_provider_8cs.html", "_i_async_token_provider_8cs" ],
    [ "ICache`2.cs", "_i_cache_0l2_8cs.html", "_i_cache_0l2_8cs" ],
    [ "ICacheContextAccessor.cs", "_i_cache_context_accessor_8cs.html", "_i_cache_context_accessor_8cs" ],
    [ "ICacheHolder.cs", "_i_cache_holder_8cs.html", "_i_cache_holder_8cs" ],
    [ "ICacheManager.cs", "_i_cache_manager_8cs.html", "_i_cache_manager_8cs" ],
    [ "IParallelCacheContext.cs", "_i_parallel_cache_context_8cs.html", "_i_parallel_cache_context_8cs" ],
    [ "ISignals.cs", "_i_signals_8cs.html", "_i_signals_8cs" ],
    [ "ITask`1.cs", "_i_task_0l1_8cs.html", "_i_task_0l1_8cs" ],
    [ "IVolatileProvider.cs", "_i_volatile_provider_8cs.html", "_i_volatile_provider_8cs" ],
    [ "IVolatileToken.cs", "_i_volatile_token_8cs.html", "_i_volatile_token_8cs" ],
    [ "Signals.cs", "_signals_8cs.html", "_signals_8cs" ],
    [ "SimpleAcquireContext.cs", "_simple_acquire_context_8cs.html", "_simple_acquire_context_8cs" ],
    [ "Weak`1.cs", "_weak_0l1_8cs.html", "_weak_0l1_8cs" ]
];