var dir_8beeedf000a9fc352af3454b9bbc4d78 =
[
    [ "CustomWorkflowInstanceColumns.cs", "_custom_workflow_instance_columns_8cs.html", null ],
    [ "DocumentationSwitcher.cs", "_documentation_switcher_8cs.html", "_documentation_switcher_8cs" ],
    [ "FilterForSettingsPopupGridStateProvider.cs", "_filter_for_settings_popup_grid_state_provider_8cs.html", "_filter_for_settings_popup_grid_state_provider_8cs" ],
    [ "FilterFullMonitorMenuProviderExtension.cs", "_filter_full_monitor_menu_provider_extension_8cs.html", "_filter_full_monitor_menu_provider_extension_8cs" ],
    [ "FilterImprovementMenuProviderExtension.cs", "_filter_improvement_menu_provider_extension_8cs.html", "_filter_improvement_menu_provider_extension_8cs" ],
    [ "FilterMonitorMenuProviderExtension.cs", "_filter_monitor_menu_provider_extension_8cs.html", "_filter_monitor_menu_provider_extension_8cs" ],
    [ "FilterMyProcessMenuProviderExtension.cs", "_filter_my_process_menu_provider_extension_8cs.html", "_filter_my_process_menu_provider_extension_8cs" ],
    [ "ImprovementFilterPropertyVisibility.cs", "_improvement_filter_property_visibility_8cs.html", "_improvement_filter_property_visibility_8cs" ],
    [ "ProcessDocumentationLinkProvider.cs", "_process_documentation_link_provider_8cs.html", "_process_documentation_link_provider_8cs" ],
    [ "ProcessPermissionsPageProvider.cs", "_process_permissions_page_provider_8cs.html", "_process_permissions_page_provider_8cs" ],
    [ "ReplacementWorkflowResponsibleBlockUserActionExtension.cs", "_replacement_workflow_responsible_block_user_action_extension_8cs.html", null ],
    [ "SecurityDefaultHomePagePortletProvider.cs", "_ele_wise_8_e_l_m_a_8_workflow_8_processes_8_web_2_components_2_security_default_home_page_portlet_provider_8cs.html", null ],
    [ "WorkfloInstanceCommentAttachmentHistoryPartMerge.cs", "_workflo_instance_comment_attachment_history_part_merge_8cs.html", null ],
    [ "WorkfloInstanceCommentHistoryPartProvider.cs", "_workflo_instance_comment_history_part_provider_8cs.html", "_workflo_instance_comment_history_part_provider_8cs" ],
    [ "WorkflowInstanceAttachmentHistoryPartProvider.cs", "_workflow_instance_attachment_history_part_provider_8cs.html", null ],
    [ "WorkflowInstanceAutoCompleteExtension.cs", "_workflow_instance_auto_complete_extension_8cs.html", "_workflow_instance_auto_complete_extension_8cs" ],
    [ "WorkflowInstanceBaseFilterCreator.cs", "_workflow_instance_base_filter_creator_8cs.html", "_workflow_instance_base_filter_creator_8cs" ],
    [ "WorkflowinstanceCustomSortable.cs", "_workflowinstance_custom_sortable_8cs.html", "_workflowinstance_custom_sortable_8cs" ],
    [ "WorkflowInstanceFilterCreator.cs", "_workflow_instance_filter_creator_8cs.html", "_workflow_instance_filter_creator_8cs" ],
    [ "WorkflowInstanceFilterProcessHeaderPropertyExtension.cs", "_workflow_instance_filter_process_header_property_extension_8cs.html", "_workflow_instance_filter_process_header_property_extension_8cs" ],
    [ "WorkflowInstanceFilterPropertyTypeResolver.cs", "_workflow_instance_filter_property_type_resolver_8cs.html", "_workflow_instance_filter_property_type_resolver_8cs" ],
    [ "WorkflowInstanceLink.cs", "_components_2_workflow_instance_link_8cs.html", "_components_2_workflow_instance_link_8cs" ],
    [ "WorkflowInstanceSelectableGridProvider.cs", "_workflow_instance_selectable_grid_provider_8cs.html", "_workflow_instance_selectable_grid_provider_8cs" ],
    [ "WorkflowMigrationSwitcher.cs", "_workflow_migration_switcher_8cs.html", "_workflow_migration_switcher_8cs" ],
    [ "WorkflowProcessesLessSourceProvider.cs", "_workflow_processes_less_source_provider_8cs.html", null ],
    [ "WorkflowProcessHeaderImprovementFilterPropertyEditor.cs", "_workflow_process_header_improvement_filter_property_editor_8cs.html", "_workflow_process_header_improvement_filter_property_editor_8cs" ],
    [ "WorkflowProcessHeaderMonitorFilterPropertyEditor.cs", "_workflow_process_header_monitor_filter_property_editor_8cs.html", "_workflow_process_header_monitor_filter_property_editor_8cs" ],
    [ "WorkflowQueueSwitcher.cs", "_workflow_queue_switcher_8cs.html", "_workflow_queue_switcher_8cs" ],
    [ "WorkflowRoleTypeFilterPropertyEditor.cs", "_workflow_role_type_filter_property_editor_8cs.html", "_workflow_role_type_filter_property_editor_8cs" ],
    [ "WorkflowTaskExecuteZone.cs", "_workflow_task_execute_zone_8cs.html", "_workflow_task_execute_zone_8cs" ]
];