var dir_6171c0b5e3502a4b6562b11fc097ed8e =
[
    [ "iPadLicensedModuleAccessGroup.cs", "_ele_wise_8_e_l_m_a_8i_pad_2_ele_wise_2_e_l_m_a_2i_pad_2_security_2i_pad_licensed_module_access_group_8cs.html", "_ele_wise_8_e_l_m_a_8i_pad_2_ele_wise_2_e_l_m_a_2i_pad_2_security_2i_pad_licensed_module_access_group_8cs" ],
    [ "PermissionsProvider.cs", "_ele_wise_8_e_l_m_a_8i_pad_2_ele_wise_2_e_l_m_a_2i_pad_2_security_2_permissions_provider_8cs.html", "_ele_wise_8_e_l_m_a_8i_pad_2_ele_wise_2_e_l_m_a_2i_pad_2_security_2_permissions_provider_8cs" ],
    [ "PublicApplicationAuthValidator.cs", "_ele_wise_8_e_l_m_a_8i_pad_2_ele_wise_2_e_l_m_a_2i_pad_2_security_2_public_application_auth_validator_8cs.html", null ]
];