var dir_13259cc41f39bc8e6be048b3da2bcc3e =
[
    [ "DTO", "dir_10f93338c45d8b68f2c2d5a6fd9cd73b.html", "dir_10f93338c45d8b68f2c2d5a6fd9cd73b" ],
    [ "Enum", "dir_0fa27c96913af64d58a622b288ec5b0e.html", "dir_0fa27c96913af64d58a622b288ec5b0e" ],
    [ "Managers", "dir_7b76173a395e68e022699331ff46e0fa.html", "dir_7b76173a395e68e022699331ff46e0fa" ],
    [ "Models", "dir_d7e54c88ae2ad53dfe90ac3a110ce6f5.html", "dir_d7e54c88ae2ad53dfe90ac3a110ce6f5" ],
    [ "Services", "dir_906903daca4f26bdd6a7acb149789199.html", "dir_906903daca4f26bdd6a7acb149789199" ],
    [ "BpmAppBAItem.cs", "_bpm_app_b_a_item_8cs.html", "_bpm_app_b_a_item_8cs" ],
    [ "BPMAppFakeManifest.cs", "_b_p_m_app_fake_manifest_8cs.html", "_b_p_m_app_fake_manifest_8cs" ],
    [ "BPMAppManifest.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_b_p_m_apps_2_bpm_app_manifest_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_b_p_m_apps_2_bpm_app_manifest_8cs" ],
    [ "BPMAppManifestChapter.cs", "_b_p_m_app_manifest_chapter_8cs.html", "_b_p_m_app_manifest_chapter_8cs" ],
    [ "BPMAppManifestFakeChapter.cs", "_b_p_m_app_manifest_fake_chapter_8cs.html", "_b_p_m_app_manifest_fake_chapter_8cs" ],
    [ "BPMAppManifestFakeItem.cs", "_b_p_m_app_manifest_fake_item_8cs.html", "_b_p_m_app_manifest_fake_item_8cs" ],
    [ "BPMAppManifestFlag.cs", "_b_p_m_app_manifest_flag_8cs.html", "_b_p_m_app_manifest_flag_8cs" ],
    [ "BPMAppManifestItem.cs", "_b_p_m_app_manifest_item_8cs.html", "_b_p_m_app_manifest_item_8cs" ],
    [ "BPMAppManifestSerializationHelper.cs", "_b_p_m_app_manifest_serialization_helper_8cs.html", null ],
    [ "BpmAppsBAChapter.cs", "_bpm_apps_b_a_chapter_8cs.html", "_bpm_apps_b_a_chapter_8cs" ],
    [ "ComponentBAChapter.cs", "_component_b_a_chapter_8cs.html", "_component_b_a_chapter_8cs" ],
    [ "ComponentBAItem.cs", "_component_b_a_item_8cs.html", "_component_b_a_item_8cs" ],
    [ "DataClassBAItem.cs", "_data_class_b_a_item_8cs.html", "_data_class_b_a_item_8cs" ],
    [ "EntityBAItem.cs", "_entity_b_a_item_8cs.html", "_entity_b_a_item_8cs" ],
    [ "EnumBAItem.cs", "_enum_b_a_item_8cs.html", "_enum_b_a_item_8cs" ],
    [ "FilesBAChapter.cs", "_files_b_a_chapter_8cs.html", "_files_b_a_chapter_8cs" ],
    [ "FunctionBAChapter.cs", "_function_b_a_chapter_8cs.html", "_function_b_a_chapter_8cs" ],
    [ "FunctionBAItem.cs", "_function_b_a_item_8cs.html", "_function_b_a_item_8cs" ],
    [ "ObjectsBAChapter.cs", "_objects_b_a_chapter_8cs.html", "_objects_b_a_chapter_8cs" ],
    [ "PackageBAItem.cs", "_package_b_a_item_8cs.html", "_package_b_a_item_8cs" ],
    [ "PackagesBAChapter.cs", "_packages_b_a_chapter_8cs.html", "_packages_b_a_chapter_8cs" ],
    [ "RazorViewBAItem.cs", "_razor_view_b_a_item_8cs.html", "_razor_view_b_a_item_8cs" ],
    [ "RazorViewsBAChapter.cs", "_razor_views_b_a_chapter_8cs.html", "_razor_views_b_a_chapter_8cs" ],
    [ "TranslateBAItem.cs", "_translate_b_a_item_8cs.html", "_translate_b_a_item_8cs" ],
    [ "TranslatesBAChapter.cs", "_translates_b_a_chapter_8cs.html", "_translates_b_a_chapter_8cs" ]
];