var dir_df5b9026e44a63d5033c3b1b37a5d4a7 =
[
    [ "AcquaintanceStatusEnum.cs", "_acquaintance_status_enum_8cs.html", "_acquaintance_status_enum_8cs" ],
    [ "ApprovalStatusEnum.cs", "_ele_wise_8_e_l_m_a_8_documents_8_docflow_2_ele_wise_2_e_l_m_a_2_documents_2_a_p_i_2_models_2_approval_status_enum_8cs.html", "_ele_wise_8_e_l_m_a_8_documents_8_docflow_2_ele_wise_2_e_l_m_a_2_documents_2_a_p_i_2_models_2_approval_status_enum_8cs" ],
    [ "ApprovementResultWCF.cs", "_approvement_result_w_c_f_8cs.html", "_approvement_result_w_c_f_8cs" ],
    [ "CreateDocumentOutlookModel.cs", "_create_document_outlook_model_8cs.html", "_create_document_outlook_model_8cs" ],
    [ "CreateTaskOutlookModel.cs", "_create_task_outlook_model_8cs.html", "_create_task_outlook_model_8cs" ],
    [ "DigitalSignatureWCF.cs", "_digital_signature_w_c_f_8cs.html", "_digital_signature_w_c_f_8cs" ],
    [ "DocumentAcquaintanceTaskPackage.cs", "_document_acquaintance_task_package_8cs.html", "_document_acquaintance_task_package_8cs" ],
    [ "DocumentAcquaintanceTaskWCF.cs", "_document_acquaintance_task_w_c_f_8cs.html", "_document_acquaintance_task_w_c_f_8cs" ],
    [ "DocumentApprovementTaskPackage.cs", "_document_approvement_task_package_8cs.html", "_document_approvement_task_package_8cs" ],
    [ "DocumentApprovementTaskWCF.cs", "_document_approvement_task_w_c_f_8cs.html", "_document_approvement_task_w_c_f_8cs" ],
    [ "DocumentAssignUserWCF.cs", "_document_assign_user_w_c_f_8cs.html", "_document_assign_user_w_c_f_8cs" ],
    [ "DocumentTaskItemWCF.cs", "_document_task_item_w_c_f_8cs.html", "_document_task_item_w_c_f_8cs" ],
    [ "DocumentTaskWCF.cs", "_document_task_w_c_f_8cs.html", "_document_task_w_c_f_8cs" ],
    [ "DocumentType.cs", "_document_type_8cs.html", "_document_type_8cs" ],
    [ "DocumentTypeOutlookModel.cs", "_document_type_outlook_model_8cs.html", "_document_type_outlook_model_8cs" ],
    [ "NotSupportedDocumentTaskPackage.cs", "_not_supported_document_task_package_8cs.html", "_not_supported_document_task_package_8cs" ],
    [ "NotSupportedDocumentTaskWCF.cs", "_not_supported_document_task_w_c_f_8cs.html", "_not_supported_document_task_w_c_f_8cs" ],
    [ "RegisterDocumentOutlookModel.cs", "_register_document_outlook_model_8cs.html", "_register_document_outlook_model_8cs" ],
    [ "ResolutionTaskPackage.cs", "_resolution_task_package_8cs.html", "_resolution_task_package_8cs" ],
    [ "ResolutionTaskTypeEnum.cs", "_resolution_task_type_enum_8cs.html", "_resolution_task_type_enum_8cs" ],
    [ "ResolutionTaskWCF.cs", "_resolution_task_w_c_f_8cs.html", "_resolution_task_w_c_f_8cs" ],
    [ "SignatureGeneratingTypeWCF.cs", "_signature_generating_type_w_c_f_8cs.html", "_signature_generating_type_w_c_f_8cs" ],
    [ "SignDocumentTaskPackage.cs", "_sign_document_task_package_8cs.html", "_sign_document_task_package_8cs" ],
    [ "SignDocumentTaskWCF.cs", "_sign_document_task_w_c_f_8cs.html", "_sign_document_task_w_c_f_8cs" ],
    [ "SignOptionsWCF.cs", "_sign_options_w_c_f_8cs.html", "_sign_options_w_c_f_8cs" ],
    [ "TextForSignResultWCF.cs", "_text_for_sign_result_w_c_f_8cs.html", "_text_for_sign_result_w_c_f_8cs" ],
    [ "VerifyDataStructWCF.cs", "_verify_data_struct_w_c_f_8cs.html", "_verify_data_struct_w_c_f_8cs" ]
];