var dir_eb6c27c1d52cf45a2a849f3c8952d5c5 =
[
    [ "HistoryOrder", "dir_9e055aaeca16da4425bce93093e24e81.html", "dir_9e055aaeca16da4425bce93093e24e81" ],
    [ "BaseHistoryIdentifier.cs", "_base_history_identifier_8cs.html", null ],
    [ "BlobStore.cs", "_blob_store_8cs.html", "_blob_store_8cs" ],
    [ "BlobStoreConfigurationService.cs", "_blob_store_configuration_service_8cs.html", "_blob_store_configuration_service_8cs" ],
    [ "CatalogProfileUpdaterService.cs", "_catalog_profile_updater_service_8cs.html", null ],
    [ "CatalogPropertyPermissionAdapter.cs", "_catalog_property_permission_adapter_8cs.html", "_catalog_property_permission_adapter_8cs" ],
    [ "DuplicateService.cs", "_duplicate_service_8cs.html", "_duplicate_service_8cs" ],
    [ "EntityHistoryRestrictionService.cs", "_entity_history_restriction_service_8cs.html", null ],
    [ "EntityModelHistoryService.cs", "_entity_model_history_service_8cs.html", "_entity_model_history_service_8cs" ],
    [ "EntityTaskModelDraftService.cs", "_entity_task_model_draft_service_8cs.html", null ],
    [ "HistoryIdParams.cs", "_history_id_params_8cs.html", "_history_id_params_8cs" ],
    [ "ICatalogProfileUpdaterService.cs", "_i_catalog_profile_updater_service_8cs.html", "_i_catalog_profile_updater_service_8cs" ],
    [ "IDuplicateService.cs", "_i_duplicate_service_8cs.html", "_i_duplicate_service_8cs" ],
    [ "IEntityHistoryRestrictionService.cs", "_i_entity_history_restriction_service_8cs.html", "_i_entity_history_restriction_service_8cs" ],
    [ "IEntityModelHistoryRestrictionService.cs", "_i_entity_model_history_restriction_service_8cs.html", "_i_entity_model_history_restriction_service_8cs" ],
    [ "IEntityTaskModelDraftExtensionPoint.cs", "_i_entity_task_model_draft_extension_point_8cs.html", "_i_entity_task_model_draft_extension_point_8cs" ],
    [ "IEntityTaskModelDraftService.cs", "_i_entity_task_model_draft_service_8cs.html", "_i_entity_task_model_draft_service_8cs" ],
    [ "IHistoryIdentifierExtensionPoint.cs", "_i_history_identifier_extension_point_8cs.html", "_i_history_identifier_extension_point_8cs" ],
    [ "IHistoryIdParams.cs", "_i_history_id_params_8cs.html", "_i_history_id_params_8cs" ],
    [ "IHistoryOrder.cs", "_i_history_order_8cs.html", "_i_history_order_8cs" ],
    [ "IObjectAttachmentsArchiveService.cs", "_i_object_attachments_archive_service_8cs.html", "_i_object_attachments_archive_service_8cs" ],
    [ "IObjectAttachmentsArchiveServiceCheckFileExt.cs", "_i_object_attachments_archive_service_check_file_ext_8cs.html", "_i_object_attachments_archive_service_check_file_ext_8cs" ],
    [ "IObjectAttachmentsArchiveServiceExt.cs", "_i_object_attachments_archive_service_ext_8cs.html", "_i_object_attachments_archive_service_ext_8cs" ],
    [ "IScheduledRestartService.cs", "_i_scheduled_restart_service_8cs.html", "_i_scheduled_restart_service_8cs" ],
    [ "IServerRestartMessageService.cs", "_i_server_restart_message_service_8cs.html", "_i_server_restart_message_service_8cs" ],
    [ "IWatchEntityService.cs", "_i_watch_entity_service_8cs.html", "_i_watch_entity_service_8cs" ],
    [ "ObjectAttachmentsArchiveService.cs", "_object_attachments_archive_service_8cs.html", null ],
    [ "ScheduledRestartService.cs", "_scheduled_restart_service_8cs.html", null ],
    [ "ServerRestartService.cs", "_server_restart_service_8cs.html", null ],
    [ "WatchEntityService.cs", "_watch_entity_service_8cs.html", "_watch_entity_service_8cs" ],
    [ "WatchKey.cs", "_watch_key_8cs.html", "_watch_key_8cs" ]
];