var dir_ad3920b86229890fa86888c402edeedf =
[
    [ "DataProtectionCryptographyService.cs", "_data_protection_cryptography_service_8cs.html", "_data_protection_cryptography_service_8cs" ],
    [ "FileCatalogModuleEnumerator.cs", "_file_catalog_module_enumerator_8cs.html", "_file_catalog_module_enumerator_8cs" ],
    [ "FileStatePersistenceService.cs", "_file_state_persistence_service_8cs.html", "_file_state_persistence_service_8cs" ],
    [ "IAuthenticationService.cs", "_ele_wise_8_e_l_m_a_8_c_a_b_2_services_2_i_authentication_service_8cs.html", "_ele_wise_8_e_l_m_a_8_c_a_b_2_services_2_i_authentication_service_8cs" ],
    [ "ICryptographyService.cs", "_i_cryptography_service_8cs.html", "_i_cryptography_service_8cs" ],
    [ "IModuleEnumerator.cs", "_i_module_enumerator_8cs.html", "_i_module_enumerator_8cs" ],
    [ "IModuleLoaderService.cs", "_i_module_loader_service_8cs.html", "_i_module_loader_service_8cs" ],
    [ "IsolatedStorageStatePersistenceService.cs", "_isolated_storage_state_persistence_service_8cs.html", "_isolated_storage_state_persistence_service_8cs" ],
    [ "IStatePersistenceService.cs", "_i_state_persistence_service_8cs.html", "_i_state_persistence_service_8cs" ],
    [ "IWorkItemExtensionService.cs", "_i_work_item_extension_service_8cs.html", "_i_work_item_extension_service_8cs" ],
    [ "IWorkItemTypeCatalogService.cs", "_i_work_item_type_catalog_service_8cs.html", "_i_work_item_type_catalog_service_8cs" ],
    [ "LoadedModuleInfo.cs", "_loaded_module_info_8cs.html", "_loaded_module_info_8cs" ],
    [ "ModuleEnumeratorException.cs", "_module_enumerator_exception_8cs.html", "_module_enumerator_exception_8cs" ],
    [ "ModuleLoaderService.cs", "_module_loader_service_8cs.html", "_module_loader_service_8cs" ],
    [ "ModuleLoadException.cs", "_module_load_exception_8cs.html", "_module_load_exception_8cs" ],
    [ "ReflectionModuleEnumerator.cs", "_reflection_module_enumerator_8cs.html", "_reflection_module_enumerator_8cs" ],
    [ "ServiceMissingException.cs", "_service_missing_exception_8cs.html", "_service_missing_exception_8cs" ],
    [ "StatePersistenceException.cs", "_state_persistence_exception_8cs.html", "_state_persistence_exception_8cs" ],
    [ "StreamStatePersistenceService.cs", "_stream_state_persistence_service_8cs.html", "_stream_state_persistence_service_8cs" ],
    [ "WindowsPrincipalAuthenticationService.cs", "_windows_principal_authentication_service_8cs.html", "_windows_principal_authentication_service_8cs" ],
    [ "WorkItemExtensionService.cs", "_work_item_extension_service_8cs.html", "_work_item_extension_service_8cs" ],
    [ "WorkItemTypeCatalogService.cs", "_work_item_type_catalog_service_8cs.html", "_work_item_type_catalog_service_8cs" ]
];