var dir_2062d514a4d7721c912473ad0185f212 =
[
    [ "ExchangeRates", "dir_fc0aabc6a5b2ad3a27e97e9d1c3617ad.html", "dir_fc0aabc6a5b2ad3a27e97e9d1c3617ad" ],
    [ "__Resources_AccountStatus.cs", "_____resources___account_status_8cs.html", null ],
    [ "__Resources_CategoryRuleType.cs", "_____resources___category_rule_type_8cs.html", null ],
    [ "__Resources_CategoryType.cs", "_____resources___category_type_8cs.html", null ],
    [ "__Resources_ContactPriority.cs", "_____resources___contact_priority_8cs.html", null ],
    [ "__Resources_LeadDublicateStatus.cs", "_____resources___lead_dublicate_status_8cs.html", null ],
    [ "__Resources_LeadMainFilter.cs", "_____resources___lead_main_filter_8cs.html", null ],
    [ "__Resources_LeadStatus.cs", "_____resources___lead_status_8cs.html", null ],
    [ "__Resources_PaymentStatus.cs", "_____resources___payment_status_8cs.html", null ],
    [ "__Resources_RelationshipCallType.cs", "_____resources___relationship_call_type_8cs.html", null ],
    [ "__Resources_RelationshipPriority.cs", "_____resources___relationship_priority_8cs.html", null ],
    [ "__Resources_RelationshipUserStatus.cs", "_____resources___relationship_user_status_8cs.html", null ],
    [ "__Resources_SalePriority.cs", "_____resources___sale_priority_8cs.html", null ],
    [ "__Resources_SaleStatus.cs", "_____resources___sale_status_8cs.html", null ],
    [ "__Resources_SummaryLeadStatus.cs", "_____resources___summary_lead_status_8cs.html", null ],
    [ "AccountStatus.cs", "_account_status_8cs.html", "_account_status_8cs" ],
    [ "AddresType.cs", "_ele_wise_8_e_l_m_a_8_c_r_m_2_c_r_m_2_enums_2_addres_type_8cs.html", "_ele_wise_8_e_l_m_a_8_c_r_m_2_c_r_m_2_enums_2_addres_type_8cs" ],
    [ "CategoryRuleType.cs", "_category_rule_type_8cs.html", "_category_rule_type_8cs" ],
    [ "CategoryType.cs", "_category_type_8cs.html", "_category_type_8cs" ],
    [ "ContactPriority.cs", "_contact_priority_8cs.html", "_contact_priority_8cs" ],
    [ "LeadDublicateStatus.cs", "_lead_dublicate_status_8cs.html", "_lead_dublicate_status_8cs" ],
    [ "LeadMainFilter.cs", "_lead_main_filter_8cs.html", "_lead_main_filter_8cs" ],
    [ "LeadStatus.cs", "_lead_status_8cs.html", "_lead_status_8cs" ],
    [ "PaymentStatus.cs", "_payment_status_8cs.html", "_payment_status_8cs" ],
    [ "RelationshipCallType.cs", "_relationship_call_type_8cs.html", "_relationship_call_type_8cs" ],
    [ "RelationshipPriority.cs", "_relationship_priority_8cs.html", "_relationship_priority_8cs" ],
    [ "RelationshipUserStatus.cs", "_relationship_user_status_8cs.html", "_relationship_user_status_8cs" ],
    [ "RuleDeletedCategoryAction.cs", "_rule_deleted_category_action_8cs.html", "_rule_deleted_category_action_8cs" ],
    [ "SalePriority.cs", "_sale_priority_8cs.html", "_sale_priority_8cs" ],
    [ "SaleStatus.cs", "_sale_status_8cs.html", "_sale_status_8cs" ],
    [ "SummaryLeadStatus.cs", "_summary_lead_status_8cs.html", "_summary_lead_status_8cs" ]
];