var dir_55d2334e5759e66001334aa279f4f82c =
[
    [ "__LogOutResponse_SR.cs", "_____log_out_response___s_r_8cs.html", null ],
    [ "__Resources_IPackageChanges.cs", "_____resources___i_package_changes_8cs.html", null ],
    [ "__Resources_PackageChangesStatus.cs", "_____resources___package_changes_status_8cs.html", null ],
    [ "ApiMethodResponse.cs", "_api_method_response_8cs.html", "_api_method_response_8cs" ],
    [ "ApiServiceVersionResponse.cs", "_api_service_version_response_8cs.html", "_api_service_version_response_8cs" ],
    [ "ApiVersionResponse.cs", "_api_version_response_8cs.html", "_api_version_response_8cs" ],
    [ "AuthResponse.cs", "_auth_response_8cs.html", "_auth_response_8cs" ],
    [ "CheckPermissionRequest.cs", "_check_permission_request_8cs.html", "_check_permission_request_8cs" ],
    [ "CheckPermissionResponse.cs", "_check_permission_response_8cs.html", "_check_permission_response_8cs" ],
    [ "DeletedIdsPackage.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_deleted_ids_package_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_deleted_ids_package_8cs" ],
    [ "EntityChangesResponse.cs", "_entity_changes_response_8cs.html", "_entity_changes_response_8cs" ],
    [ "EntityChangesSyncRequest.cs", "_entity_changes_sync_request_8cs.html", "_entity_changes_sync_request_8cs" ],
    [ "EntityFormData.cs", "_entity_form_data_8cs.html", "_entity_form_data_8cs" ],
    [ "EntityQueryRequest.cs", "_entity_query_request_8cs.html", "_entity_query_request_8cs" ],
    [ "EntityQueryResponse.cs", "_entity_query_response_8cs.html", "_entity_query_response_8cs" ],
    [ "IClientSessionDataSets.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_client_session_data_sets_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_client_session_data_sets_8cs" ],
    [ "IPackageChanges.cs", "_i_package_changes_8cs.html", "_i_package_changes_8cs" ],
    [ "IPackageChangesFilter.cs", "_i_package_changes_filter_8cs.html", "_i_package_changes_filter_8cs" ],
    [ "IPublicApplication.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_application_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_application_8cs" ],
    [ "IPublicApplicationCompatibilityError.cs", "_i_public_application_compatibility_error_8cs.html", "_i_public_application_compatibility_error_8cs" ],
    [ "IPublicApplicationToken.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_application_token_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_application_token_8cs" ],
    [ "IPublicCacheData.cs", "_i_public_cache_data_8cs.html", "_i_public_cache_data_8cs" ],
    [ "IPublicClientCacheToken.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_client_cache_token_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_client_cache_token_8cs" ],
    [ "IPublicClientSession.cs", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_client_session_8cs.html", "_ele_wise_8_e_l_m_a_8_s_d_k_2_ele_wise_2_e_l_m_a_2_a_p_i_2_models_2_i_public_client_session_8cs" ],
    [ "JwtAuthResponse.cs", "_jwt_auth_response_8cs.html", "_jwt_auth_response_8cs" ],
    [ "LogOutResponse.cs", "_log_out_response_8cs.html", "_log_out_response_8cs" ],
    [ "PackageBase.cs", "_package_base_8cs.html", "_package_base_8cs" ],
    [ "PackageChangesResponse.cs", "_package_changes_response_8cs.html", "_package_changes_response_8cs" ],
    [ "PackageChangesStatus.cs", "_package_changes_status_8cs.html", "_package_changes_status_8cs" ],
    [ "PackageChangesSyncData.cs", "_package_changes_sync_data_8cs.html", "_package_changes_sync_data_8cs" ],
    [ "PackageChangesSyncRequest.cs", "_package_changes_sync_request_8cs.html", "_package_changes_sync_request_8cs" ],
    [ "PackagesCacheData.cs", "_packages_cache_data_8cs.html", "_packages_cache_data_8cs" ],
    [ "PropertyFormItemData.cs", "_property_form_item_data_8cs.html", "_property_form_item_data_8cs" ],
    [ "PublicApplicationCompatibilityError.cs", "_public_application_compatibility_error_8cs.html", "_public_application_compatibility_error_8cs" ],
    [ "UpdateIdPackage.cs", "_update_id_package_8cs.html", "_update_id_package_8cs" ]
];