var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_managers =
[
    [ "BPMNProcessManager", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_managers_1_1_b_p_m_n_process_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_managers_1_1_b_p_m_n_process_manager" ],
    [ "ResponsibilityMatrixItemManager", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_managers_1_1_responsibility_matrix_item_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_managers_1_1_responsibility_matrix_item_manager" ]
];