var namespace_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions =
[
    [ "ClientDataException", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_client_data_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_client_data_exception" ],
    [ "ConnectionException", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_connection_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_connection_exception" ],
    [ "GateException", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_gate_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_gate_exception" ],
    [ "UnexpectedDataException", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_unexpected_data_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_s_m_s_1_1_exceptions_1_1_unexpected_data_exception" ]
];