var namespace_ele_wise_1_1_e_l_m_a_1_1_reports =
[
    [ "BPMApps", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_b_p_m_apps.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_b_p_m_apps" ],
    [ "Code", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_code.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_code" ],
    [ "CodeGeneration", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_code_generation.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_code_generation" ],
    [ "Components", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_components.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_components" ],
    [ "Db", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_db.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_db" ],
    [ "Deploy", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_deploy.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_deploy" ],
    [ "Design", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_design.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_design" ],
    [ "DevServer", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_dev_server.html", null ],
    [ "Documents", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_documents.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_documents" ],
    [ "DTO", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_d_t_o.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_d_t_o" ],
    [ "Exceptions", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_exceptions.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_exceptions" ],
    [ "Extensions", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_extensions.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_extensions" ],
    [ "FastReportPatch", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_fast_report_patch.html", null ],
    [ "Hql", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_hql.html", null ],
    [ "Listeners", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_listeners.html", null ],
    [ "Managers", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_managers.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_managers" ],
    [ "Mappings", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_mappings.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_mappings" ],
    [ "Mobile", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_mobile.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_mobile" ],
    [ "Models", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_models.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_models" ],
    [ "Parameters", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_parameters.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_parameters" ],
    [ "Processors", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors" ],
    [ "Properties", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_properties.html", null ],
    [ "Scripts", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_scripts.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_scripts" ],
    [ "Security", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_security.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_security" ],
    [ "Types", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_types.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_types" ],
    [ "Web", "namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_web.html", null ],
    [ "PermissionProvider", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_permission_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_permission_provider" ]
];