var namespace_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services =
[
    [ "CreateFilePreviewSettings", "class_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services_1_1_create_file_preview_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services_1_1_create_file_preview_settings" ],
    [ "FilePreviewServiceLocal", "class_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services_1_1_file_preview_service_local.html", "class_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services_1_1_file_preview_service_local" ],
    [ "ICreateFilePreviewSettings", "interface_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services_1_1_i_create_file_preview_settings.html", "interface_ele_wise_1_1_e_l_m_a_1_1_file_preview_1_1_local_service_1_1_services_1_1_i_create_file_preview_settings" ]
];