var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_gateways =
[
    [ "GatewayExecutingInfo", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_gateways_1_1_gateway_executing_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_gateways_1_1_gateway_executing_info" ],
    [ "IGatewayActivity", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_gateways_1_1_i_gateway_activity.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_diagrams_1_1_activities_1_1_gateways_1_1_i_gateway_activity" ]
];