var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models =
[
    [ "ChangeProcessVersionValidationResult", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_change_process_version_validation_result.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_change_process_version_validation_result" ],
    [ "IBPMNProcess", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_i_b_p_m_n_process.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_i_b_p_m_n_process" ],
    [ "IResponsibilityMatrixItem", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_i_responsibility_matrix_item.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_i_responsibility_matrix_item" ],
    [ "SwimlaneChangeInfo", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_swimlane_change_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_models_1_1_swimlane_change_info" ]
];