var namespace_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers =
[
    [ "IDataClassMetadataItemHeaderManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_i_data_class_metadata_item_header_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_i_data_class_metadata_item_header_manager" ],
    [ "IDataClassMetadataTypeReferenceService", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_i_data_class_metadata_type_reference_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_i_data_class_metadata_type_reference_service" ],
    [ "MetadataItemGroupManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_metadata_item_group_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_metadata_item_group_manager" ],
    [ "MetadataItemHeaderManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_metadata_item_header_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_metadata_item_header_manager" ],
    [ "MetadataItemManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_metadata_item_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_metadata_1_1_managers_1_1_metadata_item_manager" ]
];