var namespace_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_components_1_1_designer_1_1_settings =
[
    [ "DesignerComponentSettings", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_components_1_1_designer_1_1_settings_1_1_designer_component_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_packaging_1_1_components_1_1_designer_1_1_settings_1_1_designer_component_settings" ]
];