var namespace_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers =
[
    [ "AddressBaseManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_address_base_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_address_base_manager" ],
    [ "AddrManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_addr_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_addr_manager" ],
    [ "AnswerManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_answer_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_answer_manager" ],
    [ "BaseCrmManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_base_crm_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_base_crm_manager" ],
    [ "CategoryAssignMethodManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_category_assign_method_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_category_assign_method_manager" ],
    [ "CategoryManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_category_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_category_manager" ],
    [ "ContactManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contact_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contact_manager" ],
    [ "ContractorManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contractor_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contractor_manager" ],
    [ "ContractorTypeManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contractor_type_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contractor_type_manager" ],
    [ "ContractorWatchManagerExtension", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contractor_watch_manager_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_contractor_watch_manager_extension" ],
    [ "CrmAttachmentManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_crm_attachment_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_crm_attachment_manager" ],
    [ "CurrencyManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_currency_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_currency_manager" ],
    [ "ExchangeCurrencyRateManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_exchange_currency_rate_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_exchange_currency_rate_manager" ],
    [ "InpaymentManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_inpayment_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_inpayment_manager" ],
    [ "LeadDublicateStateManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_lead_dublicate_state_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_lead_dublicate_state_manager" ],
    [ "LeadManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_lead_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_lead_manager" ],
    [ "LeadTypeManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_lead_type_manager.html", null ],
    [ "MarketingActivityManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_activity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_activity_manager" ],
    [ "MarketingBaseManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_base_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_base_manager" ],
    [ "MarketingEffectManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_effect_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_effect_manager" ],
    [ "MarketingGroupManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_group_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_group_manager" ],
    [ "MarketingPaymentManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_payment_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_marketing_payment_manager" ],
    [ "PaymentManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_payment_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_payment_manager" ],
    [ "ProductManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_product_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_product_manager" ],
    [ "RegularCurrencyRateImportManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_regular_currency_rate_import_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_regular_currency_rate_import_manager" ],
    [ "RelationshipBaseManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_base_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_base_manager" ],
    [ "RelationshipCallManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_call_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_call_manager" ],
    [ "RelationshipMailManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_mail_manager.html", null ],
    [ "RelationshipManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_manager" ],
    [ "RelationshipMeetingManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_meeting_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_relationship_meeting_manager" ],
    [ "SaleFunnelManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_sale_funnel_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_sale_funnel_manager" ],
    [ "SaleManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_sale_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_sale_manager" ],
    [ "SaleStageManager", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_sale_stage_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_managers_1_1_sale_stage_manager" ]
];