var namespace_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension =
[
    [ "IKPIDimension", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension_1_1_i_k_p_i_dimension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension_1_1_i_k_p_i_dimension" ],
    [ "IKpiValueDimensionItem", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension_1_1_i_kpi_value_dimension_item.html", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension_1_1_i_kpi_value_dimension_item" ],
    [ "IKpiValueDimensionItemFilter", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension_1_1_i_kpi_value_dimension_item_filter.html", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_models_1_1_dimension_1_1_i_kpi_value_dimension_item_filter" ]
];