var namespace_ele_wise_1_1_e_l_m_a_1_1_history_1_1_components =
[
    [ "BaseHistoryCollectorCachable", "class_ele_wise_1_1_e_l_m_a_1_1_history_1_1_components_1_1_base_history_collector_cachable.html", "class_ele_wise_1_1_e_l_m_a_1_1_history_1_1_components_1_1_base_history_collector_cachable" ]
];