var namespace_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_1_1_models =
[
    [ "FooterFileModel", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_1_1_models_1_1_footer_file_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_1_1_models_1_1_footer_file_model" ]
];