var namespace_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions =
[
    [ "CheckPrerequisitesException", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_check_prerequisites_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_check_prerequisites_exception" ],
    [ "ConfigurationInitializeException", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_configuration_initialize_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_configuration_initialize_exception" ],
    [ "OtherConnectionsException", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_other_connections_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_other_connections_exception" ],
    [ "TransactionRequiredException", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_transaction_required_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_transaction_required_exception" ],
    [ "TransactionRollbackException", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_transaction_rollback_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_runtime_1_1_exceptions_1_1_transaction_rollback_exception" ]
];