var namespace_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format =
[
    [ "EmailFormatInfo", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format_1_1_email_format_info.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format_1_1_email_format_info" ],
    [ "EmailFormatSettings", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format_1_1_email_format_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format_1_1_email_format_settings" ],
    [ "EmailFormatSettingsModule", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format_1_1_email_format_settings_module.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_format_1_1_email_format_settings_module" ]
];