var namespace_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers =
[
    [ "EQL", "namespace_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_e_q_l.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_e_q_l" ],
    [ "AbstractNHEntityManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_abstract_n_h_entity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_abstract_n_h_entity_manager" ],
    [ "CompositeEntityManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_composite_entity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_composite_entity_manager" ],
    [ "DTOManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_d_t_o_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_d_t_o_manager" ],
    [ "DynamicEntityManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_dynamic_entity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_dynamic_entity_manager" ],
    [ "EntityChangesLoader", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_changes_loader.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_changes_loader" ],
    [ "EntityExtensionManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_extension_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_extension_manager" ],
    [ "EntityImplManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_impl_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_impl_manager" ],
    [ "EntityManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager" ],
    [ "EntityManagerBehavior", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager_behavior.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager_behavior" ],
    [ "EntityManagerMaker", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager_maker.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager_maker" ],
    [ "EntityManagerMakerBase", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager_maker_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_manager_maker_base" ],
    [ "EntityPermissionConfigurationManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_permission_configuration_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_entity_permission_configuration_manager" ],
    [ "FormDependencyDTOManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_form_dependency_d_t_o_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_form_dependency_d_t_o_manager" ],
    [ "ICompositeEntityManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_composite_entity_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_composite_entity_manager" ],
    [ "IEntityChangesLoader", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_changes_loader.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_changes_loader" ],
    [ "IEntityExistsManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_exists_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_exists_manager" ],
    [ "IEntityExtensionManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_extension_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_extension_manager" ],
    [ "IEntityManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_manager" ],
    [ "IEntityManagerAlias", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_manager_alias.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_manager_alias" ],
    [ "IEntityManagerBehavior", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_manager_behavior.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_manager_behavior" ],
    [ "IEntityMappingProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_mapping_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_mapping_provider" ],
    [ "IEntityPermissionConfigurationManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_permission_configuration_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_entity_permission_configuration_manager" ],
    [ "IFormDependencyDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_form_dependency_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_form_dependency_d_t_o_manager" ],
    [ "ILockManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_lock_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_lock_manager" ],
    [ "IManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_manager.html", null ],
    [ "IManagerMaker", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_manager_maker.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_manager_maker" ],
    [ "IModelManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_model_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_model_manager" ],
    [ "ITablePartManager", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_table_part_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_i_table_part_manager" ],
    [ "LockManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_lock_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_lock_manager" ],
    [ "MemoryEntityManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_memory_entity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_memory_entity_manager" ],
    [ "MemoryEntityManagerMaker", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_memory_entity_manager_maker.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_memory_entity_manager_maker" ],
    [ "ModelManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_model_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_model_manager" ],
    [ "SoftDeletableManagerBehavior", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_soft_deletable_manager_behavior.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_soft_deletable_manager_behavior" ],
    [ "TypedDynamicEntityManager", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_typed_dynamic_entity_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_model_1_1_managers_1_1_typed_dynamic_entity_manager" ]
];