var namespace_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs =
[
    [ "AttachmentTemplateInput", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs_1_1_attachment_template_input.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs_1_1_attachment_template_input" ],
    [ "BinaryFileTemplateInput", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs_1_1_binary_file_template_input.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs_1_1_binary_file_template_input" ],
    [ "BooleanTemplateInput", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs_1_1_boolean_template_input.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_common_1_1_template_inputs_1_1_boolean_template_input" ]
];