var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components =
[
    [ "BaseDocumentFromElementResolver", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components_1_1_base_document_from_element_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components_1_1_base_document_from_element_resolver" ],
    [ "DocflowDocumentFromElementResolver", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components_1_1_docflow_document_from_element_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components_1_1_docflow_document_from_element_resolver" ],
    [ "UserTaskDocumentFromElementResolver", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components_1_1_user_task_document_from_element_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_b_p_m_n_1_1_components_1_1_user_task_document_from_element_resolver" ]
];