var namespace_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions =
[
    [ "BulkDataImportException", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_bulk_data_import_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_bulk_data_import_exception" ],
    [ "DataSourceReadException", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_data_source_read_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_data_source_read_exception" ],
    [ "MapObjectInvalidWrongException", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_map_object_invalid_wrong_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_map_object_invalid_wrong_exception" ],
    [ "StopImportException", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_stop_import_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_bulk_data_import_1_1_exceptions_1_1_stop_import_exception" ]
];