var namespace_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services =
[
    [ "IProjectPlanObjectService", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_plan_object_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_plan_object_service" ],
    [ "IProjectPortletPageUpdateQueueItemRepository", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_portlet_page_update_queue_item_repository.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_portlet_page_update_queue_item_repository" ],
    [ "IProjectRolesUpdateQueueItemRepository", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_roles_update_queue_item_repository.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_roles_update_queue_item_repository" ],
    [ "IProjectRolesUpdateService", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_roles_update_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_i_project_roles_update_service" ],
    [ "ProjectPlanObjectService", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_project_plan_object_service.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_services_1_1_project_plan_object_service" ]
];