var namespace_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extension_points =
[
    [ "CRMBulkDataImportHandler", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extension_points_1_1_c_r_m_bulk_data_import_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extension_points_1_1_c_r_m_bulk_data_import_handler" ],
    [ "IAddressProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extension_points_1_1_i_address_provider.html", "interface_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_extension_points_1_1_i_address_provider" ]
];