var namespace_ele_wise_1_1_e_l_m_a_1_1_security_1_1_property_handlers =
[
    [ "ChangeAuthorPropertyHandler", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_property_handlers_1_1_change_author_property_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_property_handlers_1_1_change_author_property_handler" ],
    [ "PropertyHandlersListener", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_property_handlers_1_1_property_handlers_listener.html", "class_ele_wise_1_1_e_l_m_a_1_1_security_1_1_property_handlers_1_1_property_handlers_listener" ]
];