var namespace_ele_wise_1_1_e_l_m_a_1_1_common_1_1_property_handlers =
[
    [ "AttachmentsPropertyHandler", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_property_handlers_1_1_attachments_property_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_property_handlers_1_1_attachments_property_handler" ],
    [ "CommentsPropertyHandler", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_property_handlers_1_1_comments_property_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_common_1_1_property_handlers_1_1_comments_property_handler" ]
];