var namespace_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_query_in_functions =
[
    [ "RelativeDateTimeFunction", "class_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_query_in_functions_1_1_relative_date_time_function.html", "class_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_query_in_functions_1_1_relative_date_time_function" ],
    [ "SubTypesFunction", "class_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_query_in_functions_1_1_sub_types_function.html", "class_ele_wise_1_1_e_l_m_a_1_1_extensions_1_1_query_in_functions_1_1_sub_types_function" ]
];