var namespace_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications =
[
    [ "CalendarEventNotificationsDataSource", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_calendar_event_notifications_data_source.html", null ],
    [ "CalendarTemplateGeneratorFunctions", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_calendar_template_generator_functions.html", null ],
    [ "ConfirmParticipationRecipientHandler", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_confirm_participation_recipient_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_confirm_participation_recipient_handler" ],
    [ "InformToRecipientHandler", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_inform_to_recipient_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_inform_to_recipient_handler" ],
    [ "ParticipantRecipientHandler", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_participant_recipient_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_participant_recipient_handler" ],
    [ "UserRecipientHandlerBase", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_user_recipient_handler_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_notifications_1_1_user_recipient_handler_base" ]
];