var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history =
[
    [ "DocumentTaskSettingsDocumentHistory", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_document_task_settings_document_history.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_document_task_settings_document_history" ],
    [ "RenderByDocumentTaskCloseHistory", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_render_by_document_task_close_history.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_render_by_document_task_close_history" ],
    [ "RenderDocumentTaskAddCommentHistory", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_render_document_task_add_comment_history.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_web_1_1_history_1_1_render_document_task_add_comment_history" ]
];