var namespace_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_extension_points =
[
    [ "IRuleModuleSettingsPageProvider", "interface_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_extension_points_1_1_i_rule_module_settings_page_provider.html", null ]
];