var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point =
[
    [ "DmsObjectBulkDataImportHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_dms_object_bulk_data_import_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_dms_object_bulk_data_import_handler" ],
    [ "DocumentBulkDataImportHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_document_bulk_data_import_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_document_bulk_data_import_handler" ],
    [ "FolderBulkDataImportHandler", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_folder_bulk_data_import_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_folder_bulk_data_import_handler" ],
    [ "IDocumentCreateCheckerExtension", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_i_document_create_checker_extension.html", "interface_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_extension_point_1_1_i_document_create_checker_extension" ]
];