var namespace_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_attributes =
[
    [ "AggregatorAttribute", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_attributes_1_1_aggregator_attribute.html", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_attributes_1_1_aggregator_attribute" ],
    [ "DiagnosticEventsAttribute", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_attributes_1_1_diagnostic_events_attribute.html", "class_ele_wise_1_1_e_l_m_a_1_1_diagnostics_1_1_attributes_1_1_diagnostic_events_attribute" ]
];