var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components =
[
    [ "ProcessMonitorIndicatorsExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components_1_1_process_monitor_indicators_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components_1_1_process_monitor_indicators_extension" ],
    [ "WorkflowInstanceIndicatorsExtension", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components_1_1_workflow_instance_indicators_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_components_1_1_workflow_instance_indicators_extension" ]
];