var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications =
[
    [ "TaskExriredRecipientHandler", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_task_exrired_recipient_handler.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_task_exrired_recipient_handler" ],
    [ "WorkflowNotificationsDataSource", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_workflow_notifications_data_source.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_workflow_notifications_data_source" ],
    [ "WorkflowProcessNotificationDataSource", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_workflow_process_notification_data_source.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_notifications_1_1_workflow_process_notification_data_source" ]
];