var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions =
[
    [ "DocumentActionException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_document_action_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_document_action_exception" ],
    [ "DocumentNotFoundException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_document_not_found_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_document_not_found_exception" ],
    [ "EncryptDocumentException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_encrypt_document_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_encrypt_document_exception" ],
    [ "EncryptDocumentVersionException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_encrypt_document_version_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_encrypt_document_version_exception" ],
    [ "RegistrationException", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_registration_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_exceptions_1_1_registration_exception" ]
];