var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_d_t_o_1_1_models =
[
    [ "BPMNProcessDTO", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_d_t_o_1_1_models_1_1_b_p_m_n_process_d_t_o.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_d_t_o_1_1_models_1_1_b_p_m_n_process_d_t_o" ],
    [ "ResponsibilityMatrixItemDTO", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_d_t_o_1_1_models_1_1_responsibility_matrix_item_d_t_o.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_b_p_m_n_1_1_d_t_o_1_1_models_1_1_responsibility_matrix_item_d_t_o" ]
];