var namespace_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_global_variable =
[
    [ "GlobalVariableAccessViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_global_variable_1_1_global_variable_access_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_global_variable_1_1_global_variable_access_view_item" ],
    [ "GlobalVariableValueEditorViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_global_variable_1_1_global_variable_value_editor_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_view_items_1_1_global_variable_1_1_global_variable_value_editor_view_item" ]
];