var namespace_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extensions =
[
    [ "BlockUserSelectGroupResolver", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extensions_1_1_block_user_select_group_resolver.html", "class_ele_wise_1_1_e_l_m_a_1_1_b_p_m_1_1_web_1_1_security_1_1_extensions_1_1_block_user_select_group_resolver" ]
];