var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_settings =
[
    [ "DocumentPropertySettings", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_settings_1_1_document_property_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_settings_1_1_document_property_settings" ],
    [ "RegistrationCardPropertySettings", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_settings_1_1_registration_card_property_settings.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_types_1_1_settings_1_1_registration_card_property_settings" ]
];