var namespace_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models =
[
    [ "ProjectTaskBasePackage", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_base_package.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_base_package" ],
    [ "ProjectTaskBaseWCF", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_base_w_c_f.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_base_w_c_f" ],
    [ "ProjectTaskPackage", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_package.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_package" ],
    [ "ProjectTaskWCF", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_w_c_f.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_a_p_i_1_1_models_1_1_project_task_w_c_f" ]
];