var namespace_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_exceptions =
[
    [ "BlockedPermissionException", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_exceptions_1_1_blocked_permission_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_c_r_m_1_1_exceptions_1_1_blocked_permission_exception" ]
];