var namespace_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models =
[
    [ "IntegrationActivityViewModel", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models_1_1_integration_activity_view_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models_1_1_integration_activity_view_model" ],
    [ "IntegrationModuleModel", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models_1_1_integration_module_model.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_modules_1_1_web_1_1_models_1_1_integration_module_model" ]
];