var namespace_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_d_t_o_1_1_managers =
[
    [ "ILinkWorkflowKpiDTOManager", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_d_t_o_1_1_managers_1_1_i_link_workflow_kpi_d_t_o_manager.html", "interface_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_d_t_o_1_1_managers_1_1_i_link_workflow_kpi_d_t_o_manager" ],
    [ "LinkWorkflowKpiDTOManager", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_d_t_o_1_1_managers_1_1_link_workflow_kpi_d_t_o_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_k_p_i_1_1_workflow_1_1_d_t_o_1_1_managers_1_1_link_workflow_kpi_d_t_o_manager" ]
];