var namespace_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_managers =
[
    [ "ExternalCalendarManager", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_managers_1_1_external_calendar_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_managers_1_1_external_calendar_manager" ],
    [ "InternetCalendarManager", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_managers_1_1_internet_calendar_manager.html", "class_ele_wise_1_1_e_l_m_a_1_1_calendar_1_1_export_1_1_managers_1_1_internet_calendar_manager" ]
];