var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_view_items =
[
    [ "DocumentTaskButtonsPanelViewItem", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_view_items_1_1_document_task_buttons_panel_view_item.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_docflow_1_1_view_items_1_1_document_task_buttons_panel_view_item" ]
];