var namespace_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i =
[
    [ "ITaskUpdatePackages", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i_1_1_i_task_update_packages.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i_1_1_i_task_update_packages" ],
    [ "ITaskWCFFiller", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i_1_1_i_task_w_c_f_filler.html", "interface_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i_1_1_i_task_w_c_f_filler" ],
    [ "TaskUpdatePackageServiceBase", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i_1_1_task_update_package_service_base.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_extension_points_1_1_a_p_i_1_1_task_update_package_service_base" ]
];