var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations =
[
    [ "HttpRequest", "namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_http_request.html", "namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_http_request" ],
    [ "BackgroundOperationResult", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_background_operation_result.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_background_operation_result" ],
    [ "IBackgroundOperationResult", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_i_background_operation_result.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_models_1_1_background_operations_1_1_i_background_operation_result" ]
];