var namespace_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security =
[
    [ "ProjectMetadataHeadRoleTypes", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_metadata_head_role_types.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_metadata_head_role_types" ],
    [ "ProjectPermissionsDelegate", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_permissions_delegate.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_permissions_delegate" ],
    [ "ProjectRoleTypes", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_role_types.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_role_types" ],
    [ "ProjectTaskBasePermissionsDelegate", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_task_base_permissions_delegate.html", "class_ele_wise_1_1_e_l_m_a_1_1_projects_1_1_security_1_1_project_task_base_permissions_delegate" ]
];