var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_controllers =
[
    [ "IndicatorController", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_controllers_1_1_indicator_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_controllers_1_1_indicator_controller" ],
    [ "ProcessMetricController", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_controllers_1_1_process_metric_controller.html", "class_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_indicators_1_1_web_1_1_controllers_1_1_process_metric_controller" ]
];