var namespace_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors =
[
    [ "DataBaseReportExternalDataSourceProcessor", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors_1_1_data_base_report_external_data_source_processor.html", "class_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors_1_1_data_base_report_external_data_source_processor" ],
    [ "IReportExternalDataSourceProcessor", "interface_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors_1_1_i_report_external_data_source_processor.html", "interface_ele_wise_1_1_e_l_m_a_1_1_reports_1_1_processors_1_1_i_report_external_data_source_processor" ]
];