var namespace_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security =
[
    [ "InstanceSettingsRegistrationPlacePermission", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_instance_settings_registration_place_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_instance_settings_registration_place_permission" ],
    [ "RegistrationPlaceInstanceDefaultPermission", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_registration_place_instance_default_permission.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_registration_place_instance_default_permission" ],
    [ "RegistrationPlaceRoleTypes", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_registration_place_role_types.html", "class_ele_wise_1_1_e_l_m_a_1_1_documents_1_1_security_1_1_registration_place_role_types" ]
];