var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions =
[
    [ "IProcessMetricColumn", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_column.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_column" ],
    [ "IProcessMetricContextMenu", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_context_menu.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_context_menu" ],
    [ "IProcessMetricDelete", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_delete.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_delete" ],
    [ "IProcessMetricSaveValue", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_save_value.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_process_metric_extensions_1_1_i_process_metric_save_value" ]
];