var namespace_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_mobile_1_1_extension_points =
[
    [ "IWorkflowTaskElement", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_mobile_1_1_extension_points_1_1_i_workflow_task_element.html", "interface_ele_wise_1_1_e_l_m_a_1_1_workflow_1_1_mobile_1_1_extension_points_1_1_i_workflow_task_element" ]
];