var namespace_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_1_1_exceptions =
[
    [ "GroupingMailMessagesException", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_1_1_exceptions_1_1_grouping_mail_messages_exception.html", "class_ele_wise_1_1_e_l_m_a_1_1_messaging_1_1_email_1_1_exceptions_1_1_grouping_mail_messages_exception" ]
];