var namespace_ele_wise_1_1_e_l_m_a_1_1_extension_points_1_1_header_buttons_services =
[
    [ "IHeaderButtonsPaperPinIsAvailableService", "interface_ele_wise_1_1_e_l_m_a_1_1_extension_points_1_1_header_buttons_services_1_1_i_header_butedfacfc7fd86aba28de117cf01ea32a7.html", "interface_ele_wise_1_1_e_l_m_a_1_1_extension_points_1_1_header_buttons_services_1_1_i_header_butedfacfc7fd86aba28de117cf01ea32a7" ],
    [ "IHeaderButtonsWatchIsAvailableService", "interface_ele_wise_1_1_e_l_m_a_1_1_extension_points_1_1_header_buttons_services_1_1_i_header_buttons_watch_is_available_service.html", "interface_ele_wise_1_1_e_l_m_a_1_1_extension_points_1_1_header_buttons_services_1_1_i_header_buttons_watch_is_available_service" ]
];