var namespace_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_work_log =
[
    [ "EmptyEntityWorkLogExtension", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_work_log_1_1_empty_entity_work_log_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_work_log_1_1_empty_entity_work_log_extension" ],
    [ "TaskBaseUpdateFactWorkLogExtension", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_work_log_1_1_task_base_update_fact_work_log_extension.html", "class_ele_wise_1_1_e_l_m_a_1_1_tasks_1_1_components_1_1_work_log_1_1_task_base_update_fact_work_log_extension" ]
];