var namespace_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_components_1_1_security =
[
    [ "ModulePermissionsPage", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_components_1_1_security_1_1_module_permissions_page.html", "class_ele_wise_1_1_e_l_m_a_1_1_business_rules_1_1_web_1_1_components_1_1_security_1_1_module_permissions_page" ]
];