var namespace_ele_wise_1_1_e_l_m_a_1_1_integration_infratel_1_1_components =
[
    [ "InfratelTelephonyProvider", "class_ele_wise_1_1_e_l_m_a_1_1_integration_infratel_1_1_components_1_1_infratel_telephony_provider.html", "class_ele_wise_1_1_e_l_m_a_1_1_integration_infratel_1_1_components_1_1_infratel_telephony_provider" ]
];